# Práctica 004: Diccionarios de Python aplicados a la teoría elemental de números

**Duración sugerida del video:** 15 minutos  
**Enfoque:** ciencia de datos y teoría elemental de números.

## Objetivos de aprendizaje

Al finalizar esta práctica, el estudiante podrá:

1. Crear diccionarios de Python con propiedades matemáticas.
2. Añadir nuevas parejas clave-valor y actualizar valores existentes.
3. Consultar valores utilizando sus claves y el método `get()`.
4. Organizar registros matemáticos en una colección y recorrerlos para analizar datos.

## Pregunta orientadora

¿Cómo podemos organizar información sobre números naturales para consultar y analizar sus propiedades mediante Python?

## 1. Introducción: organizar información matemática

En ciencia de datos no basta con almacenar números: también necesitamos asociarles información que permita interpretarlos. Para estudiar números naturales podemos registrar sus divisores, la cantidad de divisores y si son primos.

Un **diccionario** de Python es una estructura de datos que asocia cada **clave** con un **valor**. Las claves permiten identificar la información que queremos recuperar.

## 2. Crear un diccionario

Vamos a crear una ficha matemática para el número 7. Recordemos que 7 es primo y sus divisores positivos son 1 y 7.

In [1]:
numero_6 = {'numero':6, 
           'es_primo':True, 
           'divisores':[1,2,3,6], 
           'cantidad_divisores':4}

In [2]:
numero_6

{'numero': 6,
 'es_primo': True,
 'divisores': [1, 2, 3, 6],
 'cantidad_divisores': 4}

In [ ]:
# Diccionario con información sobre el número 7

numero_7 = {
    "numero": 7,
    "es_primo": True,
    "divisores": [1, 7],
    "cantidad_divisores": 2
}

print(numero_7)

### Interpretación

- `numero_6` es la variable que almacena el diccionario.
- Las llaves `{}` delimitan el diccionario.
- `"numero"`, `"es_primo"`, `"divisores"` y `"cantidad_divisores"` son las claves.
- `6`, `True`, `[1, 2, 3, 6]` y `4` son los valores asociados.

Los valores pueden ser de distintos tipos: enteros, booleanos, listas, cadenas de texto, entre otros.

In [3]:
numero_6.items() # el método items() sirve para convertir el diccionario en una lista de tuplas, 
# donde las componentes de estos pares ordenados son las parejas clave valor

dict_items([('numero', 6), ('es_primo', True), ('divisores', [1, 2, 3, 6]), ('cantidad_divisores', 4)])

In [4]:
# Consultar la estructura clave-valor de forma legible

for clave, valor in numero_6.items():
    print(f"Clave: {clave!r:24} | Valor: {valor}")

Clave: 'numero'                 | Valor: 6
Clave: 'es_primo'               | Valor: True
Clave: 'divisores'              | Valor: [1, 2, 3, 6]
Clave: 'cantidad_divisores'     | Valor: 4

## 3. Añadir nuevas parejas clave-valor

Podemos ampliar la ficha cuando necesitamos registrar nuevas propiedades. La instrucción `diccionario[clave] = valor` crea una nueva pareja si la clave no existe; si ya existe, reemplaza su valor.

In [6]:
# Agregar nuevas propiedades al número 7

numero_6["es_impar"] = False
numero_6["cuadrado"] = 6 ** 2
numero_6["cubo"] = 6 ** 3

print(numero_6)

{'numero': 6, 'es_primo': True, 'divisores': [1, 2, 3, 6], 'cantidad_divisores': 4, 'es_impar': False, 'cuadrado': 36, 'cubo': 216}

In [ ]:
numero_6

### Actualizar un valor existente

El siguiente ejemplo modifica intencionalmente el cuadrado de 7 para mostrar cómo funciona la actualización. **El valor 50 es incorrecto matemáticamente**: el cuadrado de 7 es 49. Después corregiremos el dato.

In [7]:
numero_6["cuadrado"] = 17
print("Cuadrado registrado:", numero_6["cuadrado"])

Cuadrado registrado: 17

In [8]:
# Corregir el dato para mantener la consistencia matemática
numero_6["cuadrado"] = 6 ** 2
print("Cuadrado corregido:", numero_6["cuadrado"])

Cuadrado corregido: 36

## 4. Acceder a los valores mediante sus claves

Cuando conocemos la clave de una propiedad, podemos recuperar su valor escribiendo `diccionario[clave]`.

In [16]:
numero_6['cubo']

216

In [ ]:
print("Número:", numero_7["numero"])
print("¿Es primo?", numero_7["es_primo"])
print("Divisores:", numero_7["divisores"])
print("Cantidad de divisores:", numero_7["cantidad_divisores"])
print("Cuadrado:", numero_7["cuadrado"])
print("Cubo:", numero_7["cubo"])

### Consultar con `get()`

El método `get()` permite consultar una clave sin provocar un `KeyError` si no existe. Podemos indicar un valor predeterminado.

In [17]:
print(numero_6.get("cantidad_divisores"))

4

In [19]:
print(numero_6.get("suma_divisores", "Dato no registrado"))

Dato no registrado

## 5. Aplicación a ciencia de datos: varios registros matemáticos

Cada diccionario puede representar una observación. La lista `datos` reúne varios registros, que después podemos recorrer para consultar propiedades o convertirlos en una tabla de Pandas.

In [20]:
# Datos de tres números naturales

numero_5 = {
    "numero": 5,
    "es_primo": True,
    "cantidad_divisores": 2
}

numero_6 = {
    "numero": 6,
    "es_primo": False,
    "cantidad_divisores": 4
}

numero_9 = {
    "numero": 9,
    "es_primo": False,
    "cantidad_divisores": 3
}

In [21]:
# Añadir el cuadrado a cada registro
numero_5["cuadrado"] = 5 ** 2
numero_6["cuadrado"] = 6 ** 2
numero_9["cuadrado"] = 9 ** 2

In [23]:
numero_5

{'numero': 5, 'es_primo': True, 'cantidad_divisores': 2, 'cuadrado': 25}

In [24]:
# Colección de registros
datos = [numero_5, numero_6, numero_9]

for registro in datos:
    print(
        registro["numero"],
        registro["es_primo"],
        registro["cantidad_divisores"],
        registro["cuadrado"]
    )

5 True 2 25
6 False 4 36
9 False 3 81

### Convertir los registros en una tabla con Pandas

Este paso conecta las estructuras básicas de Python con una herramienta muy utilizada en ciencia de datos. No es indispensable para comprender los diccionarios, pero muestra cómo pueden aprovecharse después.

In [25]:
import pandas as pd

df = pd.DataFrame(datos) # Una dataframe se puede formar a partir de una lista de diccionarios 
df

   numero  es_primo  cantidad_divisores  cuadrado
0       5      True                   2        25
1       6     False                   4        36
2       9     False                   3        81

## 6. Reto: detectar cuadrados perfectos

**Pregunta:** ¿cómo podemos agregar a cada registro una clave llamada `"es_cuadrado_perfecto"` que indique si el número es un cuadrado perfecto?

Por ejemplo, \(9 = 3^2\), por lo que 9 es un cuadrado perfecto. En cambio, 5 y 6 no lo son.

Primero intenta resolverlo por tu cuenta. Luego ejecuta la solución.

In [27]:
from math import isqrt, sqrt
isqrt(5), sqrt(5)

(2, 2.23606797749979)

In [28]:


for registro in datos:
    n = registro["numero"]
    registro["es_cuadrado_perfecto"] = isqrt(n) ** 2 == n

for registro in datos:
    print(registro["numero"], registro["es_cuadrado_perfecto"])

5 False
6 False
9 True

In [29]:
# Actualizar la tabla para incluir la nueva propiedad

df = pd.DataFrame(datos)
df

   numero  es_primo  cantidad_divisores  cuadrado  es_cuadrado_perfecto
0       5      True                   2        25                 False
1       6     False                   4        36                 False
2       9     False                   3        81                  True

## 7. Ejercicios de práctica

Resuelve estos ejercicios en nuevas celdas de código.

1. Crea un diccionario llamado `numero_12` con las claves `"numero"`, `"es_par"` y `"divisores"`. Usa los valores correctos para el número 12.
2. Añade la clave `"cuadrado"` con el cuadrado de 12.
3. Consulta e imprime el valor asociado a `"divisores"`.
4. Añade la clave `"cantidad_divisores"` con el número correcto de divisores positivos de 12.
5. Usa `get()` para consultar la clave `"es_primo"` con el texto `"Dato no registrado"` como valor predeterminado.
6. En la lista `datos`, añade una clave `"es_par"` a cada registro. El valor debe ser `True` cuando el número sea par y `False` en caso contrario.
7. Construye un `DataFrame` actualizado y filtra las filas que correspondan a cuadrados perfectos.

### Pistas

- Los divisores positivos de 12 son `[1, 2, 3, 4, 6, 12]`.
- Puedes usar `n % 2 == 0` para comprobar si un entero es par.
- En Pandas, una condición como `df[df["es_cuadrado_perfecto"]]` selecciona las filas donde esa columna es verdadera.

In [30]:
df[df['es_cuadrado_perfecto']]

   numero  es_primo  cantidad_divisores  cuadrado  es_cuadrado_perfecto
2       9     False                   3        81                  True

## 8. Resumen

| Operación | Ejemplo |
|---|---|
| Crear un diccionario | `d = {"numero": 7, "es_primo": True}` |
| Añadir o actualizar una pareja | `d["cuadrado"] = 49` |
| Consultar por clave | `d["numero"]` |
| Consultar con valor predeterminado | `d.get("suma_divisores", 0)` |
| Recorrer las parejas | `for clave, valor in d.items(): ...` |

**Idea central:** los diccionarios permiten organizar propiedades matemáticas mediante claves descriptivas. Combinados con listas, ciclos y Pandas, ayudan a construir conjuntos de datos, verificar propiedades y preparar información para investigaciones en ciencia de datos.