# Consultas `SELECT`

Dominar la sentencia `SELECT**` y sus cláusulas esenciales.

El enfoque será práctico y administrativo, 
* utilizando la misma base de datos de la `cafetería.db` que ya creamos en la ruta de la carpeta datos.



# Diseño de Clase: Extracción de Datos con SQL (`SELECT`)



**Objetivo de la clase:** ser capaces de escribir consultas con lenguaje SQL para:
* extraer, 
* filtrar, 
* ordenar y 
* limitar datos específicos de una base de datos relacional usando Pandas como puente.


## 1. La Anatomía de una Consulta `SELECT`


# El Orden Sintáctico (Cómo se escribe):

1. **`SELECT`** ¿Qué columnas quiero ver?
2. **`FROM`** ¿De qué tabla o archivo se van a sacar?
3. **`WHERE`** ¿Qué filtros deben cumplir las filas o instancias u observaciones?
4. **`ORDER BY`** ¿Cómo quiero ordenar el resultado?
5. **`LIMIT`** ¿Cuántos registros quiero mostrar?


## 2. Preparación del Entorno en Python

In [1]:
import pandas as pd
import sqlite3

In [2]:

# Conexión a nuestra base de datos de la cafetería
ruta = r"C:\Users\marco\Documentos\docencia\fundamentos_de_programacion\2_clases\unidad4\2_datos\cafeteria.db"
conexion = sqlite3.connect(ruta) # es para establecer el motor de conexion

print("Conexión establecida para la clase sobre la sentencia `SELECT.`")

Conexión establecida para la clase sobre la sentencia `SELECT.`


# 3. Ejercicios Prácticos Guiados

A partir de aquí, encuentras una guía para resolver retos de la administración de la cafetería.


# Reto 1: Consultar todo y columnas específicas (El inventario)

> **Problema de negocio:** El nuevo encargado de la cafetería quiere conocer qué productos vendemos y sus precios exactos.

* **Caso A: Traer toda la tabla (`*`)**

In [3]:
# El asterisco trae absolutamente todo
solicitud = "SELECT * FROM productos;"
df_productos = pd.read_sql_query(solicitud, conexion)
df_productos

   id_producto               nombre          categoria  precio
0          101        Café Espresso  Bebidas Calientes     2.5
1          102            Capuccino  Bebidas Calientes     3.8
2          103  Muffin de Arándanos         Repostería     4.0
3          104       Panini de Pavo          Alimentos     6.5
4          105             Té Verde      Bebidas Frías     3.0

# Práctica de codificación

In [4]:
import pandas as pd 
import sqlite3

In [5]:
conexion = sqlite3.connect(r"C:\Users\marco\Documentos\docencia\fundamentos_de_programacion\2_clases\unidad4\2_datos\cafeteria.db")

In [6]:
solicitud = "SELECT * From productos;"

In [7]:
df_productos = pd.read_sql_query(solicitud, conexion )

In [8]:
df_productos # visualizar el dataframe

   id_producto               nombre          categoria  precio
0          101        Café Espresso  Bebidas Calientes     2.5
1          102            Capuccino  Bebidas Calientes     3.8
2          103  Muffin de Arándanos         Repostería     4.0
3          104       Panini de Pavo          Alimentos     6.5
4          105             Té Verde      Bebidas Frías     3.0


* **Caso B: Traer columnas específicas (Buenas prácticas)**

In [9]:
# Es mejor especificar solo lo que el negocio necesita para ahorrar memoria
solicitud_columnas_especificas = "SELECT id_producto, nombre, precio FROM productos;"
df_columnas = pd.read_sql_query(solicitud_columnas_especificas, conexion)
df_columnas

   id_producto               nombre  precio
0          101        Café Espresso     2.5
1          102            Capuccino     3.8
2          103  Muffin de Arándanos     4.0
3          104       Panini de Pavo     6.5
4          105             Té Verde     3.0

# Práctica de codificación de la solicitud de columnas especóficas de una tabla dada

In [2]:
import sqlite3 
import pandas as pd

In [7]:
conexion = sqlite3.connect(r"C:\Users\marco\Documentos\docencia\fundamentos_de_programacion\2_clases\unidad4\2_datos\cafeteria.db")

In [11]:
solicitud = "SELECT nombre FROM productos;"

In [12]:
df_nombre_precio = pd.read_sql_query(solicitud,conexion)

In [13]:
df_nombre_precio

                nombre
0        Café Espresso
1            Capuccino
2  Muffin de Arándanos
3       Panini de Pavo
4             Té Verde


# Reto 2: Filtrar filas con `WHERE` (Análisis de Precios)

> **Problema de negocio:** Finanzas quiere evaluar si es necesario crear un "impuesto de lujo" o promoción especial para los productos que son caros (con un precio mayor o igual a $4.00).

In [10]:
# Usamos el operador >= para filtrar
query_filtro = """
SELECT nombre, categoria, precio 
FROM productos 
WHERE precio >= 4.00;
"""
df_filtro = pd.read_sql_query(query_filtro, conexion)
df_filtro

                nombre   categoria  precio
0  Muffin de Arándanos  Repostería     4.0
1       Panini de Pavo   Alimentos     6.5

# Práctica de codificación

In [9]:
import sqlite3
import pandas as pd

In [10]:
motor_conexion = sqlite3.connect(r"C:\Users\marco\Documentos\docencia\fundamentos_de_programacion\2_clases\unidad4\2_datos\cafeteria.db")

In [11]:
solicitud = """
SELECT nombre, precio
FROM productos
WHERE precio >= 4.00;
"""

In [12]:
df_productos_caros = pd.read_sql_query(solicitud, motor_conexion)
df_productos_caros

                nombre  precio
0  Muffin de Arándanos     4.0
1       Panini de Pavo     6.5


*Tip docente:* Explica que aquí se pueden usar operadores como `=`, `<`, `>`, `!=` y también texto (ej. `WHERE categoria = 'Bebidas Calientes'`).


# Reto 3: Ordenar datos con `ORDER BY` (Prioridades de Venta)

> **Problema de negocio:** El encargado de marketing quiere acomodar la pizarra del menú digital de la sucursal para que los productos aparezcan ordenados del más costoso al más barato.

In [11]:
# 'DESC' ordena de mayor a menor. 'ASC' (por defecto) de menor a mayor.
query_orden = """
SELECT nombre, precio 
FROM productos 
ORDER BY precio DESC;
"""
df_orden = pd.read_sql_query(query_orden, conexion)
df_orden

                nombre  precio
0       Panini de Pavo     6.5
1  Muffin de Arándanos     4.0
2            Capuccino     3.8
3             Té Verde     3.0
4        Café Espresso     2.5

# Práctica de codificación

In [12]:
import sqlite3
import pandas as pd

In [13]:
conexion = sqlite3.connect(r"C:\Users\marco\Documentos\docencia\fundamentos_de_programacion\2_clases\unidad4\2_datos\cafeteria.db")

In [19]:
solicitud = """
SELECT nombre, precio
FROM productos
ORDER BY precio ASC;
"""

In [20]:
df = pd.read_sql_query(solicitud, conexion)

In [21]:
df

                nombre  precio
0        Café Espresso     2.5
1             Té Verde     3.0
2            Capuccino     3.8
3  Muffin de Arándanos     4.0
4       Panini de Pavo     6.5



# Reto 4: Limitar resultados con `LIMIT` (El "Top")

> **Problema de negocio:** El Director General quiere ver una muestra rápida de las primeras 5 transacciones registradas en el sistema para verificar que los identificadores se estén generando correctamente.

In [9]:
# LIMIT restringe el número de filas devueltas
query_limite = """
SELECT id_transaccion, fecha_hora, cantidad 
FROM ventas 
LIMIT 2;
"""
df_limite = pd.read_sql_query(query_limite, conexion)
print(df_limite)

   id_transaccion           fecha_hora  cantidad
0            1001  2026-04-21 19:14:00         1
1            1002  2026-05-11 19:20:00         1


# 4. El Gran Reto Integrador (Evaluación o Práctica Autónoma)

Para consolidar el aprendizaje, se le pide a los alumnos que resuelvan el siguiente problema combinando todo lo aprendido:

> **Reto para el alumno:** El departamento de operaciones detectó una anomalía en las ventas. Necesitan un reporte que muestre únicamente el **nombre** y la **categoría** de los productos que pertenezcan a la categoría de **'Bebidas Calientes'** y cuyo precio sea **mayor a $3.00**, ordenados de forma **ascendente por su nombre**.


**Solución esperada que el alumno debe construir:**

In [ ]:
query_reto = """
SELECT nombre, categoria, precio
FROM productos
WHERE categoria = 'Bebidas Calientes' AND precio > 3.00
ORDER BY nombre ASC;
"""
df_resultado = pd.read_sql_query(query_reto, conexion)
print(df_resultado)


# 5. Cierre de la clase

* Recordar la importancia de cerrar la conexión con `conexion.close()`.
* Recalcar que el `SELECT` no modifica los datos de la base de datos, solo los "lee", por lo que es una herramienta completamente segura para un analista de negocios.

# Código para consultar de cada archivo .db los nombres de todas las tablas que contiene

Para conocer qué tablas existen dentro de un archivo `.db` (SQLite), debemos consultar una tabla oculta del sistema que se genera automáticamente en cada base de datos, llamada **`sqlite_master`**.


Aquí tienes el código limpio y estructurado utilizando **Pandas** y **SQLite**. Te incluyo dos opciones: una para un solo archivo y otra automatizada por si quieres escanear varios archivos `.db` dentro de una carpeta.

---


### Opción 1: Consultar las tablas de un solo archivo `.db`

Este script se conecta al archivo específico, extrae los nombres de las tablas y cierra la conexión inmediatamente.

In [13]:
import pandas as pd
import sqlite3

# 1. Ruta del archivo .db que deseas consultar
ruta_db = r"C:\Users\marco\Documentos\docencia\fundamentos_de_programacion\2_clases\unidad4\2_datos\cafeteria.db"

# 2. Abrir la conexión
conexion = sqlite3.connect(ruta_db)

# 3. Consulta SQL a la tabla maestra de SQLite
# Filtramos por type='table' para ignorar índices o vistas automáticas
query = "SELECT name AS nombre_tabla FROM sqlite_master WHERE type='table';"

# 4. Leer el resultado con Pandas
df_tablas = pd.read_sql_query(query, conexion)

# 5. Cerrar conexión
conexion.close()

# 6. Mostrar el resultado
print(f"--- Tablas encontradas en: {ruta_db.split('\\')[-1]} ---")
print(df_tablas)

--- Tablas encontradas en: cafeteria.db ---
  nombre_tabla
0    productos
1   sucursales
2       ventas


# Opción 2: Escanear una carpeta entera y listar las tablas de CADA archivo `.db`

Si estás administrando varias clases o proyectos y quieres saber qué hay dentro de cada archivo `.db` de esa carpeta de forma automatizada, este enfoque con `pathlib` te ahorrará mucho tiempo:

In [14]:
import pandas as pd
import sqlite3
from pathlib import Path

# 1. Definir la ruta de la carpeta contenedora
ruta_carpeta = Path(r"C:\Users\marco\Documentos\docencia\fundamentos_de_programacion\2_clases\unidad4\2_datos")

# 2. Buscar todos los archivos que terminen en .db en esa carpeta
archivos_db = list(ruta_carpeta.glob("*.db"))

print(f"Se encontraron {len(archivos_db)} archivos .db para analizar.\n")

# 3. Iterar sobre cada archivo encontrado
for ruta_archivo in archivos_db:
    try:
        # Conectar al archivo actual
        conn = sqlite3.connect(str(ruta_archivo))
        
        # Consulta para traer los nombres de las tablas
        query = "SELECT name FROM sqlite_master WHERE type='table';"
        df = pd.read_sql_query(query, conn)
        
        conn.close()
        
        # Mostrar resultados de forma ordenada
        print(f"==================================================")
        print(f"ARCHIVO: {ruta_archivo.name}")
        print(f"==================================================")
        if not df.empty:
            # Convertimos la columna a una lista para una lectura más limpia en consola
            lista_tablas = df['name'].tolist()
            for tabla in lista_tablas:
                print(f"  • {tabla}")
        else:
            print("  [La base de datos está vacía / no contiene tablas]")
        print("\n")
        
    except Exception as e:
        print(f"Error al leer el archivo {ruta_archivo.name}: {e}\n")

Se encontraron 2 archivos .db para analizar.

==================================================
ARCHIVO: cafeteria.db
==================================================
  • productos
  • sucursales
  • ventas


==================================================
ARCHIVO: caucasia_negocios.db
==================================================
  • clientes
  • ingresos_credito
  • satisfaccion_operaciones


```