# Archivos de Datos .csv y Bases de Datos .db de SQL

# Prompt para diseño de esta clase    

Dame el diseño de una clase, bien completa, sobre: "Archivos de Datos .csv y Bases de Datos .db de SQL", de 3 horas para la formación de estudiantes del segundo semestre de la carrera de Matemáticas en Caucasia - Antioquia (Colombia). Donde los temas a desarrollar sean:  

1. Creación de archivos de datos .csv a partit de DataFrame de Pandas. 
2. Creación de bases de datos sql con sqlite. 
3. Acceso a bases de datos sql con Pandas. 

Todo con una orientación hacia su utilización en ciencia de datos con ejemplos de la Teoría Elemental de Números y pensando en desarrollar las habilidades computacionales de los estudiantes para el curso de Métodos Numéricos I que verán en dos semestres. Esta es una clase para estudiantes que ya tienen los conceptos adquiricos de Tipos de datos, estructuras de datos incorporadas, Operadores, condicionales, ciclos, funciones, NumPy, Pandas y Matplotlib. Y esto teniendo en cuenta que el siguiente tema en este curso es "Análisis Descriptivo de Datos".

## Diseño de Clase: Archivos de Datos .csv y Bases de Datos .db de SQL

**Datos generales**
- **Curso:** Métodos Numéricos I (preparación previa)
- **Público:** Estudiantes de segundo semestre de Matemáticas, Caucasia, Antioquia
- **Duración:** 3 horas (180 minutos)
- **Prerrequisitos:** Tipos de datos, estructuras, operadores, condicionales, ciclos, funciones, NumPy, Pandas, Matplotlib
- **Tema siguiente del curso:** Análisis Descriptivo de Datos
- **Eje transversal:** Teoría Elemental de Números (divisibilidad, primos, congruencias, funciones aritméticas)
- **Habilidades computacionales objetivo:** Persistencia de datos, organización de información numérica, preparación para flujos de análisis descriptivo en Métodos Numéricos I



### 1. Objetivos de Aprendizaje

Al finalizar la clase, el estudiante estará en capacidad de:

1. **Exportar** DataFrames de Pandas a archivos `.csv` controlando parámetros clave (índice, separador, codificación) para preservar la integridad de datos numéricos.
2. **Crear** bases de datos SQLite (`.db`) desde Python, definiendo tablas con esquemas apropiados para datos provenientes de Teoría de Números.
3. **Acceder** a bases de datos SQL desde Pandas mediante `read_sql` y `to_sql`, integrándolas en flujos de trabajo que anticipan el Análisis Descriptivo de Datos.
4. **Seleccionar** críticamente entre CSV y base de datos según el volumen, la estructura y la necesidad de consulta de los datos.



# 2. Justificación y Contexto


En el curso de Métodos Numéricos I, los estudiantes trabajarán con conjuntos de datos que a menudo provienen de experimentos computacionales: tablas de funciones aritméticas, secuencias de residuos, conteos de primos en intervalos, entre otros.

Antes de aplicar técnicas descriptivas (medias, varianzas, histogramas), necesitan **saber almacenar, recuperar y organizar** esos datos de manera reproducible.


Esta clase resuelve una brecha práctica: los estudiantes ya saben manipular DataFrames en memoria, pero no persistirlos ni conectarlos con sistemas de almacenamiento estructurado.

Se usa **SQLite** por ser nativo de Python, sin servidor, y adecuado para entornos con recursos limitados como el aula de Caucasia.

Los ejemplos con Teoría de Números son deliberadamente simples en su lógica matemática pero ricos en estructura de datos, lo que permite concentrar la atención en los mecanismos de archivo y consulta.


### 3. Contenidos y Distribución del Tiempo

| Bloque | Tema | Tiempo | Modalidad |
|:---|:---|:---|:---|
| 1 | Creación de archivos `.csv` desde DataFrames de Pandas | 50 min | Exposición + práctica guiada |
| 2 | Creación de bases de datos SQLite con `sqlite3` | 55 min | Exposición + práctica guiada |
| 3 | Acceso a bases de datos SQL con Pandas | 55 min | Práctica integradora |
| — | Cierre, síntesis y conexión con Análisis Descriptivo | 20 min | Plenaria |


# 4. Desarrollo Detallado

## Bloque 1 — Creación de archivos `.csv` desde DataFrames de Pandas (50 min)


**1.1 Contextualización**

Se plantea una situación concreta: se ha calculado, con un script en Python, la **función φ de Euler** para los enteros del 1 al 100. El resultado está en un DataFrame. La pregunta es: ¿cómo conservarlo para analizarlo después sin recalcular?

Se discute brevemente por qué CSV es útil: legible por humanos, compatible con Excel y con otras herramientas, adecuado para datos tabulares planos.


**1.2 Demostración guiada (20 min)**

Se construye el DataFrame de ejemplo:

In [7]:
# función para el número de divisores de un número n, también llamada función tau(n)
def tau(n):
    count = 0
    for i in range(1, n + 1):
        if n % i == 0:
            count += 1
    return count

In [9]:
import numpy as np  
tau = np.vectorize(tau)  # Vectorizamos la función tau para que pueda aplicarse a arrays de NumPy

In [19]:
import pandas as pd
n = np.arange(1, 21)
datos = {
    'n': n,
    'phi': tau(n),
    'es_primo': tau(n) == 2
}
df = pd.DataFrame(datos)
df

     n  phi  es_primo
0    1    1     False
1    2    2      True
2    3    2      True
3    4    3     False
4    5    2      True
5    6    4     False
6    7    2      True
7    8    4     False
8    9    3     False
9   10    4     False
10  11    2      True
11  12    6     False
12  13    2      True
13  14    4     False
14  15    4     False
15  16    5     False
16  17    2      True
17  18    6     False
18  19    2      True
19  20    6     False

Exportación con parámetros comentados:

In [20]:
df.to_csv('phi_hasta_20.csv', index=False, encoding='utf-8')


**Puntos clave a explicar:**
- `index=False`: evita que el índice del DataFrame se escriba como una columna adicional, lo que suele confundir al reimportar.
- `encoding='utf-8'`: relevante si en el futuro se añaden columnas con texto en español.
- `sep`: por defecto `,`; en contextos donde se use Excel en configuración regional colombiana, puede requerirse `sep=';'`.


**1.3 Práctica guiada (15 min)**

Los estudiantes:
1. Crean un DataFrame con los **divisores de los números 1 al 15** (una fila por número, columna `n` y columna `num_divisores`).
2. Lo exportan a `divisores.csv` sin índice.
3. Reimportan con `pd.read_csv()` y verifican que los tipos de datos se conservaron.


**1.4 Cierre del bloque (5 min)**


Se enfatiza: CSV es un **formato de intercambio**, no una base de datos.

No impone tipos, no valida integridad, no permite consultas eficientes.

Esa limitación motiva el bloque siguiente.



## Bloque 2 — Creación de bases de datos SQLite con `sqlite3` (55 min)


**2.1 Motivación (10 min)**

Se retoma el ejemplo anterior: si en lugar de 20 números se tienen 100.000, y se quiere responder repetidamente preguntas como “¿cuántos primos hay entre 50.000 y 60.000?” o “¿cuál es el promedio de φ para n compuesto?”, releer todo el CSV en cada consulta es ineficiente. Una base de datos permite **indexar, filtrar y agregar** sin cargar todo en memoria.

SQLite se presenta como: biblioteca estándar de Python (`sqlite3`), sin instalación adicional, archivo único `.db`, ideal para aprender SQL sin administrar un servidor.


**2.2 Creación de la base de datos y la tabla (20 min)**

Demostración paso a paso:

In [21]:
import sqlite3

conexion = sqlite3.connect('teoria_numeros.db')
cursor = conexion.cursor()

cursor.execute('''
    CREATE TABLE IF NOT EXISTS funcion_phi (
        n INTEGER PRIMARY KEY,
        phi INTEGER NOT NULL,
        es_primo INTEGER NOT NULL
    )
''')
conexion.commit()

**Explicación de decisiones de diseño:**
- `n INTEGER PRIMARY KEY`: garantiza unicidad y acelera búsquedas por número.
- `es_primo INTEGER` en lugar de `BOOLEAN`: SQLite no tiene tipo booleano nativo; se usa 0/1 y se documenta la convención.
- `NOT NULL`: evita filas incompletas.


**2.3 Inserción de datos (15 min)**

In [ ]:
filas = [(n, phi, 1 if primo else 0) for n, phi, primo in
         zip(df['n'], df['phi'], df['es_primo'])]
# ojo, las filas son listas de tuplas, no un DataFrame. 
cursor.executemany(
    'INSERT OR REPLACE INTO funcion_phi (n, phi, es_primo) VALUES (?, ?, ?)',
    filas
)
conexion.commit()

Se discute `INSERT OR REPLACE` frente a `INSERT` simple: el primero permite reejecutar el script sin errores por clave duplicada.


**2.4 Consulta directa con SQL (10 min)**

In [24]:
cursor.execute('SELECT n, phi FROM funcion_phi WHERE es_primo = 0')
for fila in cursor.fetchall():
    print(fila)

(1, 1)
(4, 3)
(6, 4)
(8, 4)
(9, 3)
(10, 4)
(12, 6)
(14, 4)
(15, 4)
(16, 5)
(18, 6)
(20, 6)

Los estudiantes ejecutan una consulta propia: los números `n` donde `phi(n) = n - 1` (que corresponde a primos, propiedad elemental).


#### Bloque 3 — Acceso a bases de datos SQL con Pandas (55 min)

**3.1 Del cursor a Pandas (10 min)**

Se explica que `pd.read_sql()` envuelve la conexión y devuelve un DataFrame directamente, lo que evita iterar con `fetchall()` y facilita el análisis posterior.

In [16]:
import pandas as pd

df_primos = pd.read_sql(
    'SELECT n, phi FROM funcion_phi WHERE es_primo = 1 ORDER BY n',
    conexion
)
df_primos

    n  phi
0   2    2
1   3    2
2   5    2
3   7    2
4  11    2
5  13    2
6  17    2
7  19    2


**3.2 Consultas parametrizadas y agregaciones (20 min)**

Se construyen consultas que responden preguntas de Teoría de Números con estructura de análisis descriptivo:

In [17]:
# Promedio de phi según condición de primalidad
df_resumen = pd.read_sql('''
    SELECT
        es_primo,
        COUNT(*) AS cantidad,
        AVG(phi) AS phi_promedio,
        MIN(phi) AS phi_min,
        MAX(phi) AS phi_max
    FROM funcion_phi
    GROUP BY es_primo
''', conexion)
df_resumen

   es_primo  cantidad  phi_promedio  phi_min  phi_max
0         0        12      4.166667        1        6
1         1         8      2.000000        2        2

Esta consulta produce una tabla que **ya es un insumo directo** para el Análisis Descriptivo de Datos que verán a continuación: medias, conteos, extremos por grupo.


**3.3 Escritura desde Pandas hacia SQL (15 min)**

Se muestra el flujo inverso: si se calcula una nueva tabla (por ejemplo, la **función τ(n)** de número de divisores) en Pandas, se puede persistir en la misma base de datos:

In [18]:
def contar_divisores(n):
    return sum(1 for i in range(1, n + 1) if n % i == 0)

df_tau = pd.DataFrame({
    'n': list(range(1, 21)),
    'tau': [contar_divisores(n) for n in range(1, 21)]
})

df_tau.to_sql('funcion_tau', conexion, if_exists='replace', index=False)

20

Se explican las opciones de `if_exists`: `'fail'`, `'replace'`, `'append'`.

**3.4 Práctica integradora (10 min)**

Los estudiantes deben:
1. Consultar con `read_sql` los números `n` donde `phi(n)` es par (todos salvo n=1 y n=2, propiedad elemental que pueden verificar).
2. Exportar **ese resultado** a un CSV llamado `phi_pares.csv`.
3. Reflexionar: ¿en qué caso usarían CSV y en cuál SQLite?


### 5. Cierre y Conexión con Análisis Descriptivo (20 min)

**5.1 Síntesis colectiva (10 min)**

Se construye en tablero una tabla comparativa:

| Criterio | CSV | SQLite (.db) |
|:---|:---|:---|
| Estructura | Plana, sin tipos | Tablas con esquemas |
| Consulta | Carga completa en memoria | Filtros y agregaciones en disco |
| Volumen | Limitado por RAM | Escalable a millones de filas |
| Integridad | Ninguna | Restricciones (PK, NOT NULL) |
| Uso típico | Intercambio, respaldo simple | Análisis repetido, datos relacionales |


**5.2 Puente explícito al siguiente tema (10 min)**


Se plantea la pregunta que abre el Análisis Descriptivo de Datos: **“¿qué hacemos ahora que los datos están organizados y accesibles?”** Se anticipa que la respuesta involucrará medidas de tendencia central, dispersión y visualizaciones sobre los DataFrames que obtuvieron con `read_sql`. Se destaca que la consulta `SELECT es_primo, AVG(phi) FROM ... GROUP BY es_primo` ya produjo una tabla descriptiva básica.



### 6. Evaluación

**Formativa (durante la clase):**
- Observación de la práctica guiada en los bloques 1 y 2.
- Revisión rápida de la práctica integradora del bloque 3.

**Criterios de desempeño mínimos:**
- Exporta un DataFrame a CSV sin incluir el índice y lo reimporta correctamente.
- Crea una tabla en SQLite con clave primaria y restricciones básicas.
- Ejecuta al menos una consulta con `read_sql` que involucre filtro o agregación.

**Evidencia entregable (al finalizar la sesión):**
Un script de Python que: (a) genere un DataFrame con φ(n) y τ(n) para n de 1 a 50, (b) lo guarde en CSV, (c) cree una base `.db` con ambas funciones en tablas separadas, (d) consulte con Pandas el promedio de φ para n con τ(n) = 2 (primos).


### 7. Recursos y Consideraciones Logísticas

- **Equipos:** aula con computadores con Python 3.10+ y Pandas instalado (verificar previamente).
- **Archivos de apoyo:** ninguno externo; los datos se generan en clase.
- **Ritmo:** los ejemplos numéricos son deliberadamente pequeños (n ≤ 20, n ≤ 50) para que la atención esté en los mecanismos de archivo y consulta, no en la complejidad matemática.
- **Contexto local:** se menciona que SQLite es especialmente útil cuando no se dispone de servidores de bases de datos, situación común en laboratorios de cómputo con recursos limitados.

# Porciones de código para el parcial  

## Lista Estructurada de Porciones de Código para el Parcial

**Propósito:** Cada porción es una *plantilla mínima funcional* que el estudiante debe **adaptar** (no copiar literalmente) al ejercicio planteado. Se organizan por tema, con sintaxis estable y puntos de adaptación señalados explícitamente.

**Convención de marcadores:**
- `[...]` → el estudiante debe reemplazar según el enunciado.
- `# ADAPTAR:` → comentario que indica qué cambiar.
- Las plantillas están deliberadamente **incompletas en lógica de negocio** (no resuelven el ejercicio), pero **completas en sintaxis** (corren si se rellenan los marcadores).


### Tema 1 — Creación de archivos `.csv` desde DataFrames de Pandas

**P1.1 — Construcción de un DataFrame desde diccionario**
```python
import pandas as pd

datos = {
    'columna_1': [ ... ],   # ADAPTAR: lista de valores
    'columna_2': [ ... ],   # ADAPTAR: lista de valores
}
df = pd.DataFrame(datos)
print(df.head())
```

**P1.2 — Exportación básica a CSV sin índice**
```python
df.to_csv('[...].csv', index=False)   # ADAPTAR: nombre del archivo
```

**P1.3 — Exportación con parámetros controlados**
```python
df.to_csv(
    '[...].csv',          # ADAPTAR: nombre
    index=False,          # no escribir el índice
    sep=',',              # ADAPTAR: ',' o ';' según el enunciado
    encoding='utf-8',     # ADAPTAR: si hay texto en español
    header=True           # ADAPTAR: True si debe incluir encabezados
)
```

**P1.4 — Reimportación y verificación de tipos**
```python
df_leido = pd.read_csv('[...].csv')   # ADAPTAR: nombre del archivo
print(df_leido.dtypes)
print(df_leido.shape)
```

**P1.5 — Exportación de un subconjunto filtrado**
```python
df_filtrado = df[df['[...]'] [...] ]   # ADAPTAR: columna y condición
df_filtrado.to_csv('[...].csv', index=False)   # ADAPTAR: nombre
```

> **Nota para el estudiante:** estas cinco porciones cubren el ciclo completo *construir → exportar → reimportar → filtrar → exportar*. En el parcial se espera que las combine, no que las use aisladas.


### Tema 2 — Creación de bases de datos SQL con `sqlite3`

**P2.1 — Conexión y creación del archivo `.db`**
```python
import sqlite3

conexion = sqlite3.connect('[...].db')   # ADAPTAR: nombre de la BD
cursor = conexion.cursor()
```

**P2.2 — Creación de tabla con restricciones**
```python
cursor.execute('''
    CREATE TABLE IF NOT EXISTS [...] (       -- ADAPTAR: nombre de tabla
        [...] INTEGER PRIMARY KEY,           -- ADAPTAR: columna clave
        [...] INTEGER NOT NULL,              -- ADAPTAR: columna numérica
        [...] INTEGER NOT NULL               -- ADAPTAR: columna numérica
    )
''')
conexion.commit()
```

**P2.3 — Inserción de una sola fila (parametrizada)**
```python
cursor.execute(
    'INSERT INTO [...] ([...], [...], [...]) VALUES (?, ?, ?)',   # ADAPTAR: tabla y columnas
    ([...], [...], [...])                                          # ADAPTAR: valores
)
conexion.commit()
```

**P2.4 — Inserción masiva con `executemany`**
```python
filas = [ (a, b, c) for a, b, c in zip([...], [...], [...]) ]   # ADAPTAR: origen de datos
cursor.executemany(
    'INSERT OR REPLACE INTO [...] ([...], [...], [...]) VALUES (?, ?, ?)',   # ADAPTAR
    filas
)
conexion.commit()
```

**P2.5 — Consulta directa con cursor (sin Pandas)**
```python
cursor.execute('SELECT [...] FROM [...] WHERE [...]')   # ADAPTAR: columnas, tabla, condición
resultados = cursor.fetchall()
for fila in resultados:
    print(fila)
```

**P2.6 — Cierre de la conexión**
```python
cursor.close()
conexion.close()
```

> **Nota para el estudiante:** `INSERT OR REPLACE` permite reejecutar el script sin errores por clave duplicada. Si el enunciado pide solo insertar, use `INSERT`. El cierre de conexión es obligatorio para que el archivo `.db` quede consistente.


### Tema 3 — Acceso a bases de datos SQL con Pandas

**P3.1 — Consulta completa a DataFrame**
```python
import pandas as pd

df = pd.read_sql('SELECT * FROM [...]', conexion)   # ADAPTAR: tabla
print(df.head())
```

**P3.2 — Consulta con filtro y orden**
```python
df = pd.read_sql(
    'SELECT [...] FROM [...] WHERE [...] ORDER BY [...]',   # ADAPTAR
    conexion
)
```

**P3.3 — Consulta con agregación y `GROUP BY`**
```python
df_resumen = pd.read_sql('''
    SELECT
        [...],                  -- ADAPTAR: columna de agrupación
        COUNT(*) AS cantidad,
        AVG([...]) AS promedio, -- ADAPTAR: columna numérica
        MIN([...]) AS minimo,   -- ADAPTAR
        MAX([...]) AS maximo    -- ADAPTAR
    FROM [...]
    GROUP BY [...]
''', conexion)
```

**P3.4 — Escritura de un DataFrame nuevo hacia la BD**
```python
df_nuevo.to_sql(
    '[...]',              # ADAPTAR: nombre de la tabla destino
    conexion,
    if_exists='replace',  # ADAPTAR: 'replace', 'append' o 'fail'
    index=False
)
```

**P3.5 — Flujo integrador: leer → filtrar → exportar**
```python
df = pd.read_sql('SELECT [...] FROM [...]', conexion)   # ADAPTAR
df_filtrado = df[df['[...]'] [...] ]                    # ADAPTAR: condición
df_filtrado.to_csv('[...].csv', index=False)            # ADAPTAR: nombre
```

**P3.6 — Cierre de conexión al terminar con Pandas**
```python
conexion.close()
```

> **Nota para el estudiante:** `read_sql` requiere una conexión **abierta**. Si la cierra antes, la consulta falla. Para múltiples consultas, mantenga la conexión abierta y ciérrela al final.


### Estructura sugerida del parcial (para el docente)

| Tipo de ítem | Porciones habilitadas | Competencia evaluada |
|:---|:---|:---|
| Ítem 1 (CSV) | P1.1, P1.2, P1.4 | Construir, exportar y verificar |
| Ítem 2 (CSV filtrado) | P1.1, P1.5, P1.4 | Filtrar y persistir subconjuntos |
| Ítem 3 (crear BD) | P2.1, P2.2, P2.3 | Esquema y restricciones |
| Ítem 4 (carga masiva) | P2.4, P2.5 | Inserción y verificación |
| Ítem 5 (acceso con Pandas) | P3.1, P3.3 | Consulta y agregación |
| Ítem 6 (integrador) | P3.5 + P1.3 | Flujo completo BD → filtro → CSV |

**Criterio de calificación sugerido:** se evalúa la **adaptación correcta de los marcadores** (`[...]`, `# ADAPTAR`) al contexto del enunciado, no la memorización literal. Un estudiante que deje un marcador sin reemplazar pierde el punto de ese ítem, aunque la sintaxis sea válida.

## Taller Presencial — 5 Ejercicios sin Resolver

**Instrucciones generales para el estudiante:**
- Cada ejercicio indica **qué porciones de código** debe adaptar (P1.x, P2.x, P3.x del material entregado).
- Los marcadores `[...]` y `# ADAPTAR` **deben** ser reemplazados; dejar uno sin reemplazar invalida ese ítem.
- Puede consultar el material de clase, pero **no copiar literalmente** las plantillas: debe adaptarlas al contexto numérico del enunciado.
- Al finalizar cada ejercicio, **verifique** que el archivo `.csv` o `.db` fue creado correctamente (abra el archivo o reimporte).
- Tiempo estimado total del taller: **90 minutos** (18 min por ejercicio).


### Ejercicio 1 — Función σ(n): suma de divisores a CSV

**Contexto matemático.** La función σ(n) (sigma de divisores) suma todos los divisores positivos de n. Para $n = 1, \ldots, 25$, se desea conservar los resultados para análisis posterior.

**Tarea:**
1. Construya un DataFrame con columnas `n` y `sigma` para n = 1..25. Use una función auxiliar `suma_divisores(n)`.

In [2]:
import pandas as pd 

def suma_divisores(n):
    return sum(i for i in range(1, n + 1) if n % i == 0)    

df_sigma = pd.DataFrame({
    'n': list(range(1, 21)),    
'sigma': [suma_divisores(n) for n in range(1, 21)]
})
df_sigma

     n  sigma
0    1      1
1    2      3
2    3      4
3    4      7
4    5      6
5    6     12
6    7      8
7    8     15
8    9     13
9   10     18
10  11     12
11  12     28
12  13     14
13  14     24
14  15     24
15  16     31
16  17     18
17  18     39
18  19     20
19  20     42

2. Exporte el DataFrame a `sigma_hasta_25.csv` **sin incluir el índice** y con separador `,`.

In [3]:
df_sigma.to_csv('sigma_hasta_20.csv', index=False, encoding='utf-8')

3. Reimporte el archivo y verifique: número de filas, número de columnas y tipos de datos.

In [4]:
df_sigma2 = pd.read_csv('sigma_hasta_20.csv')
df_sigma2

     n  sigma
0    1      1
1    2      3
2    3      4
3    4      7
4    5      6
5    6     12
6    7      8
7    8     15
8    9     13
9   10     18
10  11     12
11  12     28
12  13     14
13  14     24
14  15     24
15  16     31
16  17     18
17  18     39
18  19     20
19  20     42

4. Exporte un **subconjunto filtrado** con los $n$ donde $\sigma(n) > 2n$ (números abundantes) a `abundantes.csv`.

**Porciones habilitadas:** P1.1, P1.2, P1.4, P1.5.

**Pista:** para σ(n) puede usar una comprensión: `sum(i for i in range(1, n+1) if n % i == 0)`.

In [7]:
import numpy as np
def es_abundante(n):
    return suma_divisores(n) > 2 * n    
es_abundante = np.vectorize(es_abundante)  # Vectorizamos la función es_abundante para que pueda aplicarse a arrays de NumPy
df_abundante = df_sigma2[es_abundante(df_sigma2['n'])]
df_abundante  

df_abundante.to_csv('abundantes_hasta_20.csv', index=False, encoding='utf-8')


### Ejercicio 2 — Conteo de primos por intervalo a CSV

**Contexto matemático.** La función π(x) cuenta los primos ≤ x. Se desea una tabla que, para intervalos de tamaño 10 hasta 100, registre cuántos primos hay en cada intervalo.

**Tarea:**
1. Construya un DataFrame con columnas `intervalo` (texto, ej. `"1-10"`, `"11-20"`, …) y `cantidad_primos` para los intervalos [1,10], [11,20], …, [91,100].

In [9]:
#**Tarea:**
#1. Construya un DataFrame con columnas `intervalo` (texto, ej. `"1-10"`, `"11-20"`, …) y
# `cantidad_primos` para los intervalos [1,10], [11,20], …, [91,100].

import pandas as pd
def tau(n):
    count = 0
    for i in range(1, n + 1):
        if n % i == 0:
            count += 1
    return count  

df_primos = pd.DataFrame({
    'intervalo': [f"{i}-{i+9}" for i in range(1, 100, 10)],
    'cantidad_primos': [sum(1 for n in range(i, i + 10) if tau(n) == 2) 
                        for i in range(1, 100, 10)]
})
df_primos

  intervalo  cantidad_primos
0      1-10                4
1     11-20                4
2     21-30                2
3     31-40                2
4     41-50                3
5     51-60                2
6     61-70                2
7     71-80                3
8     81-90                2
9    91-100                1

2. Exporte a `primos_por_intervalo.csv` con `index=False` y `encoding='utf-8'`.

In [10]:
df_primos.to_csv('cantidad_primos_por_intervalo.csv', index=False, encoding='utf-8')

3. Reimporte y verifique que la columna `cantidad_primos` sea de tipo entero.

In [11]:
df_primos2 = pd.read_csv('cantidad_primos_por_intervalo.csv')
df_primos2

  intervalo  cantidad_primos
0      1-10                4
1     11-20                4
2     21-30                2
3     31-40                2
4     41-50                3
5     51-60                2
6     61-70                2
7     71-80                3
8     81-90                2
9    91-100                1

4. Exporte a `intervalos_con_al_menos_3_primos.csv` solo los intervalos con 3 o más primos.

**Porciones habilitadas:** P1.1, P1.3, P1.4, P1.5.

**Pista:** defina `es_primo(n)` y úsela dentro de un ciclo por intervalos. No modifique el separador por defecto.

In [12]:
df_intervalos_con_al_menos_3_primos = df_primos2[df_primos2['cantidad_primos'] >= 3]
df_intervalos_con_al_menos_3_primos.to_csv('intervalos_con_al_menos_3_primos.csv', 
                                           index=False, encoding='utf-8')



### Ejercicio 3 — Base de datos de congruencias módulo 7

**Contexto matemático.** Para n = 1..30, se desea almacenar en una base de datos el residuo de n módulo 7 y si n es primo, para luego consultar patrones de congruencia.

**Tarea:**
1. Cree la base de datos `congruencias.db` y una tabla `modulo7` con columnas:
   - `n INTEGER PRIMARY KEY`
   - `residuo INTEGER NOT NULL`
   - `es_primo INTEGER NOT NULL` (convención: 1 = primo, 0 = no primo)

In [ ]:
import pandas as pd
df_modulo_7_primos = pd.DataFrame({
    'n': list(range(1, 101)),   
    'modulo_7': [n % 7 for n in range(1, 101)],
    'es_primo': [1 if tau(n) == 2 else 0 for n in range(1, 101)]
})
df_modulo_7_primos   
# creación de base de datos  
import sqlite3 

conexion = sqlite3.connect('congruencias.db' )
cursor = conexion.cursor()  

# creacion de tabla módulo 7
cursor.execute('''
    CREATE TABLE IF NOT EXISTS modulo_7_primos (
        n INTEGER PRIMARY KEY,
        modulo_7 INTEGER NOT NULL,
        es_primo INTEGER NOT NULL
    )
''')

2. Inserte las 30 filas usando `executemany` con `INSERT OR REPLACE`.

In [ ]:
cursor.executemany(
    "INSERT OR REPLACE INTO modulo_7_primos (n, modulo_7, es_primo) VALUES (?, ?, ?)",
    [(row['n'], row['modulo_7'], row['es_primo']) 
     for index, row in df_modulo_7_primos.iterrows()]
)

IntegrityError: datatype mismatch

In [17]:

cursor.execute("PRAGMA table_info(modulo_7_primos)")
print(cursor.fetchall())

[(0, 'n', 'INTEGER', 0, None, 1), (1, 'modulo_7', 'INTEGER', 1, None, 0), (2, 'es_primo', 'INTEGER', 1, None, 0)]

3. Ejecute con cursor **una** consulta que devuelva los n donde `residuo = 3` y `es_primo = 1`; imprima los resultados.

4. Cierre la conexión.

**Porciones habilitadas:** P2.1, P2.2, P2.4, P2.5, P2.6.

**Pista:** el residuo se calcula con `n % 7`. No olvide `conexion.commit()` después de la inserción masiva.

# Solución completa del ejercicio 3  

import sqlite3

# ---------------------------------------------------------------
# Funciones auxiliares
# ---------------------------------------------------------------
def es_primo(n):
    """Devuelve True si n es primo, False en caso contrario."""
    if n < 2:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True


# ---------------------------------------------------------------
# P2.1 — Conexión y creación del archivo .db
# ---------------------------------------------------------------
conexion = sqlite3.connect('congruencias.db')
cursor = conexion.cursor()

# ---------------------------------------------------------------
# P2.2 — Creación de la tabla con restricciones
# ---------------------------------------------------------------
cursor.execute('''
    CREATE TABLE IF NOT EXISTS modulo7 (
        n         INTEGER PRIMARY KEY,
        residuo   INTEGER NOT NULL,
        es_primo  INTEGER NOT NULL
    )
''')
conexion.commit()

# ---------------------------------------------------------------
# P2.4 — Inserción masiva con executemany
# ---------------------------------------------------------------
# Construimos las filas: (n, n % 7, 1 si primo else 0)
filas = [
    (n, n % 7, 1 if es_primo(n) else 0)
    for n in range(1, 31)
]

cursor.executemany(
    'INSERT OR REPLACE INTO modulo7 (n, residuo, es_primo) VALUES (?, ?, ?)',
    filas
)
conexion.commit()

print(f"Se insertaron {len(filas)} filas en la tabla 'modulo7'.")

# ---------------------------------------------------------------
# P2.5 — Consulta directa con cursor
# ---------------------------------------------------------------
cursor.execute('''
    SELECT n, residuo, es_primo
    FROM modulo7
    WHERE residuo = 3 AND es_primo = 1
    ORDER BY n
''')
resultados = cursor.fetchall()

print("\nNúmeros primos con residuo 3 (mód 7):")
print(" n  | residuo | es_primo")
print("----+---------+----------")
for fila in resultados:
    print(f" {fila[0]:>2} |    {fila[1]}    |    {fila[2]}")

# ---------------------------------------------------------------
# P2.6 — Cierre de la conexión
# ---------------------------------------------------------------
cursor.close()
conexion.close()
print("\nConexión cerrada. Base de datos 'congruencias.db' creada.")



### Ejercicio 4 — Segunda tabla en la misma base de datos

**Contexto matemático.** Se desea enriquecer `congruencias.db` con la función τ(n) (número de divisores) para los mismos n = 1..30, en una tabla separada.

**Tarea:**
1. Abra la base de datos `congruencias.db` creada en el Ejercicio 3.
2. Cree la tabla `divisores` con columnas `n INTEGER PRIMARY KEY` y `tau INTEGER NOT NULL`.
3. Inserte los 30 valores con `executemany`.
4. Con cursor, ejecute una consulta que devuelva los n donde `tau = 2` (que corresponden a primos) e imprímalos.
5. **Compare** (mentalmente o en comentario) los resultados con los de la tabla `modulo7`: ¿coinciden los primos? ¿Por qué?

**Porciones habilitadas:** P2.1, P2.2, P2.4, P2.5, P2.6.

**Pista:** esta vez **no** cree la base de datos, solo conéctese a la existente. Use `INSERT OR REPLACE` para poder reejecutar sin errores.


### Ejercicio 5 — Flujo integrador: SQL → Pandas → filtro → CSV

**Contexto matemático.** El objetivo es producir un reporte que, a partir de las tablas `modulo7` y `divisores` de `congruencias.db`, calcule cuántos primos hay por cada residuo módulo 7, y exporte ese resumen a CSV.

**Tarea:**
1. Conéctese a `congruencias.db` con `sqlite3`.
2. Con `pd.read_sql`, ejecute una consulta con `GROUP BY residuo` sobre la tabla `modulo7` que devuelva: `residuo`, `COUNT(*) AS total`, `SUM(es_primo) AS cantidad_primos`.
3. Con `pd.read_sql`, traiga la tabla `divisores` completa a un DataFrame.
4. **Combine** ambos DataFrames con `pd.merge` por la columna `n` (necesitará primero una consulta que traiga `n` y `residuo` de `modulo7`, o traer `modulo7` completo y hacer el merge). Documente en un comentario qué columnas quedan.
5. Exporte el DataFrame combinado a `reporte_congruencias.csv` con `index=False`, separador `;` y `encoding='utf-8'`.
6. Cierre la conexión.

**Porciones habilitadas:** P3.1, P3.2, P3.3, P3.4 (opcional si decide persistir el resumen), P3.5, P3.6, P1.3.

**Pista:** este ejercicio combina los tres temas. Si el merge falla, verifique que la columna `n` exista en ambos DataFrames y tenga el mismo tipo. El separador `;` es intencional para practicar P1.3.



### Tabla resumen para el docente

| Ejercicio | Tema principal | Porciones | Producto esperado | Tiempo |
|:---|:---|:---|:---|:---|
| 1 | CSV | P1.1, P1.2, P1.4, P1.5 | `sigma_hasta_25.csv`, `abundantes.csv` | 18 min |
| 2 | CSV | P1.1, P1.3, P1.4, P1.5 | `primos_por_intervalo.csv`, `intervalos_con_al_menos_3_primos.csv` | 18 min |
| 3 | SQLite | P2.1, P2.2, P2.4, P2.5, P2.6 | `congruencias.db` con tabla `modulo7` | 18 min |
| 4 | SQLite | P2.1, P2.2, P2.4, P2.5, P2.6 | Tabla `divisores` en `congruencias.db` | 18 min |
| 5 | Integrador | P3.1–P3.6, P1.3 | `reporte_congruencias.csv` | 18 min |


**Criterios de revisión rápida (para el docente durante el taller):**
- ¿El estudiante reemplazó **todos** los marcadores `[...]` y `# ADAPTAR`?
- ¿Verificó la creación del archivo (reimportó el CSV o consultó la BD)?
- ¿Cerró la conexión cuando correspondía?
- ¿El merge del Ejercicio 5 produjo un DataFrame con columnas coherentes?


**Nota:** los ejercicios 3 y 4 son secuenciales (comparten la misma base de datos). Si un estudiante no termina el 3, puede continuar el 4 sobre la base creada por un compañero o por el docente, siempre que documente en un comentario de dónde provino el archivo.