# Pandas para Ciencia de Datos y Teoría Elemental de Números

# Recrdar los elementos esenciales de NumPy  

1. la estructura de datos insignia es el nd-array()

In [1]:
import numpy as np

In [2]:
v_lista = [1,2,3]

In [3]:
2*v_lista

[1, 2, 3, 1, 2, 3]

In [4]:
v_vector = np.array(v_lista)

In [5]:
2*v_vector

array([2, 4, 6])

In [6]:
w = np.array([4, 5, 6])

In [7]:
v_vector + w

array([5, 7, 9])

In [8]:
A = np.array([[1,2], [3,4]])
A

array([[1, 2],
       [3, 4]])

In [9]:
w

array([4, 5, 6])

In [11]:
w[1]

np.int64(5)

In [12]:
w[1] = 5.0

In [13]:
w

array([4, 5, 6])

In [14]:
w[1]

np.int64(5)

In [15]:
v = np.array([1.5, 2.3, 5.1])
v[0]

np.float64(1.5)

In [16]:
len(v)

3

In [17]:
for i in range(len(v)):
    print(v[i])

1.5
2.3
5.1

In [22]:
v[0:4]

array([1.5, 2.3, 5.1])

In [23]:
A # los array de numpy no tienen ni numero ni nombre para las columnas y las filas

array([[1, 2],
       [3, 4]])

## Integración de Python, NumPy y Pandas

**Público:** estudiantes que ya conocen operadores, tipos de datos y estructuras incorporadas de Python, condicionales, ciclos funciones de usuario de Python.

**Duración sugerida:** 3 horas.  
**Herramientas:** Python, NumPy y Pandas. **No se utiliza Matplotlib.**

### Objetivos de aprendizaje
Al finalizar este cuaderno podrás:
1. Crear y explorar `Series` y `DataFrame` de Pandas.
2. Importar y usar NumPy junto con Pandas para generar y transformar datos.
3. Aplicar `if`, `elif`, `else`, `for` y `while` a problemas de clasificación, divisibilidad y primalidad.
4. Crear funciones con `def` y `lambda` para transformar y analizar datos.

5. Filtrar, agrupar y resumir datos con Pandas, relacionando ciencia de datos y teoría elemental de números.

**Metodología:** 
* predice la salida de cada celda antes de ejecutarla.   

* Después modifica los datos o las condiciones y explica qué cambia.

## 1. Preparación del entorno

Pandas trabaja con datos tabulares.   

NumPy complementa Pandas con arreglos y operaciones numéricas.

In [24]:
import numpy as np  # librería de cálculo numérico y vectorial 
import pandas as pd  # gestión de datos en forma  tabular

In [25]:
print("NumPy:", np.__version__)
print("Pandas:", pd.__version__)

NumPy: 2.4.6
Pandas: 3.0.3

## 2. Crear una `Series` y un `DataFrame`

Una `Series` es una secuencia etiquetada de datos.   

Un `DataFrame` es una tabla con filas y columnas.

In [4]:
notas = pd.Series([3.2, 4.1, 2.8, 4.7, 3.9], name="notas")
print(notas)

0    3.2
1    4.1
2    2.8
3    4.7
4    3.9
Name: notas, dtype: float64

In [32]:
edad = pd.Series([7.0, 89.0, 26.0, 16.0, 15.0, 19.0], name = 'edades_math')

In [33]:
edad

0     7.0
1    89.0
2    26.0
3    16.0
4    15.0
5    19.0
Name: edades_math, dtype: float64

In [37]:
edad[1]

np.float64(89.0)

In [31]:
v = np.array([[1], [2], [3]])
v

array([[1],
       [2],
       [3]])

In [5]:
print("Promedio:", notas.mean())

Promedio: 3.7399999999999998

In [6]:
notas.to_numpy()

array([3.2, 4.1, 2.8, 4.7, 3.9])

In [39]:
funda_programacion_dicc = {'nombres':['camilo', 'moises', 'juliana'], 
                     'edades':[21, 18, 21], 
                     'estaturas':[1.67, 1.64, 1.60]}

In [40]:
funda_programacion_dicc

{'nombres': ['camilo', 'moises', 'juliana'],
 'edades': [21, 18, 21],
 'estaturas': [1.67, 1.64, 1.6]}

In [48]:
df_marco = pd.DataFrame(funda_programacion_dicc)

In [49]:
df_marco

   nombres  edades  estaturas
0   camilo      21       1.67
1   moises      18       1.64
2  juliana      21       1.60

In [50]:
df_marco.nombres

0     camilo
1     moises
2    juliana
Name: nombres, dtype: str

In [7]:
estudiantes = pd.DataFrame({
    "estudiante": ["Ana", "Luis", "Marta", "José", "Sofía"],
    "edad": [18, 20, 19, 21, 18],
    "nota": notas.to_numpy()
})

In [9]:
display(estudiantes) # Un DataFrame se parece a una tabla de excel

  estudiante  edad  nota
0        Ana    18   3.2
1       Luis    20   4.1
2      Marta    19   2.8
3       José    21   4.7
4      Sofía    18   3.9

In [10]:
print("Dimensiones:", estudiantes.shape)

Dimensiones: (5, 3)

In [11]:
print("Columnas:", estudiantes.columns.tolist())

Columnas: ['estudiante', 'edad', 'nota']

In [12]:
print("Tipos:", estudiantes.dtypes)

Tipos: estudiante        str
edad            int64
nota          float64
dtype: object

### Actividad 1
* Crea un `DataFrame` llamado `grupo` con cinco filas y las columnas `id`, `edad` y `horas_estudio`.   
* Calcula el promedio de edad y de horas de estudio.

In [57]:
grupo = pd.DataFrame({
    "id": [101, 102, 103, 104, 105],
    "edad": [18, 22, 19, 20, 21],
    "horas de estudio": [2, 5, 3, 4, 6]
})

In [62]:
grupo[['id', 'edad']]

    id  edad
0  101    18
1  102    22
2  103    19
3  104    20
4  105    21

In [15]:
grupo['edad']

0    18
1    22
2    19
3    20
4    21
Name: edad, dtype: int64

In [63]:
(2/12)*20

3.333333333333333

In [56]:
grupo.horas_estudio.mean()

np.float64(4.0)

In [ ]:
print("Edad promedio:", grupo["edad"].mean())

In [17]:
print("Horas promedio:", grupo["horas_estudio"].mean())

Edad promedio: 20.0
Horas promedio: 4.0

## 3. Condicionales `if`, `elif` y `else`

Los condicionales permiten tomar decisiones para un valor individual.   

Las funciones que definamos después podrán aplicarse a columnas mediante `Series.apply`, aunque para condiciones simples es preferible la vectorización.

In [18]:
nota = 3.6

if nota >= 4.5:
    nivel = "Alto"
elif nota >= 3.0:
    nivel = "Aprobado"
else:
    nivel = "Debe mejorar"

print(f"Nota {nota}: {nivel}")

Nota 3.6: Aprobado

# Cómo crear nuevas columnas en un DatFrame

### 3.1 Clasificar una columna con una función

Aquí usamos `def` para expresar una regla de negocio legible y `apply` para aplicarla a cada valor.

In [19]:
def clasificar_nota(nota):
    if nota >= 4.5:
        return "Alto"
    elif nota >= 3.0:
        return "Aprobado"
    else:
        return "Debe mejorar"

estudiantes["nivel"] = estudiantes["nota"].apply(clasificar_nota)
display(estudiantes)

  estudiante  edad  nota         nivel
0        Ana    18   3.2      Aprobado
1       Luis    20   4.1      Aprobado
2      Marta    19   2.8  Debe mejorar
3       José    21   4.7          Alto
4      Sofía    18   3.9      Aprobado

### 3.2 Alternativa vectorizada con NumPy

Para reglas simples sobre toda una columna, `np.where` puede ser más directo que recorrer fila por fila.

In [20]:
estudiantes["estado"] = np.where(
    estudiantes["nota"] >= 3.0,
    "Aprueba",
    "No aprueba"
)
display(estudiantes)

  estudiante  edad  nota         nivel      estado
0        Ana    18   3.2      Aprobado     Aprueba
1       Luis    20   4.1      Aprobado     Aprueba
2      Marta    19   2.8  Debe mejorar  No aprueba
3       José    21   4.7          Alto     Aprueba
4      Sofía    18   3.9      Aprobado     Aprueba

In [23]:
estudiantes['nota'].sum()

np.float64(18.7)

In [26]:
estudiantes['nota'] >=3

0     True
1     True
2    False
3     True
4     True
Name: nota, dtype: bool

In [24]:
print("Cantidad que aprueba:", (estudiantes["nota"] >= 3.0).sum())

Cantidad que aprueba: 4

In [28]:
(estudiantes["nota"] >= 3.0)

0     True
1     True
2    False
3     True
4     True
Name: nota, dtype: bool

In [29]:
(estudiantes["nota"] >= 3.0).mean()

np.float64(0.8)

In [34]:
(estudiantes["nota"] >= 3.0).mean()

np.float64(0.8)

In [35]:
print("Porcentaje que aprueba:", 100 * (estudiantes["nota"] >= 3.0).mean(), "%")

Porcentaje que aprueba: 80.0 %

# [Video sobre como crear Series y DataFrame](https://www.youtube.com/watch?v=CESu7I4BOUM)

## 4. Pandas y teoría de números: divisibilidad

El operador módulo `%` calcula el residuo.   
Si `n % k == 0`, entonces `n` es múltiplo de `k` (para `k` distinto de cero).

In [37]:
numeros_ = pd.Series([i for i in range(1, 31)], name = 'n')
numeros_

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
19    20
20    21
21    22
22    23
23    24
24    25
25    26
26    27
27    28
28    29
29    30
Name: n, dtype: int64

In [55]:
numeros = pd.DataFrame({"n": np.arange(1, 31)})
numeros

     n
0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
9   10
10  11
11  12
12  13
13  14
14  15
15  16
16  17
17  18
18  19
19  20
20  21
21  22
22  23
23  24
24  25
25  26
26  27
27  28
28  29
29  30

In [56]:
numeros["par"] = numeros["n"] % 2 == 0
numeros

     n    par
0    1  False
1    2   True
2    3  False
3    4   True
4    5  False
5    6   True
6    7  False
7    8   True
8    9  False
9   10   True
10  11  False
11  12   True
12  13  False
13  14   True
14  15  False
15  16   True
16  17  False
17  18   True
18  19  False
19  20   True
20  21  False
21  22   True
22  23  False
23  24   True
24  25  False
25  26   True
26  27  False
27  28   True
28  29  False
29  30   True

In [57]:
numeros["multiplos_3"] = numeros["n"] % 3 == 0
numeros

     n    par  multiplos_3
0    1  False        False
1    2   True        False
2    3  False         True
3    4   True        False
4    5  False        False
5    6   True         True
6    7  False        False
7    8   True        False
8    9  False         True
9   10   True        False
10  11  False        False
11  12   True         True
12  13  False        False
13  14   True        False
14  15  False         True
15  16   True        False
16  17  False        False
17  18   True         True
18  19  False        False
19  20   True        False
20  21  False         True
21  22   True        False
22  23  False        False
23  24   True         True
24  25  False        False
25  26   True        False
26  27  False         True
27  28   True        False
28  29  False        False
29  30   True         True

In [58]:
numeros["multiplos_5"] = numeros["n"] % 5 == 0
numeros

     n    par  multiplos_3  multiplos_5
0    1  False        False        False
1    2   True        False        False
2    3  False         True        False
3    4   True        False        False
4    5  False        False         True
5    6   True         True        False
6    7  False        False        False
7    8   True        False        False
8    9  False         True        False
9   10   True        False         True
10  11  False        False        False
11  12   True         True        False
12  13  False        False        False
13  14   True        False        False
14  15  False         True         True
15  16   True        False        False
16  17  False        False        False
17  18   True         True        False
18  19  False        False        False
19  20   True        False         True
20  21  False         True        False
21  22   True        False        False
22  23  False        False        False
23  24   True         True        False
24  25  False        False         True
25  26   True        False        False
26  27  False         True        False
27  28   True        False        False
28  29  False        False        False
29  30   True         True         True

In [59]:
numeros["multiplo_3_y_5"] = numeros["multiplos_3"] & numeros["multiplos_5"]
numeros

     n    par  multiplos_3  multiplos_5  multiplo_3_y_5
0    1  False        False        False           False
1    2   True        False        False           False
2    3  False         True        False           False
3    4   True        False        False           False
4    5  False        False         True           False
5    6   True         True        False           False
6    7  False        False        False           False
7    8   True        False        False           False
8    9  False         True        False           False
9   10   True        False         True           False
10  11  False        False        False           False
11  12   True         True        False           False
12  13  False        False        False           False
13  14   True        False        False           False
14  15  False         True         True            True
15  16   True        False        False           False
16  17  False        False        False           False
17  18   True         True        False           False
18  19  False        False        False           False
19  20   True        False         True           False
20  21  False         True        False           False
21  22   True        False        False           False
22  23  False        False        False           False
23  24   True         True        False           False
24  25  False        False         True           False
25  26   True        False        False           False
26  27  False         True        False           False
27  28   True        False        False           False
28  29  False        False        False           False
29  30   True         True         True            True

In [60]:
display(numeros)

     n    par  multiplos_3  multiplos_5  multiplo_3_y_5
0    1  False        False        False           False
1    2   True        False        False           False
2    3  False         True        False           False
3    4   True        False        False           False
4    5  False        False         True           False
5    6   True         True        False           False
6    7  False        False        False           False
7    8   True        False        False           False
8    9  False         True        False           False
9   10   True        False         True           False
10  11  False        False        False           False
11  12   True         True        False           False
12  13  False        False        False           False
13  14   True        False        False           False
14  15  False         True         True            True
15  16   True        False        False           False
16  17  False        False        False           False
17  18   True         True        False           False
18  19  False        False        False           False
19  20   True        False         True           False
20  21  False         True        False           False
21  22   True        False        False           False
22  23  False        False        False           False
23  24   True         True        False           False
24  25  False        False         True           False
25  26   True        False        False           False
26  27  False         True        False           False
27  28   True        False        False           False
28  29  False        False        False           False
29  30   True         True         True            True

# Cómo acceder a los datos consignados en una estructura de DataFrame (DataFrame.loc, o DataFrame.iloc)

# Cómo acceder a los datos de una DataFrame con el método .loc()

In [63]:
numeros.columns

Index(['n', 'par', 'multiplos_3', 'multiplos_5', 'multiplo_3_y_5'], dtype='str')

# Cómo acceder a los datos de una DataFrame con el método .iloc()

In [71]:
numeros.loc[numeros['n'] > 10,'n'] # .loc[] para acceder con condiciones booleanas y nombres de filas o columnas

10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
19    20
20    21
21    22
22    23
23    24
24    25
25    26
26    27
27    28
28    29
29    30
Name: n, dtype: int64

In [ ]:
print("Pares:", numeros.loc[numeros["par"], "n"].tolist())

In [72]:
print("Múltiplos de 3 y 5:", numeros.loc[numeros["multiplo_3_y_5"], "n"].tolist())

Múltiplos de 3 y 5: [15, 30]

### Actividad 2
Crea un `DataFrame` con los enteros del 1 al 100 y agrega columnas que indiquen si cada número es múltiplo de 4, de 6 y de ambos. Filtra los múltiplos comunes y cuenta cuántos hay.

In [ ]:
tabla = pd.DataFrame({"n": np.arange(1, 101)})

In [ ]:
tabla["mult_4"] = tabla["n"] % 4 == 0
tabla["mult_6"] = tabla["n"] % 6 == 0
tabla["mult_4_y_6"] = tabla["mult_4"] & tabla["mult_6"]

display(tabla.loc[tabla["mult_4_y_6"]])
print("Cantidad:", tabla["mult_4_y_6"].sum())

## 5. Ciclo `for`: construir listas de divisores

Aunque Pandas y NumPy permiten vectorizar muchas operaciones, los ciclos son valiosos para aprender la lógica de un algoritmo. La función siguiente busca divisores de un entero positivo.

In [ ]:
def divisores_de(n):
    divisores = []
    for d in range(1, n + 1):
        if n % d == 0:
            divisores.append(d)
    return divisores

for n in [12, 18, 25]:
    print(f"Divisores de {n}: {divisores_de(n)}")

### 5.1 Enriquecer una tabla con resultados de una función

Aplicamos `divisores_de` a cada número y añadimos la cantidad de divisores como nueva columna.

In [ ]:
tabla_divisores = pd.DataFrame({"n": np.arange(1, 21)})
tabla_divisores["divisores"] = tabla_divisores["n"].apply(divisores_de)
tabla_divisores["cantidad_divisores"] = tabla_divisores["divisores"].apply(len)

display(tabla_divisores)
print("Números con exactamente 3 divisores:")
display(tabla_divisores.loc[tabla_divisores["cantidad_divisores"] == 3])

**Observación matemática:** los enteros positivos que tienen exactamente tres divisores son los cuadrados de números primos.

## 6. Ciclo `while`: detectar números primos

Un número primo es un entero mayor que 1 que tiene exactamente dos divisores positivos: 1 y él mismo. Basta probar posibles divisores hasta que `d * d > n`.

In [ ]:
def es_primo(n):
    if n < 2:
        return False
    d = 2
    while d * d <= n:
        if n % d == 0:
            return False
        d += 1
    return True

for n in [1, 2, 9, 17, 21, 29]:
    print(n, "es primo:", es_primo(n))

### 6.1 Crear una columna booleana de primalidad

La función `es_primo` usa un ciclo `while` por dentro. Luego Pandas la aplica a cada número de la tabla.

In [ ]:
primos_df = pd.DataFrame({"n": np.arange(1, 101)})
primos_df["es_primo"] = primos_df["n"].apply(es_primo)

display(primos_df.head(15))
print("Primos entre 1 y 100:")
print(primos_df.loc[primos_df["es_primo"], "n"].tolist())
print("Cantidad de primos:", primos_df["es_primo"].sum())

### Actividad 3
1. Prueba `es_primo` con `-3`, `0`, `1`, `2`, `49`, `97` y `100`.
2. Crea un `DataFrame` para los enteros del 1 al 1000 con una columna `es_primo`.
3. Calcula cuántos son primos y muestra los primeros 20.

In [ ]:
primos_1000 = pd.DataFrame({"n": np.arange(1, 1001)})
primos_1000["es_primo"] = primos_1000["n"].apply(es_primo)
print("Cantidad de primos:", primos_1000["es_primo"].sum())
print(primos_1000.loc[primos_1000["es_primo"], "n"].head(20).tolist())

## 7. Funciones `def` para preparar datos

Una función puede convertir un valor crudo en una categoría, validar una entrada o producir una característica derivada. La siguiente función clasifica números según su paridad y primalidad.

In [ ]:
def etiqueta_numero(n):
    if n < 2:
        return "menor que 2"
    elif es_primo(n):
        return "primo"
    elif n % 2 == 0:
        return "compuesto par"
    else:
        return "compuesto impar"

etiquetas = pd.DataFrame({"n": np.arange(1, 21)})
etiquetas["clasificacion"] = etiquetas["n"].apply(etiqueta_numero)
display(etiquetas)

## 8. Funciones `lambda` en Pandas

`lambda` es útil para expresar transformaciones pequeñas. En Pandas puede utilizarse con `apply`, aunque una operación vectorizada suele ser preferible cuando está disponible.

In [ ]:
muestra = pd.DataFrame({"n": [12, 25, 37, 40, 58, 63, 75]})
muestra["cuadrado"] = muestra["n"].apply(lambda x: x**2)
muestra["ultimo_digito"] = muestra["n"].apply(lambda x: x % 10)
muestra["termina_en_5"] = muestra["n"].apply(lambda x: x % 10 == 5)

display(muestra)
print("Números que terminan en 5:", muestra.loc[muestra["termina_en_5"], "n"].tolist())

### 8.1 Ordenar con `lambda`

El parámetro `key` de `sorted` recibe una función que determina el criterio de ordenamiento.

In [ ]:
valores = [31, 14, 22, 7, 45, 18, 29]
ordenados = sorted(valores, key=lambda x: x % 10)
print("Originales:", valores)
print("Ordenados por último dígito:", ordenados)

## 9. NumPy y Pandas en un flujo de ciencia de datos

Simularemos mediciones de un sensor con NumPy, construiremos una tabla con Pandas y analizaremos valores atípicos mediante filtros y resúmenes estadísticos.

In [ ]:
rng = np.random.default_rng(2026)
mediciones = rng.normal(loc=20, scale=2.5, size=100)
mediciones = np.round(mediciones, 2)
# Incluimos deliberadamente dos valores extremos para practicar su detección.
mediciones[5] = 35.0
mediciones[72] = 8.0

sensor = pd.DataFrame({
    "observacion": np.arange(1, len(mediciones) + 1),
    "medicion": mediciones
})

display(sensor.head())
display(sensor.describe())

### 9.1 Filtrar y resumir mediciones

En este ejemplo se considera inusual una medición que está por encima de 25 o por debajo de 12. El umbral es didáctico, no una regla universal.

In [ ]:
sensor["es_atipica"] = (sensor["medicion"] > 25) | (sensor["medicion"] < 12)
atipicas = sensor.loc[sensor["es_atipica"]]

print("Número de observaciones:", len(sensor))
print("Cantidad de observaciones atípicas:", len(atipicas))
display(atipicas)
print("Promedio general:", round(sensor["medicion"].mean(), 2))
print("Promedio sin observaciones atípicas:", round(sensor.loc[~sensor["es_atipica"], "medicion"].mean(), 2))

### 9.2 Clasificar mediciones con `if`, `elif` y `else`

In [ ]:
def clasificar_medicion(x):
    if x < 18:
        return "baja"
    elif x <= 23:
        return "habitual"
    else:
        return "alta"

sensor["categoria"] = sensor["medicion"].apply(clasificar_medicion)
display(sensor.head(10))
print(sensor["categoria"].value_counts())

## 10. Agrupación: propiedades de números

Pandas permite agrupar filas y resumir propiedades.   
Vamos a clasificar enteros por la cantidad de divisores positivos.

In [ ]:
def contar_divisores(n):
    cantidad = 0
    for d in range(1, n + 1):
        if n % d == 0:
            cantidad += 1
    return cantidad

numeros_df = pd.DataFrame({"n": np.arange(1, 101)})
numeros_df["es_par"] = numeros_df["n"] % 2 == 0
numeros_df["es_primo"] = numeros_df["n"].apply(es_primo)
numeros_df["cantidad_divisores"] = numeros_df["n"].apply(contar_divisores)
numeros_df["tipo_paridad"] = np.where(numeros_df["es_par"], "par", "impar")

display(numeros_df.head(12))
resumen = numeros_df.groupby("tipo_paridad").agg(
    cantidad=("n", "count"),
    promedio_divisores=("cantidad_divisores", "mean"),
    maximo_divisores=("cantidad_divisores", "max"),
    cantidad_primos=("es_primo", "sum")
)
display(resumen)

### Preguntas para interpretar el resumen
- ¿Por qué hay un número par de enteros y un número impar de enteros entre 1 y 100?
- ¿Por qué el grupo de números pares contiene un único primo?
- ¿Qué diferencia hay entre contar observaciones y calcular el promedio de una característica?
- ¿Qué operación del código corresponde a NumPy y cuál a Pandas?

## 11. Ejercicios de práctica independiente

Resuelve cada ejercicio en una o más celdas nuevas y explica tu estrategia.

1. **Tabla de múltiplos:** crea un `DataFrame` de los enteros del 1 al 500 con columnas que indiquen si cada número es múltiplo de 3, 5 y 15. Comprueba que todo múltiplo de 15 también es múltiplo de 3 y de 5.

2. **Primos:** genera una tabla de los números del 1 al 2000, marca los primos y calcula la proporción de primos en ese intervalo.

3. **Divisores:** añade una columna con la lista de divisores de cada entero entre 1 y 100. Encuentra los que tienen exactamente seis divisores.

4. **Datos simulados:** genera 500 mediciones enteras entre 1 y 100 con NumPy. Guárdalas en un `DataFrame` y calcula promedio, mediana, desviación estándar, mínimo y máximo.

5. **Condicionales:** define con `def` una función que clasifique un entero como negativo, cero, positivo par o positivo impar.

6. **`lambda`:** añade una columna que contenga el último dígito de cada número y filtra aquellos que terminen en 7.
7. **Agrupación:** crea una columna que indique si un número es múltiplo de 2, 3, 5 o de ninguno; agrupa por categoría y cuenta los casos.

8. **Reto:** encuentra los números del 1 al 1000 que tienen exactamente seis divisores. ¿Puedes relacionar el resultado con la factorización prima?

9. **Comparación:** resuelve el mismo filtro de múltiplos primero con un ciclo `for` y después con una máscara vectorizada. Compara claridad y tiempo de ejecución con `%timeit` en Jupyter.

## 12. Soluciones orientativas para algunos ejercicios

Intenta resolverlos antes de ejecutar estas celdas.

In [ ]:
# Ejercicio 2: primos hasta 2000
primos_df = pd.DataFrame({"n": np.arange(1, 2001)})
primos_df["es_primo"] = primos_df["n"].apply(es_primo)
cantidad_primos = int(primos_df["es_primo"].sum())

print("Cantidad de primos:", cantidad_primos)
print("Proporción de primos:", cantidad_primos / len(primos_df))
print("Primeros 20 primos:", primos_df.loc[primos_df["es_primo"], "n"].head(20).tolist())

In [ ]:
# Ejercicio 3: números con exactamente seis divisores hasta 100
divisores_df = pd.DataFrame({"n": np.arange(1, 101)})
divisores_df["cantidad_divisores"] = divisores_df["n"].apply(contar_divisores)
display(divisores_df.loc[divisores_df["cantidad_divisores"] == 6])

In [ ]:
# Ejercicio 6: números que terminan en 7
digitos_df = pd.DataFrame({"n": np.arange(1, 101)})
digitos_df["ultimo_digito"] = digitos_df["n"].apply(lambda x: x % 10)
display(digitos_df.loc[digitos_df["ultimo_digito"] == 7])

## 13. Síntesis y reflexión

- **Pandas:** `Series` y `DataFrame` representan y organizan datos tabulares; `loc`, `apply`, `groupby`, `agg` y `describe` ayudan a filtrarlos y resumirlos.
- **NumPy:** permite crear arreglos, simular datos, hacer cálculos numéricos y construir condiciones vectorizadas.
- **`if`, `elif`, `else`:** expresan decisiones para valores individuales y dentro de funciones.
- **`for` y `while`:** implementan búsquedas y algoritmos como la obtención de divisores y la prueba de primalidad.
- **`def` y `lambda`:** permiten encapsular reglas de análisis y transformar columnas.

### Pregunta de cierre
En un problema de ciencia de datos, ¿cuándo usarías una máscara vectorizada de NumPy, cuándo una operación de Pandas y cuándo una función que contiene un ciclo? Ilustra tu respuesta con un ejemplo de teoría de números.

# Taller de ejercicios para preparar el parcial  

# 20 Problemas de Evaluación en Python
## Temas: Condicionales (if/elif/else), Ciclos (for/while), Funciones (def/lambda) y Pandas (Series y DataFrame)
### Contexto: Ciencia de Datos y Teoría Elemental de Números

**Prerrequisitos asumidos:** operadores, tipos de datos, estructuras incorporadas, nd-arrays de NumPy, Series y DataFrame de Pandas.

---

## 🔹 BLOQUE 1: Condicionales (if, elif, else)

**Problema 1 — Clasificación de números primos en un DataFrame**
Dado un DataFrame con una columna `"numero"` que contiene enteros positivos, agrega una columna `"clasificacion"` usando condicionales, donde cada número se clasifique como `"primo"`, `"compuesto"` o `"ni primo ni compuesto"` (para 0 y 1).

In [1]:

import pandas as pd
df = pd.DataFrame({"numero": [1, 2, 7, 12, 17, 20, 0, 29]})
df

   numero
0       1
1       2
2       7
3      12
4      17
5      20
6       0
7      29

In [2]:
def numero_de_divisores(n):
    num_div = 0
    for d in range(1, n+1):
        if n % d == 0: 
            num_div += 1 # funcion que dice el número de divisores
    return num_div

In [3]:
numero_de_divisores(2)             # verifica si la función funciona

2

In [4]:
def clasificar_numero(n):
    if numero_de_divisores(n) < 2: 
        print('ni lo uno ni lo otro')     # Hace la función que clasifica
    elif numero_de_divisores(n) == 2:
        print('es primo')
    else:
        print('es compuesto')

In [5]:
clasificar_numero(0)             #  verifica su la clasificadora funciona

ni lo uno ni lo otro

In [8]:
df['clasificar'] = df['numero'].apply(clasificar_numero)           # aplica la función al dataframe para generar la nueva columna

ni lo uno ni lo otro
es primo
es primo
es compuesto
es primo
es compuesto
ni lo uno ni lo otro
es primo

In [9]:
df              # muestra el dataframe para ver si obtuvo lo que queriía

   numero clasificar
0       1       None
1       2       None
2       7       None
3      12       None
4      17       None
5      20       None
6       0       None
7      29       None

In [10]:
pd.__version__

'3.0.3'

In [11]:
df['Nueva Columna'] = range(8)

In [12]:
df

   numero clasificar  Nueva Columna
0       1       None              0
1       2       None              1
2       7       None              2
3      12       None              3
4      17       None              4
5      20       None              5
6       0       None              6
7      29       None              7

In [13]:
df = df[['numero', 'Nueva Columna', 'clasificar']]

In [14]:
df

   numero  Nueva Columna clasificar
0       1              0       None
1       2              1       None
2       7              2       None
3      12              3       None
4      17              4       None
5      20              5       None
6       0              6       None
7      29              7       None

**Problema 2 — Clasificación de correlaciones desde un DataFrame**
Dado un DataFrame con columnas `"variable_1"`, `"variable_2"` y `"r"` (coeficiente de correlación), agrega una columna `"nivel"` usando `if/elif/else` según:
- `|r| >= 0.9` → `"muy fuerte"`
- `0.7 <= |r| < 0.9` → `"fuerte"`
- `0.4 <= |r| < 0.7` → `"moderada"`
- `|r| < 0.4` → `"débil"`

---

**Problema 3 — Clasificación de outliers por IQR en un DataFrame**
Dado un DataFrame con una columna `"ventas"`, calcula Q1, Q3 e IQR con Pandas y agrega una columna `"tipo"` que clasifique cada valor como `"outlier inferior"`, `"outlier superior"` o `"normal"`.

```python
df = pd.DataFrame({"ventas": [10, 12, 14, 15, 16, 18, 20, 22, 100]})
```

---

**Problema 4 — Clasificación de edades con reglas de negocio**
Dado un DataFrame con una columna `"edad"`, agrega una columna `"categoria"`:
- `"menor"` si < 18
- `"adulto"` si 18 <= edad < 65
- `"mayor"` si >= 65

Además, agrega una columna `"par_impar"` que indique si la edad es par o impar usando el operador módulo.

---

## BLOQUE 2: Ciclos for y while

**Problema 5 — Criba de Eratóstenes aplicada a una Serie**
* Usando un ciclo `while` y una Serie de Pandas, implementa la criba de Eratóstenes para encontrar todos los primos menores que `n`. 
* Retorna una Serie con los primos.

In [5]:
import pandas as pd 
def serie_de_primos_menos_que(n):
    lista_num = range(2, n+1)
    lista_de_primos = [lista_num[0]]
    lista_num = [lista_num[i] for i in range(len(lista_num)) if lista_num[i] % lista_num[0] != 0]
    while len(lista_num) != 0:
        lista_de_primos.append(lista_num[0])
        lista_num = [lista_num[i] for i in range(len(lista_num)) if lista_num[i] % lista_num[0] != 0]
    return pd.Series(lista_de_primos)

In [8]:
serie_de_primos_menos_que(20)

0     2
1     3
2     5
3     7
4    11
5    13
6    17
7    19
dtype: int64

In [1]:
def primos_menores_que(n): 
    lista_num = range(2, n+1) 
    lista_primos = [lista_num[0]] 
    lista_num = [lista_num[i] for i in range(len(lista_num)) if lista_num[i]%lista_num[0] != 0]
    while len(lista_num) != 0:
        lista_primos.append(lista_num[0])
        lista_num = [lista_num[i] for i in range(len(lista_num)) if lista_num[i] % lista_num[0] != 0]
    return pd.Series(lista_primos)

In [4]:
primos_menores_que(10)

[2, 3, 5, 7]

In [ ]:
criba_serie(30)  # Serie: [2, 3, 5, 7, 11, 13, 17, 19, 23, 29]

**Problema 6 — Media móvil con ciclo while sobre un DataFrame**
Dado un DataFrame con una columna `"precio"`, calcula la media móvil de ventana `k` usando un ciclo `while` y agrega el resultado como una nueva columna `"media_movil"`.

```python
df = pd.DataFrame({"precio": [100, 102, 101, 105, 110, 108, 107]})
# k = 3
```

---

**Problema 7 — MCD de columnas numéricas con while**
Implementa el algoritmo de Euclides con un ciclo `while` para calcular el MCD de dos números. Luego, recorre con un ciclo `for` las columnas numéricas de un DataFrame y calcula el MCD de cada columna.

```python
df = pd.DataFrame({"a": [24, 36, 60], "b": [8, 16, 32]})
# MCD de "a" → 12 ; MCD de "b" → 8
```

---

**Problema 8 — Detección de valores nulos con for sobre un DataFrame**
Dado un DataFrame con valores `NaN`, recorre sus columnas con un ciclo `for` y construye un nuevo DataFrame con: nombre de la columna, cantidad de NaN, porcentaje de NaN y el índice de la primera fila con NaN.

In [ ]:
df = pd.DataFrame({
    "A": [1.0, 2.0, np.nan, 4.0],
    "B": [np.nan, 2.0, 3.0, np.nan]
})


**Problema 9 — Números perfectos y su almacenamiento en DataFrame**
Un número perfecto es igual a la suma de sus divisores propios. Usando ciclos, encuentra todos los números perfectos menores que `n` y guarda el resultado en un DataFrame con columnas `"numero"` y `"suma_divisores"`.

```python
# Para n = 1000 → [6, 28, 496]
```

---


**Problema 10 — Estandarización manual con ciclo for**
Dado un DataFrame con varias columnas numéricas, estandariza cada columna (media 0, desviación 1) usando un ciclo `for` (sin usar `(x - mean) / std` vectorizado directamente sobre el DataFrame completo). Retorna un nuevo DataFrame.

---


## 🔹 BLOQUE 3: Funciones con def

**Problema 11 — Función para números amigos sobre un DataFrame**
Dos números son amigos si la suma de los divisores propios de cada uno es igual al otro. Crea una función `son_amigos(a, b)` y úsala con un ciclo para filtrar, dentro de un DataFrame, las parejas de números amigos.

```python
df = pd.DataFrame({"a": [220, 118, 2620], "b": [284, 121, 2924]})
# Solo (220, 284) y (2620, 2924) son amigos
```

---


**Problema 12 — Función de normalización Min-Max sobre DataFrame**
Crea una función `min_max_scaling(df)` que reciba un DataFrame y retorne un nuevo DataFrame con cada columna numérica normalizada al rango [0, 1]. Maneja el caso donde `max == min` retornando 0 para esa columna.


**Problema 13 — Función para detectar duplicados en una Serie**
Crea una función `duplicados(serie)` que reciba una Serie de Pandas y retorne un DataFrame con dos columnas: `"valor"` y `"conteo"`, mostrando solo los valores duplicados y su frecuencia.

```python
s = pd.Series([1, 2, 2, 3, 3, 3, 4])
# Resultado: valor [2, 3]; conteo [2, 3]
```

---


**Problema 14 — Función de factorización prima sobre un DataFrame**
Crea una función `factorizar(n)` que retorne un diccionario con los factores primos de `n` y sus exponentes. Luego aplica la función a una columna de un DataFrame y agrega el resultado como una nueva columna.

```python
df = pd.DataFrame({"numero": [360, 128, 97]})
# 360 → {2:3, 3:2, 5:1}
```

---


**Problema 15 — Función de resumen estadístico por grupo**
Crea una función `resumen_por_grupo(df, columna_grupo, columna_valor)` que retorne un DataFrame con media, mediana, desviación estándar, mínimo, máximo y rango de `columna_valor` agrupado por `columna_grupo`.

```python
df = pd.DataFrame({
    "grupo": ["A", "A", "B", "B", "B"],
    "valor": [10, 20, 30, 40, 50]
})
```

---


## 🔹 BLOQUE 4: Funciones lambda

**Problema 16 — Filtrar primos con lambda y apply**
Usando `filter()` con una `lambda`, obtén los números primos de una Serie de Pandas. Luego construye un DataFrame con esos valores.

```python
s = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])
```

---


**Problema 17 — Ordenar un DataFrame por suma de dígitos con lambda**
Dado un DataFrame con una columna `"numero"`, ordénalo usando `sort_values()` con `key` (o `sorted()` con una `lambda`) según la suma de los dígitos de cada número, de menor a mayor.

```python
df = pd.DataFrame({"numero": [123, 45, 9, 1000, 56]})
# Orden: 1000, 9, 123, 45, 56
```

---

**Problema 18 — Transformación vectorizada con lambda sobre una Serie**
Usando `apply()` con una `lambda`, aplica la función `f(x) = x² + 3x + 1` a una Serie de Pandas y retorna una nueva Serie con los resultados.

In [44]:
s = pd.Series([1, 2, 3, 4])
# Resultado: [5, 11, 19, 29]

In [46]:
s.apply(lambda x:x**2+3*x+1)

0     1
1     4
2     9
3    16
dtype: int64


**Problema 19 — Mapeo de categorías con lambda y map**
Dado un DataFrame con una columna `"edad"`, usa `map()` con una `lambda` para clasificar cada edad como `"menor"`, `"adulto"` o `"mayor"`, y guarda el resultado en una nueva columna `"categoria"`.

In [47]:
df = pd.DataFrame({"edad": [15, 22, 70, 45, 17, 80]})
df

   edad
0    15
1    22
2    70
3    45
4    17
5    80

In [52]:
df['categoria'] = map(lambda x: 'menor' if x < 18 'adulto' if x >= 18 else 'mayor', df['edad'])
df

SyntaxError: expected 'else' after 'if' expression (3621773340.py, line 1)


**Problema 20 — Reducción con lambda: producto de primos en un DataFrame**
Usando `functools.reduce` con una `lambda`, calcula el producto de todos los números primos de una columna de un DataFrame. Agrega el resultado como un nuevo registro o muéstralo como salida.

```python
from functools import reduce
df = pd.DataFrame({"numero": [2, 3, 4, 5, 6, 7, 8]})
# Resultado: 210  (2 * 3 * 5 * 7)
```

---