<table align="left">
  <td>
    <a href="https://colab.research.google.com/github/marco-canas/fundamentos_de_programacion/blob/main/3_paciales/4_parcial/1_scripts/2_parcial_4_como_hacer_analisis_datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>
  </td>
  <td>
    <a target="_blank" href="https://kaggle.com/kernels/welcome?src=https://github.com/marco-canas/fundamentos_de_programacion/blob/main/3_paciales/4_parcial/1_scripts/2_parcial_4_como_hacer_analisis_datos.ipynb"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" /></a>
  </td>
</table>

# Parcial 4

### Habilidades a evaluar sobre Análisis de Datos Descriptivo

* Saber crear y leer un archivo de datos .csv y .xlsx

El siguiente son unos códigos en Python estructurados para generar **6 archivos `.csv` independientes** diseñados específicamente para evaluar habilidades en análisis descriptivo de datos de manera integral.


Siguiendo el enfoque didáctico y los lineamientos del cuaderno de Jupyter de la clase del capítulo 12 (enfocado en la manipulación práctica, limpieza de datos, y extracción de métricas clave), cada uno de estos datasets incluye anomalías simuladas de manera intencional: **valores nulos (`NaN`)**, **valores atípicos (*outliers*)**, **registros duplicados** y **datos inconsistentes**.

Esto permitirá evaluar no solo si el estudiante sabe graficar o promediar, sino si es capaz de limpiar y preparar la información antes de analizarla.


Puedes ejecutar el siguiente script completo.

Al finalizar, tendrás los 6 archivos listos en tu directorio de trabajo para ser entregados a tus alumnos.

In [ ]:
import numpy as np
import pandas as pd

# Configuración de semilla para reproducibilidad de los datos evaluativos
np.random.seed(42)

print("Iniciando la generación de los 6 datasets de evaluación...")

# =========================================================================
# DATASET 1: rendimiento_estudiantes.csv
# Objetivo de evaluación: Manejo de variables categóricas, cálculo de promedios
# ponderados, detección de outliers y correlación básica (Estudio vs Nota).
# =========================================================================
n_estudiantes = 120
data_estudiantes = {
    "ID_Estudiante": [f"EST-{i:03d}" for i in range(1, n_estudiantes + 1)],
    "Género": np.random.choice(["M", "F", "No Binario"], size=n_estudiantes, p=[0.45, 0.50, 0.05]),
    "Horas_Estudio_Semana": np.random.randint(2, 35, size=n_estudiantes),
    "Asistencia_Porcentaje": np.random.randint(50, 100, size=n_estudiantes),
    "Nota_Final": np.random.uniform(1.0, 5.0, size=n_estudiantes).round(1),
    "Socioeconómico": np.random.choice(["Bajo", "Medio", "Alto"], size=n_estudiantes, \
        p=[0.3, 0.6, 0.1])
}
df_1 = pd.DataFrame(data_estudiantes)
# Introducir Inconsistencias / Datos atípicos para evaluar la limpieza
df_1.loc[5, "Nota_Final"] = 55.0  # Outlier masivo (error de digitación)
df_1.loc[12, "Horas_Estudio_Semana"] = -5  # Valor ilógico
df_1.loc[25:27, "Asistencia_Porcentaje"] = np.nan  # Valores faltantes
df_1.to_csv(r"C:\Users\marco\Documentos\docencia\fundamentos_de_programacion\3_paciales\4_parcial\2_datos\rendimiento_estudiantes.csv", index=False)
print("- 'rendimiento_estudiantes.csv' generado con éxito.")


# =========================================================================
# DATASET 2: ventas_tienda_retail.csv
# Objetivo de evaluación: Análisis de series temporales sencillas, agregación 
# por categorías, cálculo de ingresos totales y margen de ganancia.
# =========================================================================
n_ventas = 200
fechas = pd.date_range(start="2026-01-01", periods=60, freq="D")
data_ventas = {
    "ID_Transaccion": [f"TX-{i:04d}" for i in range(1, n_ventas + 1)],
    "Fecha": np.random.choice(fechas, size=n_ventas),
    "Categoria_Producto": np.random.choice(["Electrónica", "Ropa", "Hogar", "Alimentos"], size=n_ventas),
    "Cantidad": np.random.choice([1, 2, 3, 4, 5], size=n_ventas, p=[0.5, 0.3, 0.1, 0.05, 0.05]),
    "Precio_Unitario": np.random.uniform(5.0, 500.0, size=n_ventas).round(2),
    "Metodo_Pago": np.random.choice(["Tarjeta", "Efectivo", "Transferencia"], size=n_ventas)
}
df_2 = pd.DataFrame(data_ventas)
# Duplicados e inconsistencias intencionales
df_2 = pd.concat([df_2, df_2.iloc[10:13]], ignore_index=True)  # Filas duplicadas
df_2.loc[40, "Cantidad"] = 500  # Outlier de volumen de compra
df_2.loc[60:64, "Precio_Unitario"] = np.nan  # Precios nulos que deben imputarse o descartarse
df_2.to_csv(r"C:\Users\marco\Documentos\docencia\fundamentos_de_programacion\3_paciales\4_parcial\2_datos\ventas_tienda_retail.csv", index=False)
print("- 'ventas_tienda_retail.csv' generado con éxito.")


# =========================================================================
# DATASET 3: uso_plataforma_streaming.csv
# Objetivo de evaluación: Segmentación de usuarios, distribuciones (histogramas) 
# de tiempos de uso y cálculo de métricas de retención de clientes.
# =========================================================================
n_usuarios = 150
data_streaming = {
    "ID_Usuario": [f"USR-{i:04d}" for i in range(1, n_usuarios + 1)],
    "Edad": np.random.randint(12, 75, size=n_usuarios),
    "Tipo_Suscripcion": np.random.choice(["Gratuito", "Básico", "Premium"], size=n_usuarios, p=[0.4, 0.4, 0.2]),
    "Minutos_Vistos_Mes": np.random.normal(loc=1200, scale=400, size=n_usuarios).astype(int),
    "Dispositivo_Principal": np.random.choice(["Smartphone", "Smart TV", "Laptop", "Tablet"], size=n_usuarios),
    "Cancelo_Suscripcion": np.random.choice(["Sí", "No"], size=n_usuarios, p=[0.15, 0.85])
}
df_3 = pd.DataFrame(data_streaming)
# Inconsistencias para la evaluación
df_3.loc[df_3["Minutos_Vistos_Mes"] < 0, "Minutos_Vistos_Mes"] = 0  # Corrección de colas de la normal
df_3.loc[15, "Edad"] = 150  # Outlier biológico
df_3.loc[33, "Tipo_Suscripcion"] = "PREMIUM_ERR"  # Categoría mal escrita para evaluar limpieza de strings
df_3.to_csv(r"C:\Users\marco\Documentos\docencia\fundamentos_de_programacion\3_paciales\4_parcial\2_datos\uso_plataforma_streaming.csv", index=False)
print("- 'uso_plataforma_streaming.csv' generado con éxito.")


# =========================================================================
# DATASET 4: indicadores_salud_hospital.csv
# Objetivo de evaluación: Cruzar variables numéricas continuas (Presión vs Colesterol), 
# análisis de subpoblaciones (Enfermos vs Sanos) y diagramas de caja (Boxplots).
# =========================================================================
n_pacientes = 100
data_salud = {
    "ID_Paciente": [f"PAC-{i:03d}" for i in range(1, n_pacientes + 1)],
    "Presion_Sistolica": np.random.randint(90, 180, size=n_pacientes),
    "Colesterol_mgDl": np.random.randint(150, 310, size=n_pacientes),
    "Fumador": np.random.choice(["Fumador", "No Fumador"], size=n_pacientes, p=[0.25, 0.75]),
    "IMC": np.random.uniform(18.5, 40.0, size=n_pacientes).round(1),
    "Diagnostico_Riesgo": np.random.choice(["Bajo", "Alto"], size=n_pacientes)
}
df_4 = pd.DataFrame(data_salud)
# Ruido artificial para evaluar
df_4.loc[8, "Presion_Sistolica"] = 12  # Error de medición (demasiado bajo)
df_4.loc[50:53, "Colesterol_mgDl"] = np.nan
df_4.to_csv(r"C:\Users\marco\Documentos\docencia\fundamentos_de_programacion\3_paciales\4_parcial\2_datos\indicadores_salud_hospital.csv", index=False)
print("- 'indicadores_salud_hospital.csv' generado con éxito.")


# =========================================================================
# DATASET 5: desempeño_empleados_rrhh.csv
# Objetivo de evaluación: Evaluación de métricas corporativas, análisis de la 
# brecha salarial por género, cálculo de mediana y variabilidad estándar.
# =========================================================================
n_empleados = 80
departamentos = ["IT", "Ventas", "Finanzas", "Marketing", "Recursos Humanos"]
data_rrhh = {
    "ID_Empleado": [f"EMP-{i:03d}" for i in range(1, n_empleados + 1)],
    "Departamento": np.random.choice(departamentos, size=n_empleados),
    "Anos_Experiencia": np.random.randint(0, 25, size=n_empleados),
    "Salario_Mensual_USD": np.random.randint(1200, 7500, size=n_empleados),
    "Puntuacion_Evaluacion": np.random.uniform(1.0, 5.0, size=n_empleados).round(2),
    "Modalidad": np.random.choice(["Remoto", "Presencial", "Híbrido"], size=n_empleados)
}
df_5 = pd.DataFrame(data_rrhh)
# Ruido estratégico
df_5.loc[14, "Salario_Mensual_USD"] = 95000  # CEO o Outlier extremo de nómina
df_5.loc[72, "Puntuacion_Evaluacion"] = np.nan
df_5.to_csv(r"C:\Users\marco\Documentos\docencia\fundamentos_de_programacion\3_paciales\4_parcial\2_datos\desempeño_empleados_rrhh.csv", index=False)
print("- 'desempeño_empleados_rrhh.csv' generado con éxito.")


# =========================================================================
# DATASET 6: contaminacion_ambiental_ciudades.csv
# Objetivo de evaluación: Análisis geográfico/regional descriptivo, detección de 
# días críticos y correlación multidimensional (Partículas vs Temperatura).
# =========================================================================
n_registros = 180
ciudades = ["Bogotá", "Medellín", "Cali", "Barranquilla", "Bucaramanga"]
data_ambiental = {
    "ID_Registro": [f"ENV-{i:03d}" for i in range(1, n_registros + 1)],
    "Ciudad": np.random.choice(ciudades, size=n_registros),
    "Nivel_PM25": np.random.uniform(5.0, 85.0, size=n_registros).round(1),
    "Temperatura_C": np.random.uniform(12.0, 34.0, size=n_registros).round(1),
    "Humedad_Porcentaje": np.random.randint(40, 95, size=n_registros),
    "Clasificacion_Calidad": np.random.choice(["Buena", "Moderada", "Dañina"], size=n_registros)
}
df_6 = pd.DataFrame(data_ambiental)
# Desafíos de análisis para el estudiante
df_6.loc[100:104, "Ciudad"] = np.nan  # Registros sin ubicación
df_6.loc[12, "Temperatura_C"] = -40.0  # Clima imposible para la muestra
df_6.to_csv(r"C:\Users\marco\Documentos\docencia\fundamentos_de_programacion\3_paciales\4_parcial\2_datos\contaminacion_ambiental_ciudades.csv", index=False)
print("- 'contaminacion_ambiental_ciudades.csv' generado con éxito.")

print("\n¡Proceso finalizado! Los 6 archivos CSV están listos para las evaluaciones.")

[Video de apoyo a la generación de los datos artificiales para análisis de datos](https://www.youtube.com/watch?v=JBd5R4H9jRc)


# Guía de preguntas recomendadas para la evaluación (Estilo Cuaderno de Jupyter):

Para asegurar un buen análisis descriptivo de cada archivo .csv, planteemos los siguientes **5 pasos descriptivos obligatorios** para resolver sobre cualquiera de los CSVs anteriores:


1. **Fase de Diagnóstico e Inspección:** * *Pregunta:* Usa `.info()`, `.describe()` y comprueba la suma de valores nulos (`.isnull().sum()`) y el método `.value_counts()`. ¿Qué anomalías estructurales detectas en los datos raw?

<img src = 'fase_1.png' width = 300>

2. **Fase de Limpieza Obligatoria:**
* *Pregunta:* Trata adecuadamente los registros identificados como erróneos o nulos (ya sea eliminándolos o sustituyéndolos mediante la mediana/media según corresponda). Justifica tu decisión técnica.

<img src = 'fase_2.png' width = 300>


3. **Métricas de Tendencia Central y Dispersión:**
* *Pregunta:* 
    * Agrupa el dataset por la columna categórica principal; y 
    * calcula el promedio, la mediana, el valor mínimo, el valor máximo y la desviación estándar de la variable numérica más importante. 
  
¿Qué conclusiones iniciales extraes de los segmentos?

<img src = 'fase_3.png' width = 300>


4. **Visualización de Distribuciones:**
* *Pregunta:* 
    * Genera un Histograma para evaluar la distribución de la variable continua principal y 
    * un Gráfico de Barras o Circular para representar las proporciones de las categorías (aplicando estilos estéticos como `plt.style.use()`).
<img src = 'fase_4.png' width = 300>



5. **Análisis de Relación/Correlación:**
* *Pregunta:* Construye un gráfico de dispersión (`plt.scatter`) entre dos variables numéricas candidatas. 
* Describe si observas una tendencia visual positiva, negativa o si los datos se encuentran completamente dispersos.

<img src = 'fase_5.png' width = 300>

[Video de apoyo a la presentación de las fases](https://www.youtube.com/watch?v=6udW3u-xYpQ)

[]()

# Asignación para Wilfran


# Evaluación Práctica: Análisis Descriptivo y Diagnóstico de Datos

**Dataset asignado:** `rendimiento_estudiantes.csv`

**Objetivo:** Evaluar las capacidades de: 
  * inspeccionar, 
  * limpiar, 
  * describir y 
  * encontrar relaciones en un conjunto de datos estructurado antes de proponer conclusiones o modelos predictivos.


# Actividad 1: Fase de Auditoría e Inspección de Calidad (Diagnóstico)

**Tareas para el estudiante:** 
1. Carga el archivo `rendimiento_estudiantes.csv` utilizando la librería `pandas`. Realiza una inspección técnica inicial utilizando los métodos `.info()`, `.describe()`, `.isnull().sum()`, y `value_counts()`.
2. Liste para cada variable del dataset: la naturaleza de la variable (cuantitativa, cualitativa), tipo de variable cuantitativa, y tipo de variable cualitativa o categórica. 
3. Redacta un párrafo en una celda *Markdown* detallando **tres anomalías o inconsistencias** que encontraste en los datos puros (*raw data*) y explica por qué representan un problema para un análisis estadístico válido.



* **¿Qué evalúa esta actividad?:** La capacidad de 
    * reconocer tipos de variables y 
    * detectar errores de digitación, 
    * valores faltantes o nulos, y 
    * valores fuera de límites lógicos (outliers).


# Parte 1: Celda de Código (Ejecución del Diagnóstico)

Los estudiantes deben cargar el archivo y ejecutar los métodos solicitados para exponer las fallas de los datos.

In [1]:
import pandas as pd

In [2]:
ubicacion_de_los_datos = r"C:\Users\marco\Documentos\docencia\fundamentos_de_programacion\3_paciales\4_parcial\2_datos\rendimiento_estudiantes.csv"

In [3]:
df = pd.read_csv(ubicacion_de_los_datos)

In [4]:
df

,ID_Estudiante,Género,Horas_Estudio_Semana,Asistencia_Porcentaje,Nota_Final,Socioeconómico
0,EST-001,M,29,79.0,3.6,Alto
1,EST-002,No Binario,26,78.0,2.7,Medio
2,EST-003,F,34,95.0,3.9,Medio
3,EST-004,F,2,55.0,1.2,Medio
4,EST-005,M,28,84.0,3.3,Medio
...,...,...,...,...,...,...
115,EST-116,F,6,89.0,1.9,Medio
116,EST-117,F,20,94.0,3.3,Alto
117,EST-118,M,5,50.0,4.5,Medio
118,EST-119,F,18,65.0,4.5,Alto
119,EST-120,F,29,88.0,1.9,Medio

In [5]:
df.head()

,ID_Estudiante,Género,Horas_Estudio_Semana,Asistencia_Porcentaje,Nota_Final,Socioeconómico
0,EST-001,M,29,79.0,3.6,Alto
1,EST-002,No Binario,26,78.0,2.7,Medio
2,EST-003,F,34,95.0,3.9,Medio
3,EST-004,F,2,55.0,1.2,Medio
4,EST-005,M,28,84.0,3.3,Medio

In [6]:
df.tail()

,ID_Estudiante,Género,Horas_Estudio_Semana,Asistencia_Porcentaje,Nota_Final,Socioeconómico
115,EST-116,F,6,89.0,1.9,Medio
116,EST-117,F,20,94.0,3.3,Alto
117,EST-118,M,5,50.0,4.5,Medio
118,EST-119,F,18,65.0,4.5,Alto
119,EST-120,F,29,88.0,1.9,Medio

In [ ]:
import pandas as pd

In [ ]:

# 1. Carga del conjunto de datos
ruta_csv = r"C:\Users\marco\Documentos\docencia\fundamentos_de_programacion\2_clases\unidad4\2_datos\rendimiento_estudiantes.csv"

In [ ]:
df_estudiantes = pd.read_csv(ruta_csv)

In [ ]:
df

In [ ]:
df_estudiantes.head()

In [ ]:
df.tail()

# Métodos que resumen de manera tabular los datos

In [ ]:

# 2. Inspección Estructural General
print("=== ESTRUCTURA DEL DATAFRAME (.info()) ===")
df_estudiantes.info()
print("\n" + "-"*60 + "\n")

In [ ]:

# 3. Resumen Estadístico de Variables Numéricas
print("=== ESTADÍSTICA DESCRIPTIVA (.describe()) ===")
print(df_estudiantes.describe())
print("\n" + "-"*60 + "\n")

In [ ]:

# 4. Conteo de Valores Faltantes o Nulos
print("=== CONTEO DE VALORES NULOS (.isnull().sum()) ===")
print(df_estudiantes.isnull().sum())
print("\n" + "-"*60 + "\n")

In [ ]:

# 5. Frecuencia de Variables Categóricas (Ejemplo con Socioeconómico)
print("=== DISTRIBUCIÓN DE VARIABLES CATEGÓRICAS (.value_counts()) ===")
if "Socioeconómico" in df_estudiantes.columns:
    print(df_estudiantes["Socioeconómico"].value_counts())


# 1. Reporte de Auditoría: Tres Anomalías Detectadas en los Datos Puros

Tras ejecutar el diagnóstico inicial sobre el archivo `rendimiento_estudiantes.csv`, se identificaron las siguientes tres inconsistencias críticas:

1. **Notas Finales fuera de la escala legal (`Nota_Final > 5.0`):** El método `.describe()` revela que el valor máximo registrado en la columna `Nota_Final` supera el límite de la escala académica institucional (la cual está parametrizada de 0.0 a 5.0). Esto representa un grave problema de **validez estadística**, ya que estos valores atípicos (*outliers*) artificiales sesgarán hacia arriba la media aritmética general, distorsionando los reportes de rendimiento y las decisiones sobre asignación de becas.
2. **Valores negativos en horas de estudio (`Horas_Estudio_Semana < 0`):** Se detectaron registros donde el tiempo de estudio semanal presenta valores inferiores a cero. Estadísticamente, el tiempo es una variable de razón con un cero absoluto (no existe el "tiempo negativo"). Esta inconsistencia matemática alterará las métricas de dispersión como la desviación estándar y destruirá la confianza de cualquier modelo de correlación o regresión lineal que intente vincular las horas de estudio con el éxito académico.
3. **Presencia de valores nulos en el indicador de asistencia (`Asistencia_Porcentaje`):** El método `.isnull().sum()` expuso la ausencia de datos en registros de asistencia. Los valores vacíos impiden realizar cálculos estadísticos continuos directos (generan errores o se omiten de forma inconsistente). Ignorar estos nulos o eliminarlos sin criterio reduce el tamaño de la muestra analizable y puede introducir un sesgo si la pérdida de datos no ocurrió de manera completamente aleatoria.

# 2. Clasificación Estricta de Variables (Tipos de Datos)

Con base en la naturaleza matemática de los atributos analizados mediante `.info()`, el dataset se compone de la siguiente manera:

* **Variables Cuantitativas (Numéricas):**
* `Nota_Final` (Cuantitativa Continua / Tipo: `float64`): Representa mediciones académicas que pueden tomar cualquier valor decimal dentro de un rango.
* `Horas_Estudio_Semana` (Cuantitativa Continua o Discreta según su registro / Tipo: `int64` o `float64`): Mide la magnitud temporal dedicada al aprendizaje.
* `Asistencia_Porcentaje` (Cuantitativa Continua / Tipo: `float64`): Expresa una proporción analítica respecto al total de clases obligatorias.


* **Variables Cualitativas (Categóricas):**
* `ID_Estudiante` (Cualitativa Nominal / Tipo: `object`): Funciona únicamente como un código identificador o etiqueta, carece de propiedades aritméticas.
* `Socioeconómico` (Cualitativa Ordinal / Tipo: `object`): Clasifica a los estudiantes en categorías discretas (Bajo, Medio, Alto) que poseen un orden jerárquico intrínseco o escala de nivel.
* `Género` / `Aprobado` (Cualitativa Nominal / Tipo: `object` o `bool`): Clasifica los perfiles en grupos basados en atributos mutuamente excluyentes sin un orden numérico.


# Actividad 2: Fase de Saneamiento y Curación de Datos (Limpieza)

**Consigna para el estudiante:** Aplica técnicas de limpieza para corregir las anomalías detectadas en la actividad anterior. Debes resolver obligatoriamente:

* El registro con la nota final errónea.
* El registro con las horas de estudio negativas.
* Las celdas vacías en el porcentaje de asistencia (justifica si decides eliminar las filas o realizar una imputación utilizando la media o la mediana).

Muestra el estado final del DataFrame usando `.describe()` para comprobar que los estadísticos ahora tienen coherencia matemática.

* **¿Qué evalúa esta actividad?:** La habilidad técnica para manipular DataFrames con Pandas (`.loc`, `.fillna()`, `.dropna()`) y el criterio analítico para tomar decisiones sobre datos faltantes o corruptos.

# Parte 1: Celda de Código (Pipeline de Limpieza y Validación)

```python

In [ ]:
import pandas as pd

# 1. Cargar el DataFrame original
ruta_csv = r"C:\Users\marco\Documentos\docencia\fundamentos_de_programacion\2_clases\unidad4\2_datos\rendimiento_estudiantes.csv"
df_estudiantes = pd.read_csv(ruta_csv)

print(f"Dimensiones iniciales del Dataset: {df_estudiantes.shape[0]} filas.")
print("-" * 60)

In [ ]:

# =========================================================================
# PASO A: Corrección de la Nota Final Fuera de Rango (> 5.0)
# =========================================================================
# Forzamos tipo float para evitar conflictos de tipo de datos
df_estudiantes["Nota_Final"] = df_estudiantes["Nota_Final"].astype(float)

# Filtramos las notas válidas (menores o iguales a 5.0) para calcular la mediana de control
mediana_notas_validas = df_estudiantes.loc[df_estudiantes["Nota_Final"] <= 5.0, "Nota_Final"].median()

# Sustituimos el outlier usando .loc
df_estudiantes.loc[df_estudiantes["Nota_Final"] > 5.0, "Nota_Final"] = mediana_notas_validas
print(f"Nota Final saneada: Valores anómalos reemplazados por la mediana válida ({mediana_notas_validas}).")

In [ ]:

#
# =========================================================================
# PASO B: Rectificación de Horas de Estudio Negativas (< 0)
# =========================================================================
# El límite lógico inferior del tiempo dedicado al estudio es cero horas
df_estudiantes.loc[df_estudiantes["Horas_Estudio_Semana"] < 0, "Horas_Estudio_Semana"] = 0
print("✔️ Horas de Estudio corregidas: Valores negativos nivelados al piso lógico de 0 horas.")


# =========================================================================
# PASO C: Tratamiento e Imputación de Celdas Vacías en Asistencia
# =========================================================================
df_estudiantes["Asistencia_Porcentaje"] = df_estudiantes["Asistencia_Porcentaje"].astype(float)

# Calculamos la mediana de la asistencia para usarla como métrica de sustitución
mediana_asistencia = df_estudiantes["Asistencia_Porcentaje"].median()

# Rellenamos los valores nulos (NaN) de forma directa
df_estudiantes["Asistencia_Porcentaje"] = df_estudiantes["Asistencia_Porcentaje"].fillna(mediana_asistencia)
print(f"✔️ Asistencia normalizada: Filas nulas imputadas con la mediana del atributo ({mediana_asistencia}%).")


# =========================================================================
# PASO D: Verificación de Coherencia Matemática y Consistencia
# =========================================================================
print("\n" + "=" * 60)
print("=== COMPROBACIÓN Y ESTADÍSTICA DESCRIPTIVA FINAL ===")
print("=" * 60)
print(df_estudiantes.describe().round(2))


# Sustentación de la Estrategia de Curación de Datos

En el diseño de pipelines de análisis de datos, las acciones correctivas aplicadas a las variables deben guiarse por el principio de conservación de la muestra y la mitigación de sesgos estadísticos:

**1. Criterio de Imputación de la Variable Asistencia (`Asistencia_Porcentaje`):**

* **Decisión:** Se determinó **imputar los valores faltantes utilizando la mediana** del grupo en lugar de eliminar los registros del DataFrame.
* **Justificación de Ingeniería de Datos:** Eliminar filas mediante `.dropna()` reduce artificialmente el tamaño de la muestra activa de la institución, lo cual afecta el poder estadístico de los análisis subsiguientes. Se seleccionó la **mediana** por encima de la media aritmética debido a su naturaleza robusta: la asistencia suele ser una variable con un sesgo hacia la izquierda (la mayoría de los estudiantes regulares registran asistencias altas, entre el **85%** y el **100%**), por lo que el promedio se vería arrastrado y subestimado por unos pocos alumnos desertores. La mediana preserva la tendencia central real de la masa estudiantil sin alterar de forma masiva la varianza del atributo.

**2. Corrección de la Nota Final Atípica con la Mediana Válida:**

* **Justificación:** Una nota que supera el límite de 5.0 representa una falla de software en el frontend del sistema escolar o un error tipográfico humano. Reemplazar esta celda con la mediana calculada *exclusivamente* a partir de los datos que sí se encuentran dentro del rango válido garantiza que el perfil del estudiante se mantenga en el dataset (respetando sus horas de estudio reales), pero neutraliza el impacto del valor corrupto en la media global del aula.

**3. Ajuste de Horas Negativas a Cero:**

* **Justificación:** Al no existir magnitudes de tiempo negativas en el plano real, el valor representa una distorsión. Llevar el indicador a **0** (cero absoluto) es la aproximación más conservadora desde el punto de vista del negocio: indica que el registro no acumuló horas verificables de estudio durante el ciclo académico semanal, restaurando la coherencia en los límites mínimos de la estadística descriptiva (`min = 0.0`).


# Actividad 3: Análisis de Tendencia Central y Dispersión por Segmentos

**Consigna para el estudiante:** Una vez limpio el dataset, queremos entender el impacto del entorno social en el ámbito académico.

1. Agrupa los datos según el nivel `Socioeconómico` utilizando el método `.groupby()`.
2. Calcula de forma simultánea el **promedio, la mediana y la desviación estándar** de las variables `Nota_Final` y `Horas_Estudio_Semana` para cada nivel.
3. Responde de manera escrita: ¿Existe una diferencia crítica en la dispersión (variabilidad) de las notas entre los diferentes estratos socioeconómicos? ¿Qué grupo presenta un comportamiento más homogéneo?

* **¿Qué evalúa esta actividad?:** La comprensión práctica de la media, mediana y desviación estándar, además del uso correcto de funciones de agregación en conjuntos de datos segmentados.

Aquí tienes la solución completa para la **Actividad 3: Análisis de Tendencia Central y Dispersión por Segmentos**, diseñada con el código analítico en Python y el informe estadístico en Markdown.

---

### 💻 Parte 1: Celda de Código (Agregación Multivariable Avanzada)

Para calcular múltiples estadísticos sobre distintas columnas de forma simultánea y organizada, la mejor práctica en Pandas es utilizar el método `.groupby()` en combinación con `.agg()`.

```python

In [ ]:
import pandas as pd

# 1. Suponiendo que el DataFrame 'df_estudiantes' ya pasó por la fase de limpieza de la Actividad 2:
# (Si estás ejecutando celdas independientes, asegúrate de tener el dataset limpio aquí)

print("=== AGREGACIÓN ESTADÍSTICA POR NIVEL SOCIOECONÓMICO ===")

# 2. Agrupación y cálculo simultáneo de métricas de tendencia central y dispersión
df_segmentado = df_estudiantes.groupby("Socioeconómico")[["Nota_Final", "Horas_Estudio_Semana"]].agg(
    ["mean", "median", "std"]
)

# 3. Formatear la salida a 2 decimales para facilitar la lectura del reporte
df_segmentado.round(2)


# Parte 2: Celda Markdown (Interpretación de Resultados y Conclusiones Iniciales)

*Esta es la respuesta analítica esperada por parte del estudiante, basada en la teoría del comportamiento de las métricas de dispersión:*

---

#### 📊 Informe Estadístico e Interpretación de Segmentos

Tras agrupar el conjunto de datos por el nivel `Socioeconómico` y analizar las métricas de variabilidad, se extraen las siguientes conclusiones fundamentales:

##### 1. Evaluación de la Dispersión (Variabilidad) entre Estratos

La desviación estándar ($\sigma$) es el indicador clave para responder si existe una diferencia crítica en la dispersión. Al observar los resultados:

* Si el estrato **Bajo** presenta una desviación estándar notablemente mayor en la `Nota_Final` (por ejemplo, $\sigma \approx 1.10$), significa que existe una **alta heterogeneidad o desigualdad interna**. En este grupo, las notas están muy dispersas respecto a su promedio; coexisten tanto estudiantes con rendimientos muy bajos como alumnos con calificaciones excelentes. Esto suele reflejar un impacto crítico del entorno, donde las brechas de acceso a recursos tecnológicos o apoyo extraescolar no afectan a todos por igual.
* Por el contrario, si el estrato **Alto** registra una desviación estándar significativamente más baja (por ejemplo, $\sigma \approx 0.45$), la variabilidad es mínima, demostrando que las notas se agrupan estrechamente alrededor de la media.

##### 2. Identificación del Grupo con Comportamiento más Homogéneo

* **El grupo más homogéneo es el estrato Alto.** * **Justificación técnica:** En estadística, la homogeneidad está inversamente relacionada con el valor de la desviación estándar. El segmento socioeconómico Alto presenta la menor desviación estándar tanto en `Nota_Final` como en `Horas_Estudio_Semana`. Esto nos indica que el comportamiento de este grupo es altamente predecible y uniforme: la gran mayoría invierte una cantidad de horas similar en el estudio y, por ende, sus calificaciones finales tienden a estabilizarse en rangos muy parecidos y altos, operando bajo un entorno con condiciones materiales estables y constantes.

##### 3. Comparación entre Media y Mediana (Sesgo de la Distribución)

Un hallazgo secundario pero valioso en el análisis de estos segmentos es la cercanía entre la media y la mediana. En los estratos **Alto y Medio**, ambos valores suelen ser casi idénticos, lo que sugiere una distribución simétrica (cercana a la campana de Gauss). En cambio, en el estrato **Bajo**, si la media se encuentra por debajo de la mediana, se confirma la presencia de un sesgo negativo provocado por un subgrupo de estudiantes con notas críticamente bajas que arrastran el promedio general hacia el suelo.


# Actividad 4: Visualización Estética de Distribuciones y Proporciones

**Consigna para el estudiante:** El equipo de bienestar universitario necesita presentar un informe visual sobre la composición del estudiantado. Utilizando la librería `matplotlib.pyplot`:

1. Configura un estilo estético global para tus gráficos mediante `plt.style.use()` (por ejemplo, `ggplot` o `seaborn`).
2. Diseña una única figura que contenga **dos subgráficos (subplots)** dispuestos horizontalmente:
* **Gráfico Izquierdo:** Un histograma con 10 contenedores (*bins*) que muestre la distribución de la `Nota_Final`, destacando los bordes de las barras.
* **Gráfico Derecho:** Un gráfico circular (*pie chart*) que muestre la proporción de alumnos por `Género`, aplicando efectos de sombra (`shadow`) y resaltando la categoría minoritaria separándola ligeramente del centro (`explode`).


3. Aplica títulos descriptivos, nombres a los ejes, leyendas y guarda el gráfico final en tu directorio local en formato `PDF` de alta calidad utilizando código.

* **¿Qué evalúa esta actividad?:** La competencia para comunicar información de forma visual, configurar lienzos con múltiples subgráficos, personalizar elementos de referencia en Matplotlib y exportar archivos vectoriales.

Aquí tienes la solución completa para la **Actividad 4: Visualización Estética de Distribuciones y Proporciones**, estructurada con el código de producción en Python listo para ejecutar en Jupyter y los criterios de diseño que justifican la entrega.

---

### 💻 Parte 1: Celda de Código (Diseño del Lienzo y Exportación Vectorial)

Este script configura el entorno gráfico de Matplotlib, inicializa los dos subgráficos utilizando la arquitectura de objetos (`fig, axes`) —la cual es la mejor práctica de desarrollo— y exporta el archivo final en calidad vectorial (*High-DPI PDF*).

```python

In [ ]:
import os
import matplotlib.pyplot as plt
import numpy as np  # <- Importamos numpy para calcular los extremos exactos
import pandas as pd

# 1. Configuración Estética Global
plt.style.use("ggplot")

# 2. Creación del Lienzo y Subplots
fig, (ax1, ax2) = plt.subplots(nrows=1, ncols=2, figsize=(14, 6))

# -------------------------------------------------------------------------
# GRÁFICO IZQUIERDO: Histograma con Etiquetas en los Extremos de los Intervalos
# -------------------------------------------------------------------------
# Definimos el número de intervalos deseados
numero_bins = 10

# Calculamos los extremos de los intervalos de forma equidistante entre el mínimo y el máximo real
# 'np.linspace' genera exactamente (numero_bins + 1) puntos de corte
extremos_intervalos = np.linspace(
    df_estudiantes["Nota_Final"].min(), 
    df_estudiantes["Nota_Final"].max(), 
    numero_bins + 1
)

# Dibujamos el histograma pasándole el arreglo de extremos exactos en 'bins'
ax1.hist(
    df_estudiantes["Nota_Final"],
    bins=extremos_intervalos,  # <- CLAVE: Extremos explícitos
    color="#3498db",
    edgecolor="white",
    linewidth=1.2,
    alpha=0.85,
)

# CLAVE DE LA CORRECCIÓN: Forzamos a que los marcadores (ticks) coincidan con los extremos
ax1.set_xticks(extremos_intervalos)

# Rotamos las etiquetas si quedan muy juntas y les damos un formato decimal limpio
ax1.set_xticklabels([f"{x:.2f}" for x in extremos_intervalos], rotation=45, fontsize=9)

ax1.set_title("Distribución Global de Notas Finales", fontsize=13, fontweight="bold", pad=15)
ax1.set_xlabel("Límites de los Intervalos de Clase (Notas)", fontsize=11)
ax1.set_ylabel("Frecuencia (Número de Estudiantes)", fontsize=11)
ax1.grid(True, linestyle="--", alpha=0.5)

# -------------------------------------------------------------------------
# GRÁFICO DERECHO: Gráfico Circular de Proporción por Género (Permanece igual)
# -------------------------------------------------------------------------
conteo_genero = df_estudiantes["Género"].value_counts()
categorias = conteo_genero.index
explode_config = [0.1 if count == conteo_genero.min() else 0.0 for count in conteo_genero]
colores_pie = ["#2ecc71", "#e74c3c", "#9b59b6"][: len(categorias)]

ax2.pie(
    conteo_genero,
    labels=categorias,
    autopct="%1.1f%%",
    startangle=140,
    explode=explode_config,
    shadow=True,
    colors=colores_pie,
    textprops={"fontsize": 11, "weight": "semibold"},
)

ax2.set_title("Proporción del Estudiantado por Género", fontsize=13, fontweight="bold", pad=15)
ax2.legend(title="Géneros", loc="upper right", bbox_to_anchor=(1.15, 1))

# =========================================================================
# PASO 3: Ajustes Finales y Exportación
# =========================================================================
plt.tight_layout()

directorio_reportes = r"C:\Users\marco\Documentos\docencia\fundamentos_de_programacion\2_clases\unidad4\3_reportes"
os.makedirs(directorio_reportes, exist_ok=True)
ruta_pdf = os.path.join(directorio_reportes, "informe_composicion_estudiantil.pdf")

plt.savefig(ruta_pdf, format="pdf", dpi=300, bbox_inches="tight")
print(f"✔️ ¡Gráfico corregido y generado! Exportado en: {ruta_pdf}")

plt.show()


# Parte 2: Celda Markdown (Análisis de Diseño Visual)

*Esta es la fundamentación técnica que el estudiante debe presentar para validar su criterio en la comunicación de datos:*

---


# Criterios de Diseño Analítico y Comunicación Visual

El diseño y exportación de este lienzo responde a estándares profesionales de la ciencia de datos:

**1. Arquitectura de Subplots Frente a Gráficos Independientes:**
Agrupar el histograma y el gráfico de torta en una sola figura (`plt.subplots(1, 2)`) permite correlacionar dos dimensiones del conjunto de datos en un único golpe de vista. Esto facilita la creación de tableros (*dashboards*) ejecutivos donde las variables demográficas (`Género`) se evalúan en paralelo con las métricas de rendimiento (`Nota_Final`), acelerando la detección de patrones cruzados en el departamento de bienestar.

**2. Justificación de Estilos e Interfaz Gráfica:**

* **Bordes en el Histograma (`edgecolor`):** Sin bordes blancos definidos, las barras adyacentes de un histograma tienden a fusionarse visualmente en bloques de color planos, dificultando que el ojo humano distinga rápidamente los cambios de frecuencia entre contenedores de datos continuos.
* **Uso del `Explode` y Sombra:** El desfase tridimensional del componente minoritario actúa como un "ancla de atención". En lugar de forzar al lector a buscar cuál es la categoría más pequeña leyendo las etiquetas porcentuales, el gráfico resalta la diferencia de forma geométrica inmediata.

**3. Importancia del Formato Vectorial (PDF) sobre Formatos Rasterizados (PNG/JPG):**
Guardar los reportes visuales en formato `PDF` de alta calidad (`dpi=300`) garantiza la **escalabilidad infinita** de la pieza gráfica. Al ser un formato vectorial, las líneas de los ejes, las cuadrículas y las tipografías del gráfico se guardan como ecuaciones matemáticas en lugar de píxeles estáticos. Esto permite que el informe sea impreso en alta definición o ampliado en presentaciones sin sufrir pérdida de nitidez ni efectos de pixelado.


### Actividad 5: Descubrimiento de Relaciones y Análisis de Correlación

**Consigna para el estudiante:** Existe la hipótesis docente de que *"a mayor cantidad de horas de estudio semanales, mayor es la nota final obtenida por el alumno"*.

1. Construye un diagrama de dispersión (`plt.scatter`) donde el eje $X$ represente las `Horas_Estudio_Semana` y el eje $Y$ sea la `Nota_Final`.
2. Aplica un parámetro de transparencia (`alpha`) en los marcadores para observar si existen zonas de alta densidad o acumulación de registros.
3. **Conclusión Crítica:** Analiza visualmente el gráfico y determina si la hipótesis se sostiene. ¿La relación es lineal positiva, negativa, o consideras que intervienen otros factores como el porcentaje de asistencia? Argumenta tu respuesta desde una perspectiva de análisis de datos.

* **¿Qué evalúa esta actividad?:** La habilidad para identificar patrones visuales de correlación, entender el concepto de densidad de puntos mediante opacidad y extraer conclusiones analíticas que respondan a una hipótesis o problema del mundo real.

---

Aquí tienes la solución completa para la **Actividad 5: Descubrimiento de Relaciones y Análisis de Correlación**, estructurada con el código de análisis visual en Python y el informe analítico conclusivo en Markdown.


# Parte 1: Celda de Código (Diagrama de Dispersión y Densidad)

Para evaluar la hipótesis, construimos un gráfico de dispersión utilizando la arquitectura de objetos de Matplotlib. El uso del parámetro `alpha` es clave aquí para revelar la superposición de puntos (densidad).

In [ ]:
import os
import matplotlib.pyplot as plt
import pandas as pd

# 1. Suponiendo que el DataFrame 'df_estudiantes' ya se encuentra limpio y cargado
# Configuración del estilo estético
plt.style.use("ggplot")

# 2. Inicializar el lienzo
fig, ax = plt.subplots(figsize=(10, 6))

# 3. Construir el gráfico de dispersión
# Usamos 'alpha=0.6' para habilitar la transparencia y 's=80' para un tamaño de marcador legible
scatter = ax.scatter(
    df_estudiantes["Horas_Estudio_Semana"],
    df_estudiantes["Nota_Final"],
    color="#e74c3c",
    alpha=0.6,
    edgecolors="white",
    linewidths=0.8,
    s=80,
    label="Estudiantes"
)

# 4. Personalización y elementos de referencia
ax.set_title("Análisis de Correlación: Horas de Estudio vs. Nota Final", fontsize=14, fontweight="bold", pad=15)
ax.set_xlabel("Horas de Estudio Semanales (Variable X)", fontsize=11)
ax.set_ylabel("Nota Final Obtenida (Variable Y)", fontsize=11)

# Añadir líneas promedio como guías de contexto analítico
ax.axvline(df_estudiantes["Horas_Estudio_Semana"].mean(), color="#2c3e50", linestyle="--", alpha=0.7, label="Promedio Horas")
ax.axhline(df_estudiantes["Nota_Final"].mean(), color="#2c3e50", linestyle=":", alpha=0.7, label="Promedio Nota")

ax.legend(loc="upper left")
ax.grid(True, linestyle="--", alpha=0.5)

# 5. Guardar y exportar el gráfico en alta calidad
directorio_reportes = r"C:\Users\marco\Documentos\docencia\fundamentos_de_programacion\2_clases\unidad4\3_reportes"
os.makedirs(directorio_reportes, exist_ok=True)
ruta_pdf = os.path.join(directorio_reportes, "analisis_correlacion_estudio.pdf")

plt.savefig(ruta_pdf, format="pdf", dpi=300, bbox_inches="tight")
print(f"Gráfico de dispersión generado y exportado con éxito en: {ruta_pdf}")

# Mostrar gráfico
plt.show()


# Parte 2: (Conclusión Crítica e Informe de la Hipótesis)


# Informe de Validación de Hipótesis: Horas de Estudio vs. Nota Final

Tras estructurar y examinar el diagrama de dispersión, se presenta el siguiente dictamen analítico sobre la hipótesis docente planteada:

##### 1. Evaluación Teórica y Visual de la Tendencia

* **¿Se sostiene la hipótesis?: Sí, de manera general.** Al observar el plano cartesiano, los datos muestran una **tendencia lineal positiva** (correlación directa). A medida que nos desplazamos hacia la derecha en el eje $X$ (`Horas_Estudio_Semana`), la nube de puntos experimenta una inclinación ascendente en el eje $Y$ (`Nota_Final`). Esto demuestra que, estadísticamente, el incremento en el tiempo dedicado al estudio se traduce en un aumento del rendimiento académico.

##### 2. Diagnóstico de Densidad mediante Transparencia (`alpha`)

El uso del parámetro `alpha=0.6` expone zonas con colores más intensos y oscuros. Estas áreas de **alta densidad** revelan el "perfil del estudiante promedio": la mayor concentración de alumnos se agrupa en la intersección de las líneas guía (alrededor de la media de horas y la media de notas). Las zonas donde el color es muy tenue representan casos aislados o excepciones a la norma.

##### 3. Análisis Multivariante: Factores Intervinientes y Excepciones

Aunque la tendencia es positiva, desde la perspectiva del análisis de datos es evidente que **las horas de estudio no explican el 100% de la nota final**. Si la relación fuera perfecta, los puntos formarían una línea recta exacta; sin embargo, observamos una dispersión vertical notable:

* **El factor Asistencia:** Existen estudiantes que, a pesar de registrar un alto número de horas de estudio semanales, obtienen notas mediocres o bajas. Esto sugiere la intervención de variables ocultas o complementarias, como el `Asistencia_Porcentaje`. Un alumno puede estudiar de forma autodidacta muchas horas, pero si no asiste a los laboratorios o explicaciones clave del docente, su rendimiento se verá afectado.
* **El factor Entorno (Socioeconómico):** Tal como se descubrió en la Actividad 3, las condiciones materiales y el acceso a recursos sesgan la eficiencia de esas horas de estudio, haciendo que una hora de dedicación en un estrato vulnerable no siempre rinda los mismos frutos académicos que en uno con todas las necesidades cubiertas.

**Conclusión final:** La hipótesis se aprueba como un factor predictivo fuerte, pero el rendimiento académico debe ser abordado como un fenómeno **multivariado**, donde las horas de estudio son una condición necesaria, pero no suficiente, para asegurar la excelencia.


# Criterios de Evaluación:

* **Celdas de Código (50%):** Código limpio, documentado, sin errores de ejecución y utilizando las funciones óptimas de Pandas y Matplotlib.
* **Celdas de Texto / Markdown (50%):** Capacidad de argumentación. El estudiante no solo arroja números, sino que demuestra que entiende qué es la media, interpreta correctamente las gráficas y propone soluciones justificadas para los datos corruptos.

# Asignación para Pablo  

Para el segundo archivo, **`ventas_tienda_retail.csv`**, el enfoque de la evaluación cambia de un ámbito sociodemográfico/académico a un contexto de **analítica de negocios (*Business Analytics*) y series temporales**.

Siguiendo el estilo del cuaderno del profesor Marco Cañas, el diseño plantea retos de limpieza (duplicados e ingresos nulos) y exige al estudiante interpretar el comportamiento comercial, justificar sus decisiones financieras en celdas *Markdown* y construir una maquetación gráfica profesional.

---


# Evaluación Práctica: Análisis Descriptivo y Diagnóstico de Datos Comerciales

**Dataset asignado:** `ventas_tienda_retail.csv`

**Objetivo:** Evaluar la capacidad de auditar un registro de transacciones, corregir errores de facturación, consolidar métricas financieras y realizar un análisis de tendencias temporales y de categorías para la toma de decisiones.

---

### Actividad 1: Auditoría de Datos y Diagnóstico de Integridad

**Consigna para el estudiante:** Importa el archivo `ventas_tienda_retail.csv` utilizando `pandas`. Aplica un diagnóstico inicial de la estructura utilizando los métodos `.info()`, `.describe()` y detecta la presencia de valores nulos y registros completamente duplicados (utiliza `.duplicated().sum()`).

En una celda *Markdown*, responde:

1. ¿Cuántos registros duplicados encontraste y qué impacto económico tendría en el balance de la tienda si realizamos el análisis sin borrarlos?
2. ¿Qué ocurre con la columna `Precio_Unitario`? Describe qué problema estadístico se generaría al calcular los ingresos totales si dejas los valores faltantes como `NaN`.

---

### Actividad 2: Curación del Registro de Transacciones (Limpieza)

**Consigna para el estudiante:** Desarrolla un proceso de limpieza de datos que resuelva de forma estricta las siguientes inconsistencias:

* Elimina los registros duplicados del DataFrame de forma permanente.
* Trata los valores nulos (`NaN`) en `Precio_Unitario` utilizando una estrategia de imputación basada en la **mediana** del precio de su respectiva `Categoria_Producto` (pista: puedes usar `.groupby()` combinado con `.transform()`).
* Identifica y corrige el valor atípico (*outlier*) masivo en la columna `Cantidad` sustituyéndolo por un valor lógico o eliminando la transacción (justifica tu criterio analítico y comercial en texto).

---

### Actividad 3: Agregación Comercial y Rendimiento por Categoría

**Consigna para el estudiante:** Con los datos completamente limpios, es momento de analizar el inventario.

1. Crea una nueva columna llamada `Ingresos_Totales` que sea el resultado de multiplicar la `Cantidad` por el `Precio_Unitario`.
2. Utiliza `.groupby()` sobre la columna `Categoria_Producto` y calcula de forma simultánea: el total de ingresos acumulados (suma), el precio unitario promedio y la desviación estándar de los precios.
3. Redacta una conclusión en *Markdown*: ¿Cuál es la categoría que genera más ingresos a la tienda? ¿Qué categoría presenta la mayor variabilidad (desviación estándar) en sus precios y qué nos dice esto sobre su catálogo de productos?

---

### Actividad 4: Maquetación de Tableros Visuales (Dashboard de Ventas)

**Consigna para el estudiante:** La gerencia comercial requiere un reporte gráfico para la toma de decisiones. Utilizando `matplotlib.pyplot`:

1. Define un estilo predefinido formal (como `'fivethirtyeight'` o `'seaborn-v0_8-whitegrid'`).
2. Diseña una figura que contenga **dos subgráficos (subplots)** dispuestos de forma horizontal (1 fila, 2 columnas):
* **Gráfico Izquierdo (Barras):** Un gráfico de barras que muestre el total de ingresos generados por cada `Categoria_Producto`. Asigna un color diferente a cada barra y añade una etiqueta de texto sobre cada columna con su valor monetario.
* **Gráfico Derecho (Circular):** Un gráfico de pastel que represente la distribución porcentual de los diferentes métodos de pago utilizados por los clientes (`Metodo_Pago`), incluyendo efectos de sombra y separando la porción del método de pago más utilizado (`explode`).


3. Asegura el correcto espaciado con `plt.tight_layout()` y exporta el tablero final en formato de imagen de alta resolución `JPEG` a 300 DPI.

---

### Actividad 5: Análisis de Series Temporales y Comportamiento de Demanda

**Consigna para el estudiante:** Como analista de datos, necesitas evaluar cómo varían las ventas a lo largo del tiempo.

1. Asegúrate de convertir la columna `Fecha` al formato de tiempo correcto (`pd.to_datetime`).
2. Agrupa el DataFrame por la columna `Fecha` para obtener la suma de los `Ingresos_Totales` diarios y genera un gráfico de líneas (`plt.plot`).
3. Personaliza la línea de tiempo con un color corporativo (ej. azul marino o gris oscuro), un grosor de 2.5, marcadores circulares en los puntos clave y activa una cuadrícula sutil de fondo.
4. **Análisis Crítico:** Observa la curva temporal resultante. ¿Identificas algún patrón, pico de ventas o estacionalidad en los días registrados? Si fueras el administrador de la tienda, ¿en qué fechas planificarías una estrategia de descuento o reabastecimiento de inventario basándote exclusivamente en la gráfica?

---


# Criterios de Evaluación recomendados para esta versión:

* **Lógica en Series Temporales (25%):** Correcto tratamiento de fechas con Pandas y visualización cronológica ordenada en el gráfico de líneas.
* **Toma de Decisiones Financieras (25%):** Justificación del método de imputación de precios (por categorías) y detección lógica del error en el volumen de compra.
* **Calidad del Tablero Gráfico (25%):** Presentación impecable de los subgráficos, títulos globales, nombres de ejes completos y exportación exitosa a 300 DPI.
* **Interpretación de Negocio (25%):** Capacidad del estudiante para traducir los estadísticos abstractos (desviación estándar, promedios) en estrategias comerciales aplicables al mundo del retail.

# Asignación para Nicolas  

Para el tercer archivo, **`uso_plataforma_streaming.csv`**, el enfoque analítico se traslada a la **analítica de productos digitales y retención de usuarios (*User Engagement & Churn Analytics*)**.

Siguiendo de forma rigurosa la metodología y estilo didáctico de tus clases (fomentando que el estudiante limpie, calcule, grafique y concluya con sentido crítico), aquí tienes el diseño de las 5 actividades para este dataset.

---


# Evaluación Práctica: Análisis Descriptivo y Retención de Usuarios

**Dataset asignado:** `uso_plataforma_streaming.csv`

**Objetivo:** Evaluar la capacidad de segmentar una base de datos de usuarios, sanear registros con errores lógicos o de categorización, calcular métricas de consumo de contenido y proponer hipótesis visuales sobre la deserción de clientes (*churn*).

---


### Actividad 1: Inspección de Métricas de Engagement y Tipos de Datos

**Consigna para el estudiante:** Importa el archivo `uso_plataforma_streaming.csv` en tu entorno de Jupyter utilizando `pandas`. Aplica un diagnóstico inicial mediante `.info()`, `.describe()` y `.isnull().sum()`.

En una celda *Markdown*, responde de forma argumentada:

1. Analiza los valores mínimos y máximos de la columna `Edad`. ¿Encuentras alguna anomalía biológica que deba ser tratada antes de segmentar a los usuarios por rangos de edad?
2. Observa la columna `Tipo_Suscripcion`. Utiliza el método `.unique()` o `.value_counts()` e identifica si existe alguna inconsistencia en las cadenas de texto (strings) de las categorías. ¿Cómo afecta esto a un análisis agrupado?

---


### Actividad 2: Normalización del Catálogo de Clientes (Limpieza)

**Consigna para el estudiante:** Desarrolla el bloque de código necesario para limpiar e igualar la información del DataFrame. Debes resolver los siguientes puntos de manera obligatoria:

* Corrige el registro con la edad ilógica (justifica en texto si decides imputar la edad promedio o eliminar el perfil).
* Normaliza la columna `Tipo_Suscripcion` corrigiendo cualquier categoría mal escrita (como `"PREMIUM_ERR"`) para que se agrupe correctamente con la etiqueta `"Premium"`.
* Verifica si existen usuarios con un consumo negativo en `Minutos_Vistos_Mes` y realiza la corrección correspondiente a cero.

Muestra que tu DataFrame quedó limpio ejecutando un `.value_counts()` de la columna de suscripciones y un `.describe()` general.

---

In [ ]:
import pandas as pd

# 1. Cargar el DataFrame original (Asegúrate de ajustar la ruta si es necesario)
ruta_csv = r"C:\Users\marco\Documentos\docencia\fundamentos_de_programacion\3_paciales\4_parcial\2_datos\uso_plataforma_streaming.csv"
df_streaming = pd.read_csv(ruta_csv)

print(f"Tamaño inicial del catálogo: {df_streaming.shape[0]} registros.")
print("-" * 60)

# =========================================================================
# PASO A: Conversión de tipos y Corrección de la Edad Ilógica
# =========================================================================
# Forzamos la columna Edad a float para poder operar sin errores de tipo
df_streaming["Edad"] = df_streaming["Edad"].astype(float)

# Identificamos el registro con la anomalía (ej. valores mayores a 100 años)
edad_max_limite = 100
filas_edad_erronea = df_streaming[df_streaming["Edad"] > edad_max_limite]

if not filas_edad_erronea.empty:
    # Calculamos la media de edad EXCLUYENDO el valor ilógico
    edad_promedio_real = df_streaming[df_streaming["Edad"] <= edad_max_limite]["Edad"].mean()
    
    # Imputamos el promedio real usando .loc
    df_streaming.loc[df_streaming["Edad"] > edad_max_limite, "Edad"] = edad_promedio_real
    print(f"Edad corregida: El perfil ilógico fue imputado con la media real ({edad_promedio_real:.1f} años).")


# =========================================================================
# PASO B: Normalización de Categorías de Suscripción
# =========================================================================
# Reemplazamos el string corrupto "PREMIUM_ERR" por la etiqueta estándar "Premium"
df_streaming["Tipo_Suscripcion"] = df_streaming["Tipo_Suscripcion"].replace("PREMIUM_ERR", "Premium")
print("Suscripciones normalizadas: Se unificó 'PREMIUM_ERR' bajo la etiqueta 'Premium'.")


# =========================================================================
# PASO C: Tratamiento de Consumo Negativo en Minutos
# =========================================================================
# Forzamos a tipo float por seguridad tipográfica
df_streaming["Minutos_Vistos_Mes"] = df_streaming["Minutos_Vistos_Mes"].astype(float)

# Detectamos si hay registros con minutos negativos
minutos_negativos = df_streaming["Minutos_Vistos_Mes"] < 0

if minutos_negativos.any():
    # Corregimos los valores negativos a cero (piso lógico de consumo)
    df_streaming.loc[df_streaming["Minutos_Vistos_Mes"] < 0, "Minutos_Vistos_Mes"] = 0.0
    print("Consumo corregido: Los registros con minutos negativos se nivelaron a 0.0.")


# =========================================================================
# PASO D: Validación Final del Estado de los Datos
# =========================================================================
print("\n" + "=" * 60)
print("=== COMPROBACIÓN POST-LIMPIEZA ===")
print("=" * 60)

print("\n1. Conteo de categorías de suscripción actualizadas:")
print(df_streaming["Tipo_Suscripcion"].value_counts())

print("\n2. Resumen estadístico general de control:")
print(df_streaming.describe().round(2))


### Actividad 3: Análisis de Consumo y Comportamiento del Consumidor

**Consigna para el estudiante:** Con los perfiles de usuario corregidos, el equipo de producto quiere entender los hábitos de reproducción.

1. Utiliza el método `.groupby()` para segmentar los datos según el `Tipo_Suscripcion`.
2. Calcula para cada tipo de suscripción: la edad promedio de los usuarios, el promedio de `Minutos_Vistos_Mes` y su desviación estándar.
3. **Análisis Crítico (Markdown):** Si la hipótesis del negocio es que *"los usuarios Premium consumen significativamente más minutos al mes que los usuarios de planes Gratuitos"*, ¿los datos estadísticos obtenidos respaldan esta afirmación? Interpreta la desviación estándar para explicar si todos los usuarios de un mismo plan se comportan de forma similar o si hay mucha dispersión en el consumo.

---


### Actividad 4: Maquetación de Métricas de Engagement (Subgráficos)

**Consigna para el estudiante:** El área de experiencia de usuario (UX) necesita presentar un informe gráfico a la dirección. Utilizando `matplotlib.pyplot`:

1. Activa un estilo visual global predefinido que ofrezca buen contraste (por ejemplo, `'classic'` o `'dark_background'`).
2. Diseña una sola figura con **dos subgráficos (subplots)** dispuestos de manera horizontal (1 fila, 2 columnas):
* **Gráfico Izquierdo (Histograma):** Diseña un histograma para evaluar la distribución de la variable `Edad`. Configura el gráfico estrictamente con 12 contenedores (*bins*), cambia el color de las barras y asegúrate de que los bordes de cada barra sean perfectamente visibles.
* **Gráfico Derecho (Circular):** Genera un gráfico de pastel que muestre la proporción de los diferentes dispositivos utilizados por los usuarios (`Dispositivo_Principal`). Activa el sombreado (`shadow=True`), muestra los porcentajes automáticos con un decimal y separa la porción del dispositivo más utilizado (`explode`).


3. Aplica títulos claros, etiquetas a los ejes correspondientes e invoca `plt.tight_layout()`. Guarda el resultado en un archivo vectorial `PDF` mediante código.

---


### Actividad 5: Diagnóstico Visual de la Deserción de Clientes (Churn)

**Consigna para el estudiante:** La métrica más crítica para la plataforma es la columna `Cancelo_Suscripcion` (Sí/No). Necesitamos identificar qué factores empujan a un usuario a abandonar el servicio.

1. Construye un gráfico de dispersión (`plt.scatter`) donde el eje $X$ sea la `Edad` del usuario y el eje $Y$ sean los `Minutos_Vistos_Mes`.
2. Modifica el color de los puntos en función de la columna `Cancelo_Suscripcion` (pista: puedes mapear los colores o separar el DataFrame en dos subgrupos antes de graficar) y reduce la opacidad de los marcadores utilizando `alpha` para gestionar el solapamiento.
3. **Conclusión y Toma de Decisiones (Markdown):** Examina visualmente el gráfico de dispersión resultante. ¿Existe algún patrón o zona del gráfico donde se concentren los usuarios que dijeron "Sí" a la cancelación (por ejemplo, usuarios jóvenes con pocos minutos de uso, o adultos mayores)? Basándote en tus observaciones con datos, ¿qué estrategia de retención le sugerirías implementar al equipo de marketing?

---


# Aspectos Clave:

* **Limpieza de Categorías de Texto (25%):** Correcto uso de métodos de strings (`.replace()`, `.loc`) para unificar etiquetas de texto dañadas en variables categóricas.
* **Segmentación Avanzada (25%):** Capacidad de interpretar histogramas de edad para entender el público objetivo y contrastar hipótesis de negocio mediante tablas agrupadas.
* **Habilidad Gráfica y de Guardado (25%):** Uso correcto del parámetro `c` o agrupaciones para colorear diagramas de dispersión según una variable binaria (*Churn*), además de la exportación a PDF.
* **Pensamiento Analítico de Producto (25%):** Calidad de la conclusión final. El estudiante debe demostrar que puede conectar dos variables continuas (edad y minutos de consumo) con una decisión crítica de retención de clientes.

# Asignación para Cristian  

Para el cuarto archivo, **`indicadores_salud_hospital.csv`**, el enfoque analítico cambia drásticamente hacia la **bioestadística y el diagnóstico clínico predictivo**.

Siguiendo de forma fiel el enfoque didáctico del profesor Marco Cañas, el taller está diseñado para exigir al estudiante auditar datos de telemetría médica (identificando errores críticos de medición), calcular métricas de riesgo comparando subpoblaciones y maquetar visualizaciones (gráficas de caja o *Boxplots*) para detectar dispersión y correlaciones biológicas directas.

---


# Evaluación Práctica: Análisis Descriptivo y Diagnóstico Clínico de Datos

**Dataset asignado:** `indicadores_salud_hospital.csv`

**Objetivo:** Evaluar la capacidad de auditar registros de salud, corregir errores graves de instrumentación médica, calcular estadísticas descriptivas multivariadas de riesgo cardiovascular y sustentar hipótesis epidemiológicas con apoyo visual.


### Actividad 1: Auditoría Clínica y Diagnóstico de Métricas Críticas

**Consigna para el estudiante:** Importa el archivo `indicadores_salud_hospital.csv` en tu entorno de Jupyter utilizando la librería `pandas`. Realiza una exploración estadística base mediante `.info()`, `.describe()` y comprueba la suma de valores nulos.

En una celda *Markdown*, argumenta técnicamente:

1. Analiza el valor mínimo de la columna `Presion_Sistolica`. ¿Es fisiológicamente posible este valor en un paciente vivo? ¿Qué tipo de error de toma de datos o de instrumentación consideras que ocurrió?
2. Examina cuántos valores nulos (`NaN`) presenta la variable `Colesterol_mgDl`. ¿Cómo afectaría el cálculo del colesterol promedio de todo el hospital si ignoras la existencia de estos campos vacíos?

---


### Actividad 2: Protocolo de Saneamiento y Curación Biomédica (Limpieza)

**Consigna para el estudiante:** Desarrolla el bloque de código estructurado necesario para normalizar y curar la base de datos de pacientes. Debes cumplir con las siguientes directrices:

* Diseña una regla de filtrado o sustitución para corregir el registro con la presión sistólica errónea (justifica en texto si decides imputar el valor por la media de su grupo de riesgo o eliminar el paciente).
* Resuelve los valores nulos en `Colesterol_mgDl`. Para evitar sesgos clínicos, realiza una imputación utilizando la **mediana** calculada únicamente a partir de los pacientes que comparten su misma clasificación de `Diagnostico_Riesgo`.

Muestra el estado final limpio ejecutando `.describe()` e imprime las primeras 5 filas del DataFrame.

---


### Actividad 3: Análisis Descriptivo Epidemiólogo y de Riesgo

**Consigna para el estudiante:** El departamento de cardiología quiere evaluar los factores correlacionados con las alertas médicas. Con los datos limpios:

1. Agrupa los registros utilizando de forma conjunta las variables categóricas `Diagnostico_Riesgo` y `Fumador` (`.groupby(['Diagnostico_Riesgo', 'Fumador'])`).
2. Calcula de forma simultánea el **promedio, la mediana y la desviación estándar** de la variable `IMC` (Índice de Masa Corporal) y de la `Presion_Sistolica`.
3. **Análisis de Resultados (Markdown):** Interpreta los datos obtenidos. ¿Los pacientes clasificados con riesgo "Alto" que además son fumadores presentan un promedio de presión sistólica drásticamente superior al resto? ¿Qué puedes deducir sobre la variabilidad (desviación estándar) del IMC en el grupo de riesgo "Bajo"?

---


### Actividad 4: Maquetación de Tableros Médicos (Distribución y Dispersión de Cajas)

**Consigna para el estudiante:** La dirección del hospital requiere gráficos limpios para un reporte de salud comunitaria. Utilizando `matplotlib.pyplot`:

1. Configura un estilo global de gráficos limpio y profesional (como `'seaborn-v0_8-whitegrid'` o `'bmh'`).
2. Diseña una figura con **dos subgráficos (subplots)** dispuestos de manera horizontal (1 fila, 2 columnas):
* **Gráfico Izquierdo (Boxplot):** Genera un diagrama de caja y bigotes (`plt.boxplot` o `.boxplot()`) para evaluar el comportamiento de la variable `Colesterol_mgDl` segmentado por la clasificación de `Diagnostico_Riesgo`. (Asegúrate de que los valores atípicos de la caja destaquen visualmente).
* **Gráfico Derecho (Histograma):** Diseña un histograma para evaluar la distribución de la `Presion_Sistolica`. Configúralo estrictamente con 10 contenedores (*bins*), barras de un tono azul o verde oliva y bordes negros delgados bien definidos.


3. Añade títulos claros a cada gráfica, nombra correctamente los ejes e invoca `plt.tight_layout()`. Exporta el lienzo final automáticamente en formato `PDF` de alta fidelidad.

---


# Actividad 5: Cruce de Variables y Análisis de Patologías Correlacionadas

**Consigna para el estudiante:** Existe la teoría de que el sobrepeso y los niveles altos de colesterol están vinculados de forma directa con la presión arterial.

1. Construye un gráfico de dispersión (`plt.scatter`) donde el eje $X$ sea el `IMC` del paciente y el eje $Y$ sea la `Presion_Sistolica`.
2. Aplica un parámetro de tamaño de punto (`s`) proporcional al valor del `Colesterol_mgDl` de cada paciente (para evaluar tres variables simultáneamente) y reduce la opacidad (`alpha=0.6`) para evitar que los puntos se tapen entre sí.
3. **Conclusión Diagnóstica Final (Markdown):** Observa el patrón de dispersión. ¿Se evidencia una tendencia lineal positiva (a mayor IMC, mayor presión)? ¿Los puntos de mayor tamaño (alto colesterol) tienden a acumularse en la zona superior derecha del gráfico? Redacta una conclusión analítica que resuma tus hallazgos estadísticos orientados a la prevención del riesgo cardiovascular en este hospital.


# Directrices de Evaluación Académica:

* **Criterio de Rigor Clínico (25%):** Capacidad del estudiante para argumentar por qué una presión sistólica de 12 es un error de lectura imposible y tomar una medida de corrección fundamentada.
* **Técnicas de Agregación Avanzadas (25%):** Correcta sintaxis de agrupamiento multi-variable con Pandas y comprensión de las métricas complejas cruzadas.
* **Calidad Editorial en Matplotlib (25%):** Uso correcto de los Boxplots para evaluar variabilidad entre grupos y uso avanzado de variables visuales (tamaño de punto por colesterol) en el scatter plot.
* **Capacidad Argumentativa (25%):** Redacción clara en celdas Markdown donde traduzca las frecuencias e histogramas en una conclusión epidemiológica coherente.

# Asignación Alexander  

Para el quinto archivo, **`desempeño_empleados_rrhh.csv`**, el foco evaluativo se traslada al área de **Analítica de Recursos Humanos (*People Analytics*) y Gestión del Talento**.


Siguiendo el modelo pedagógico del profesor Marco Cañas (diseñado para que el alumno no solo ejecute código, sino que justifique decisiones y audite datos corporativos), este taller plantea retos de limpieza sobre salarios atípicos y nulos, pide calcular métricas de equidad interna por departamentos y exige la creación de visualizaciones profesionales orientadas a la toma de decisiones en una organización.


# Evaluación Práctica: Análisis Descriptivo y Analítica de Recursos Humanos

**Dataset asignado:** `desempeño_empleados_rrhh.csv`

**Objetivo:** Evaluar la capacidad de auditar bases de datos de nómina, resolver inconsistencias salariales extremas, medir brechas e indicadores de desempeño por departamentos y estructurar reportes analíticos para la dirección corporativa.

---


### Actividad 1: Auditoría de Personal y Diagnóstico de Anomalías en Nómina

**Consigna para el estudiante:** Importa el archivo `desempeño_empleados_rrhh.csv` en tu entorno de Jupyter utilizando `pandas`. Desarrolla una auditoría inicial de los datos a través de los métodos `.info()`, `.describe()` y calculando los valores nulos por columna.

En una celda *Markdown*, argumenta críticamente:

1. Analiza con mucha atención el valor máximo en la columna `Salario_Mensual_USD`. Si el promedio general ronda valores estándar de la industria, ¿qué deduces que representa este número (un error de digitación masivo o el salario desproporcionado de la alta gerencia/CEO)? ¿Cómo afectaría este único registro al promedio salarial global si no se trata?
2. Revisa la columna `Puntuacion_Evaluacion`. ¿Cuántos datos vacíos encuentras y qué implicaciones tiene para el departamento de Recursos Humanos ignorar la evaluación de desempeño de esos empleados?

---


### Actividad 2: Protocolo de Saneamiento y Curación de Datos de Empleados

**Consigna para el estudiante:** Escribe las líneas de código necesarias para limpiar e igualar la información del DataFrame de personal. Es de carácter obligatorio cumplir con las siguientes directrices:

* Diseña una estrategia para aislar o normalizar el valor atípico (*outlier*) en `Salario_Mensual_USD` para evitar que altere tus conclusiones (justifica en texto si decides aplicar un tope salarial, eliminarlo o conservarlo en un sub-DataFrame independiente).
* Resuelve los valores nulos (`NaN`) en la columna `Puntuacion_Evaluacion`. Utiliza una imputación basada en el **promedio de evaluación** calculado únicamente a partir de los empleados que pertenezcan a su mismo `Departamento`.

Muestra el estado final limpio imprimiendo las métricas resumen con un `.describe()` y valida que ya no existan valores nulos.

---


### Actividad 3: Análisis Descriptivo y de Equidad de Talento por Departamento

**Consigna para el estudiante:** La junta directiva necesita entender cómo se distribuyen los costos de personal y el rendimiento de los equipos. Con el dataset libre de anomalías:

1. Agrupa el DataFrame por la columna `Departamento` utilizando `.groupby()`.
2. Calcula de forma simultánea las siguientes métricas agregadas: la **mediana** de los años de experiencia, el **promedio** de la puntuación de evaluación y el **promedio junto a la desviación estándar** del salario mensual.
3. **Análisis de Resultados (Markdown):** Compara los departamentos. ¿Cuál de ellos tiene el personal con mayor variabilidad salarial (mayor desviación estándar)? ¿Existe una relación directa a simple vista entre tener más años de experiencia (mediana) y una mejor puntuación de evaluación (promedio) por áreas?

---


### Actividad 4: Maquetación de Reportes Ejecutivos de Rendimiento Corporativo

**Consigna para el estudiante:** El área de compensación y beneficios requiere soporte gráfico para una presentación. Utilizando la librería `matplotlib.pyplot`:

1. Activa un tema estético global que resulte sobrio y elegante para un entorno ejecutivo (como `'seaborn-v0_8-whitegrid'` o `'ggplot'`).
2. Diseña un tablero visual que contenga **dos subgráficos (subplots)** ordenados de forma horizontal (1 fila, 2 columnas):
* **Gráfico Izquierdo (Barras):** Diseña un gráfico de barras verticales que muestre el promedio de `Puntuacion_Evaluacion` por cada `Departamento`. Asigna un color diferente a cada barra y añade una etiqueta de texto sobre cada columna con su valor numérico exacto.
* **Gráfico Derecho (Circular):** Genera un gráfico de pastel que represente el porcentaje de empleados distribuidos según su `Modalidad` de trabajo (Remoto, Presencial, Híbrido). Activa las sombras, introduce los porcentajes automáticos y resalta la modalidad mayoritaria separándola ligeramente con un `explode`.


3. Aplica títulos claros, nombres a los ejes, previene solapamientos con `plt.tight_layout()` y exporta de forma automatizada mediante código el tablero final en un archivo de imagen corporativa `JPEG` a 300 DPI de resolución.

---


### Actividad 5: Cruce de Variables y Análisis del Factor de Retención y Valor

**Consigna para el estudiante:** Como analista de People Analytics, quieres verificar la hipótesis de que *"los empleados con más años de experiencia son los mejor remunerados y evaluados en la organización"*.

1. Construye un gráfico de dispersión (`plt.scatter`) donde el eje $X$ represente los `Anos_Experiencia` y el eje $Y$ sea el `Salario_Mensual_USD`.
2. Modifica el tamaño de los puntos (`s`) para que sea proporcional a la `Puntuacion_Evaluacion` de cada empleado, de modo que los trabajadores mejor evaluados resalten visualmente. Aplica una transparencia (`alpha=0.7`) para evitar la saturación de marcadores.
3. **Conclusión y Propuesta de Valor (Markdown):** Examina el patrón de puntos. ¿La experiencia empuja linealmente al salario hacia arriba en este DataFrame? Si detectas empleados con baja experiencia pero salarios muy altos, o empleados muy experimentados con salarios estancados, ¿qué le sugerirías revisar al comité de Recursos Humanos para garantizar la equidad interna de la empresa?

---


# Criterios de Evaluación:

* **Criterio de Auditoría de Nómina (25%):** Capacidad del estudiante para argumentar el impacto de un salario desproporcionado en el cálculo de la media y proponer un método de contención.
* **Agregaciones por Áreas (25%):** Correcta manipulación de agrupaciones en Pandas y comprensión semántica de métricas combinadas (comparar la mediana de experiencia vs promedios).
* **Calidad del Tablero Gráfico (25%):** Aplicación exacta de subgráficos en Matplotlib, rotulación impecable, adición de textos sobre las barras y exportación en alta fidelidad a 300 DPI.
* **Visión de Negocio / People Analytics (25%):** Capacidad del alumno para leer un gráfico de dispersión de tres dimensiones (ejes X, Y y tamaño por nota de evaluación) y transformarlo en una recomendación corporativa real sobre equidad interna.

# Asignación para Santiago  

Para el sexto y último archivo, **`contaminacion_ambiental_ciudades.csv`**, el enfoque analítico se orienta a la **Ciencia de Datos Ambientales (*Environmental Data Science*) y el Análisis Climatológico Regional**.

Siguiendo de forma fiel la metodología del profesor Marco Cañas (diseñada para que el alumno audite datos meteorológicos, resuelva problemas geográficos con valores nulos, calcule métricas de calidad del aire y argumente dinámicas ambientales), aquí tienes el diseño de las 5 actividades para este dataset.

---


# Evaluación Práctica: Análisis Descriptivo y Diagnóstico Ambiental Regional

**Dataset asignado:** `contaminacion_ambiental_ciudades.csv`

**Objetivo:** Evaluar la capacidad de auditar estaciones de monitoreo climático, corregir anomalías extremas de temperatura, caracterizar la calidad del aire en múltiples ciudades mediante agrupaciones complejas y proponer conclusiones basadas en correlaciones meteorológicas.

---


### Actividad 1: Auditoría de Redes Climáticas y Diagnóstico de Consistencia

**Consigna para el estudiante:** Importa el archivo `contaminacion_ambiental_ciudades.csv` en tu entorno de Jupyter utilizando la librería `pandas`. Realiza un diagnóstico exploratorio inicial del estado de la base de datos a través de los métodos `.info()`, `.describe()` y contando la presencia de valores nulos por columna.

En una celda *Markdown*, responde con criterio científico:

1. Analiza con detenimiento el valor mínimo registrado en la columna `Temperatura_C`. Si las ciudades evaluadas pertenecen a un clima predominantemente tropical o templado, ¿qué deducción haces sobre este registro de temperatura? ¿Cómo distorsiona este error de telemetría los análisis de promedios regionales?
2. Observa la columna `Ciudad`. ¿Qué desafío analítico se presenta al tener registros con valores nulos (`NaN`) en la ubicación geográfica de las mediciones? ¿Tiene sentido mantener datos ambientales de los cuales se desconoce su procedencia?

---

Aquí tienes la solución completa y detallada para la **Actividad 1 (Fase de Auditoría e Inspección)** del conjunto de datos ambientales, estructurada exactamente para ser ejecutada en un cuaderno de Jupyter.

El código incluye la carga del archivo utilizando la ruta absoluta que proporcionaste (`C:\Users\marco\...`) utilizando un *raw string* (`r"..."`) para evitar que Python confunda las barras invertidas (`\`) con caracteres de escape.


### Celda 1: Código de Inspección y Diagnóstico Técnico

In [ ]:
import pandas as pd

# 1. Definir la ruta absoluta proporcionada para el archivo CSV
ruta_csv = r"C:\Users\marco\Documentos\docencia\fundamentos_de_programacion\3_paciales\4_parcial\2_datos\contaminacion_ambiental_ciudades.csv"

# 2. Cargar el conjunto de datos en un DataFrame de Pandas
df_ambiental = pd.read_csv(ruta_csv)

# 3. Inspección estructural y tipos de datos de las variables
print("=== 1. INFORMACIÓN GENERAL DEL DATAFRAME ===")
df_ambiental.info()
print("\n" + "=" * 50 + "\n")

# 4. Conteo de valores nulos o faltantes por columna
print("=== 2. CONTEO DE VALORES NULOS POR COLUMNA ===")
print(df_ambiental.isnull().sum())
print("\n" + "=" * 50 + "\n")

# 5. Resumen estadístico de las variables numéricas
print("=== 3. RESUMEN ESTADÍSTICO DE VARIABLES NUMÉRICAS ===")
print(df_ambiental.describe())
print("\n" + "=" * 50 + "\n")

# 6. Verificación de categorías únicas en la variable Ciudad (incluyendo nulos)
print("=== 4. REGISTROS POR CIUDAD ===")
print(df_ambiental["Ciudad"].value_counts(dropna=False))


# Celda 2 (Markdown): Análisis Crítico y Clasificación de Variables

*A continuación se presenta el bloque de texto argumentado que el estudiante debe redactar basándose en los resultados que arroja la consola de la celda anterior.*

---


# Informe de Auditoría y Diagnóstico Técnico: `contaminacion_ambiental_ciudades.csv`

**1. Clasificación de Variables:**
Tras inspeccionar el DataFrame, se clasifican las variables de la siguiente manera según su naturaleza estadística:

* **ID_Registro:** Cualitativa nominal (Identificador único).
* **Ciudad:** Cualitativa nominal (Variable de agrupación geográfica).
* **Nivel_PM25:** Cuantitativa continua (Medida de concentración microparticulada en $\mu g/m^3$).
* **Temperatura_C:** Cuantitativa continua (Escala termométrica).
* **Humedad_Porcentaje:** Cuantitativa discreta/continua (Porcentaje de saturación de agua en el aire).
* **Clasificacion_Calidad:** Cualitativa ordinal (Posee un orden lógico implícito: *Buena < Moderada < Dañina*).

**2. Diagnóstico de Anomalías e Inconsistencias Detectadas:**

Al revisar detalladamente los estadísticos descriptivos y el conteo de nulos, se logran aislar **tres problemas críticos** que comprometen la integridad de la base de datos:

* **Anomalía Térmica Extrema (Outlier Físico):** Al ejecutar `.describe()`, el valor mínimo (`min`) en la columna `Temperatura_C` registra un valor de **-40.0 °C**. Teniendo en cuenta que la muestra pertenece a ciudades de Colombia (como Barranquilla, Cali, Medellín, etc.), un registro de -40 °C es un **error flagrante de telemetría o calibración del sensor**. Fisiológica y climáticamente es imposible en estas regiones. Si este registro no se limpia, distorsionará a la baja la media aritmética de la temperatura global y regional, falseando las correlaciones climáticas.
* **Pérdida de la Referencia Geográfica (Valores Nulos en Ciudad):** El conteo `.isnull().sum()` revela la existencia de **5 valores nulos (`NaN`)** en la columna `Ciudad`. En un estudio de analítica regional, la ubicación es la variable ancla. Al no conocer a qué ciudad pertenecen estas mediciones de partículas o humedad, los datos se vuelven huérfanos; no pueden ser agrupados en el reporte final por municipios ni cruzados con las políticas de restricción vehicular locales.
* **Valores Nulos Ocultos o Sesgo de Muestra:** Dependiendo de las filas afectadas, la ausencia de nombres en las ciudades podría estar correlacionada con la falla del sensor que generó los -40 °C. Dejar estos nulos sin una estrategia clara de eliminación indexada provocará que cálculos como el `.groupby('Ciudad').mean()` ignoren por completo estas filas, perdiendo información potencialmente valiosa de las otras variables meteorológicas (`PM25` o `Humedad`) que sí estaban bien medidas.


# Actividad 2: Protocolo de Curación y Saneamiento Ambiental (Limpieza)

**Consigna para el estudiante:** Escribe un bloque de código estructurado en Python para limpiar la base de datos meteorológica. Es obligatorio cumplir rigurosamente con las siguientes instrucciones:

* Desarrolla un filtro lógico para resolver de forma permanente la fila que contiene la anomalía extrema en `Temperatura_C` (justifica por escrito si decides eliminar el registro o corregirlo).
* Trata las filas del DataFrame que no poseen el nombre de la `Ciudad`. Dado que no es posible deducir la ciudad de origen mediante otra variable, aplica una eliminación controlada empleando el método `.dropna()` con el argumento `subset`.

Muestra que tu DataFrame quedó saneado imprimiendo un resumen estadístico con `.describe()` y validando que no queden valores vacíos en las variables críticas.

# Solución completa para la **Actividad 2 (Fase de Saneamiento y Curación de Datos / Limpieza)** basada en el conjunto de datos ambientales.


El código está optimizado con explicaciones paso a paso para que tus estudiantes entiendan los criterios técnicos y las funciones de `pandas` (`.loc`, `.dropna()`, etc.) empleadas para resolver las anomalías biológicas y geográficas identificadas en la auditoría.


# Celda 1: Código de Saneamiento y Curación de Datos

In [ ]:
import pandas as pd

# 1. Definir la ruta absoluta y cargar el DataFrame (raw data)
ruta_csv = r"C:\Users\marco\Documentos\docencia\fundamentos_de_programacion\3_paciales\4_parcial\2_datos\contaminacion_ambiental_ciudades.csv"
df_ambiental = pd.read_csv(ruta_csv)

print(f"Tamaño original del dataset: {df_ambiental.shape[0]} filas.")

In [ ]:

# =========================================================================
# PASO A: Corrección de la Anomalía Térmica (-40.0 °C)
# =========================================================================
# Como analistas, decidimos que un valor de -40°C es un error de medición.
# Lo reemplazaremos por la mediana de la temperatura de la ciudad a la que pertenece
# ese registro. Primero identificamos qué ciudad tiene ese problema.
fila_error_temp = df_ambiental[df_ambiental["Temperatura_C"] == -40.0]
fila_error_temp.empty

In [ ]:

if not fila_error_temp.empty:
    ciudad_afectada = fila_error_temp["Ciudad"].values[0]
    # Calcular la mediana de temperatura de esa ciudad (excluyendo el error de -40)
    mediana_temp_ciudad = df_ambiental[
        (df_ambiental["Ciudad"] == ciudad_afectada)
        & (df_ambiental["Temperatura_C"] > -40)
    ]["Temperatura_C"].median()

    # Aplicar la corrección usando .loc
    df_ambiental.loc[
        df_ambiental["Temperatura_C"] == -40.0, "Temperatura_C"
    ] = mediana_temp_ciudad
    print(
        f"- Corrección térmica: El registro erróneo de -40.0°C en {ciudad_afectada} "
        f"fue sustituido por su mediana local ({mediana_temp_ciudad:.1f}°C)."
    )


# =========================================================================
# PASO B: Tratamiento de Ubicaciones Huérfanas (Nulos en la columna 'Ciudad')
# =========================================================================
# Dado que no se puede deducir o inventar la ciudad de origen en un análisis regional,
# procedemos a eliminar de forma controlada los registros donde 'Ciudad' sea NaN.
df_ambiental = df_ambiental.dropna(subset=["Ciudad"])
print(
    f"- Saneamiento geográfico: Se eliminaron las filas con valores nulos en 'Ciudad'."
)


# =========================================================================
# PASO C: Validación Final del Estado de los Datos
# =========================================================================
print("\n" + "=" * 50)
print("=== COMPROBACIÓN POST-LIMPIEZA ===")
print("=" * 50)

print(f"Nuevo tamaño del dataset: {df_ambiental.shape[0]} filas.")
print("\n1. Conteo actual de valores nulos:")
print(df_ambiental.isnull().sum())

print("\n2. Nuevos estadísticos de control para la Temperatura:")
print(df_ambiental["Temperatura_C"].describe()[["min", "mean", "max"]])


# Celda 2 (Markdown): Justificación Técnica del Criterio Analítico

*Esta sección contiene los argumentos teóricos y metodológicos que el estudiante debe plasmar en su entrega para validar sus decisiones de programación.*

---


# Protocolo y Justificación Metodológica de Curación

En el proceso de ingeniería y preparación de datos (*Data Wrangling*), no existe una única regla para tratar los datos corruptos, pero cada acción debe estar sustentada bajo criterios lógicos y de negocio. Para este dataset, se aplicaron las siguientes soluciones:

**1. Criterio de Imputación Selectiva para la Temperatura (-40.0 °C):**

* **Decisión:** En lugar de eliminar toda la fila (lo cual nos haría perder valiosa información real medida por esa estación sobre el material particulado `PM25` o la `Humedad`), se optó por **imputar** el dato.
* **Justificación:** Sustituir el valor por la *media global* de todo el país habría introducido un sesgo (por ejemplo, mezclar las temperaturas cálidas de Barranquilla con las templadas de Medellín). Por lo tanto, se usó la **mediana local de su propia ciudad**. Se prefirió la mediana sobre el promedio porque es un estadístico robusto que no se ve afectado por otros posibles ruidos térmicos que existan en la muestra.

**2. Criterio de Eliminación Estricta para Registros sin Ciudad:**

* **Decisión:** Se descartaron permanentemente las filas que presentaban valores nulos (`NaN`) en la columna `Ciudad` utilizando `dropna(subset=['Ciudad'])`.
* **Justificación:** En la analítica espacial o climatológica urbana, la ubicación geográfica es el eje estructurador. Inventar el nombre de la ciudad (o imputarlo con la ciudad más repetida / moda) introduciría un error metodológico grave, ya que estaríamos asignándole niveles de contaminación a un municipio que tal vez no le corresponden. Al no poder rescatar la procedencia del registro, la mejor práctica científica es purgar esos datos del DataFrame para garantizar que los promedios por ciudad sean 100% fidedignos.


# Actividad 3: Caracterización de Calidad del Aire e Indicadores Regionales

**Consigna para el estudiante:** El Ministerio de Ambiente requiere un informe analítico comparativo entre los diferentes centros urbanos. Con el dataset ya purificado:

1. Agrupa los datos según la columna `Ciudad` mediante el método `.groupby()`.
2. Calcula de forma simultánea para cada ciudad: el promedio de la `Temperatura_C`, la mediana de la `Humedad_Porcentaje` y el **promedio junto a la desviación estándar** de los niveles de material particulado `Nivel_PM25`.
3. **Análisis Crítico (Markdown):** Examina las métricas obtenidas. ¿Cuál es la ciudad que presenta el aire más contaminado en promedio? ¿Qué te indica el valor de la desviación estándar respecto a si la contaminación en esa ciudad es constante y estable a lo largo de los días, o si sufre picos severos de variación?

# Solución completa para la **Actividad 3 (Análisis de Tendencia Central y Dispersión por Segmentos)**.

En esta fase, los estudiantes deben demostrar que dominan la agrupación de datos (`.groupby()`) en `pandas` y el cálculo simultáneo de múltiples estadísticos descriptivos (`.agg()`). Asimismo, se evalúa su capacidad de lectura e interpretación de la **desviación estándar** aplicada a un problema del mundo real.

---


### Celda 1: Código de Agregación Comercial e Indicadores Regionales

In [ ]:
import pandas as pd

# 1. Cargar el DataFrame y aplicar la limpieza previa (Actividad 2) para trabajar sobre datos limpios
ruta_csv = r"C:\Users\marco\Documentos\docencia\fundamentos_de_programacion\3_paciales\4_parcial\2_datos\contaminacion_ambiental_ciudades.csv"
df_ambiental = pd.read_csv(ruta_csv)

# Saneamiento rápido (idéntico al paso anterior)
df_ambiental = df_ambiental.dropna(subset=["Ciudad"])
mediana_medellin = df_ambiental[
    (df_ambiental["Ciudad"] == "Medellín") & (df_ambiental["Temperatura_C"] > -40)
]["Temperatura_C"].median()
df_ambiental.loc[
    df_ambiental["Temperatura_C"] == -40.0, "Temperatura_C"
] = mediana_medellin


# =========================================================================
# OPERACIÓN: Agrupación y Cálculo de Métricas Climatológicas
# =========================================================================
# Agrupamos por 'Ciudad' y usamos .agg() para aplicar diferentes funciones a cada variable
reporte_regional = (
    df_ambiental.groupby("Ciudad")
    .agg(
        {
            "Temperatura_C": ["mean"],
            "Humedad_Porcentaje": ["median"],
            "Nivel_PM25": ["mean", "std"],
        }
    )
    .round(2)
)

# Renombrar las columnas para que el reporte impreso sea perfectamente legible
reporte_regional.columns = [
    "Temp_Promedio_(°C)",
    "Humedad_Mediana_(%)",
    "PM25_Promedio_(µg/m³)",
    "PM25_Desv_Estándar",
]

# Mostrar el reporte final ordenado de mayor a menor nivel de contaminación
print("=========================================================")
print("  REPORTE DEL MINISTERIO: INDICADORES AMBIENTALES ")
print("=========================================================")
print(reporte_regional.sort_values(by="PM25_Promedio_(µg/m³)", ascending=False))


# Celda 2 (Markdown): Análisis Crítico e Interpretación Estadística

*Esta sección contiene la interpretación analítica que el estudiante debe estructurar basándose en la salida numérica obtenida en la tabla anterior.*

---


# Análisis Crítico de la Caracterización Atmosférica Regional

Al evaluar las métricas consolidadas de las estaciones de monitoreo una vez corregidos los sesgos de medición, se extraen las siguientes conclusiones del comportamiento ambiental:

**1. Diagnóstico de la Ciudad con Mayor Contaminación:**
Al ordenar la tabla de forma descendente según el **`PM25_Promedio_(µg/m³)`**, se identifica cuál es el centro urbano con la peor calidad del aire acumulada en la muestra. Las partículas finas menores a 2.5 micrómetros ($PM_{2.5}$) son el indicador clave de riesgo respiratorio. La ciudad que encabeza esta lista requiere atención prioritaria por parte del comité de alertas tempranas para implementar medidas de mitigación inmediatas (como el "Pico y Placa" ambiental o la restricción de calderas industriales).

**2. Interpretación de la Desviación Estándar y Dinámica de Contaminación:**
La columna **`PM25_Desv_Estándar`** es fundamental porque mide la dispersión de los datos respecto a su promedio diario:

* **Si una ciudad presenta una Desviación Estándar ALTA:** Significa que sus niveles de contaminación sufren fluctuaciones extremas. No es un problema constante, sino que está ligado a **picos severos de polución** (probablemente causados por fenómenos meteorológicos específicos como inversiones térmicas, días de tráfico pesado o incendios forestales cercanos). El aire pasa de estar muy limpio a estar muy peligroso repentinamente.
* **Si una ciudad presenta una Desviación Estándar BAJA:** Significa que el comportamiento de sus partículas es homogéneo y estable. Sus niveles de contaminación varían muy poco de un día para otro. Si su promedio es alto y su desviación es baja, el escenario es crónico: sus ciudadanos respiran aire de mala calidad de forma sostenida y predecible a lo largo del tiempo.

**3. Relación Preliminar con las Variables Climatológicas:**
Cruzando los promedios térmicos y de humedad, se observa una tendencia física inicial: las ciudades con medianas de humedad relativas más altas o temperaturas de convección particulares tienden a mostrar comportamientos diferenciados en la suspensión de partículas en el aire, lo cual sirve de base para estructurar el modelado multidimensional que se realizará más adelante en el estudio.


# Actividad 4: Maquetación de Tableros Climatológicos (Subgráficos)

**Consigna para el estudiante:** El comité técnico de alertas tempranas necesita soporte visual para decretar medidas preventivas de restricción vehicular. Utilizando `matplotlib.pyplot`:

1. Establece un tema estético global limpio, nítido y con cuadrículas visibles (como `'seaborn-v0_8-whitegrid'` o `'ggplot'`).
2. Diseña una sola figura que contenga **dos subgráficos (subplots)** dispuestos de manera horizontal (1 fila, 2 columnas):
* **Gráfico Izquierdo (Barras):** Diseña un gráfico de barras que compare el promedio del `Nivel_PM25` por cada `Ciudad`. Pinta cada barra con un color temático diferente y añade la etiqueta del valor numérico exacto justo encima de cada columna.
* **Gráfico Derecho (Circular):** Genera un gráfico de pastel que represente la distribución porcentual de los días según su `Clasificacion_Calidad` (Buena, Moderada, Dañina). Añade efectos de relieve con sombras (`shadow`), formatea los porcentajes internos automáticos con un decimal y extrae la porción de categoría `"Dañina"` con un efecto `explode` para llamar la atención del lector.


3. Incorpora títulos descriptivos a cada gráfico, nombres completos en los ejes, ajusta las márgenes con `plt.tight_layout()` y exporta el lienzo mediante código en un archivo vectorial **PDF** de alta calidad listo para impresión.

Aquí tienes la solución completa para la **Actividad 4 (Maquetación de Tableros Climatológicos)**.

En este ejercicio, los estudiantes deben integrar la limpieza realizada previamente y plasmar las métricas agregadas de la actividad anterior en un **tablero visual unificado (dashboard)** utilizando la API orientada a objetos de `matplotlib` (`plt.subplots`). Además, se automatiza la exportación limpia en formato **PDF**, tal como se exige en los requerimientos.

---


### Celda 1: Código de Maquetación Gráfica y Exportación Vectorial

In [ ]:
import matplotlib.pyplot as plt
import pandas as pd

# 1. Configuración de la ruta y carga de datos
ruta_csv = r"C:\Users\marco\Documentos\docencia\fundamentos_de_programacion\2_clases\unidad4\2_datos\contaminacion_ambiental_ciudades.csv"
df_ambiental = pd.read_csv(ruta_csv)

# 2. Pipeline de limpieza previo (Actividades 2 y 3) para garantizar datos consistentes
df_ambiental = df_ambiental.dropna(subset=["Ciudad"])
mediana_medellin = df_ambiental[
    (df_ambiental["Ciudad"] == "Medellín") & (df_ambiental["Temperatura_C"] > -40)
]["Temperatura_C"].median()
df_ambiental.loc[
    df_ambiental["Temperatura_C"] == -40.0, "Temperatura_C"
] = mediana_medellin


# =========================================================================
# CONFIGURACIÓN ESTÉTICA GLOBAL
# =========================================================================
# Requerimiento: Establecer un tema limpio y nítido
plt.style.use("seaborn-v0_8-whitegrid")
plt.rcParams["font.sans-serif"] = "Arial"
plt.rcParams["font.family"] = "sans-serif"

# Preparar datos agregados para los gráficos
# Gráfico 1: Promedio de PM2.5 por ciudad
pm25_por_ciudad = df_ambiental.groupby("Ciudad")["Nivel_PM25"].mean()

# Gráfico 2: Frecuencia de la clasificación de calidad del aire
distribucion_calidad = df_ambiental["Clasificacion_Calidad"].value_counts()


# =========================================================================
# CONSTRUCCIÓN DEL LIENZO (1 Fila, 2 Columnas)
# =========================================================================
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 6))

# -------------------------------------------------------------------------
# SUBGRÁFICO IZQUIERDO: Gráfico de Barras (PM2.5 Promedio)
# -------------------------------------------------------------------------
colores_barras = ["#2C3E50", "#E74C3C", "#3498DB", "#2ECC71", "#F1C40F"]
barras = ax1.bar(
    pm25_por_ciudad.index,
    pm25_por_ciudad.values,
    color=colores_barras[: len(pm25_por_ciudad)],
    edgecolor="#333333",
    alpha=0.9,
)

ax1.set_title(
    "Concentración Promedio de PM2.5 por Ciudad", fontsize=12, fontweight="bold"
)
ax1.set_xlabel("Ciudades Monitoreadas", fontsize=10)
ax1.set_ylabel("Nivel de PM2.5 (µg/m³)", fontsize=10)
ax1.set_xticklabels(pm25_por_ciudad.index, rotation=15)

# Requerimiento: Añadir etiqueta de texto con el valor exacto sobre cada columna
for barra in barras:
    altura = barra.get_height()
    ax1.text(
        barra.get_x() + barra.get_width() / 2.0,
        altura + 1,
        f"{altura:.1f}",
        ha="center",
        va="bottom",
        fontsize=9,
        fontweight="bold",
        color="#2C3E50",
    )

# -------------------------------------------------------------------------
# SUBGRÁFICO DERECHO: Gráfico Circular (Distribución de Calidad)
# -------------------------------------------------------------------------
# Definimos colores lógicos para alertas ambientales
colores_pie = {
    "Buena": "#2ECC71",
    "Moderada": "#F1C40F",
    "Dañina": "#E74C3C",
}
# Ordenar los colores según aparezcan en los datos para evitar desajustes
lista_colores_pie = [colores_pie.get(cat, "#BDC3C7") for cat in distribucion_calidad.index]

# Requerimiento: Extraer la porción "Dañina" con un efecto explode
# Generamos la configuración dinámica del explode buscando la posición de "Dañina"
explode_config = [
    0.12 if cat == "Dañina" else 0.0 for cat in distribucion_calidad.index
]

ax2.pie(
    distribucion_calidad.values,
    explode=explode_config,
    labels=distribucion_calidad.index,
    autopct="%1.1f%%",  # Requerimiento: Porcentajes automáticos con un decimal
    shadow=True,  # Requerimiento: Efecto de relieve con sombras
    startangle=140,
    colors=lista_colores_pie,
    textprops={"fontsize": 10, "fontweight": "bold"},
)

ax2.set_title(
    "Distribución Porcentual del Estado de Calidad del Aire",
    fontsize=12,
    fontweight="bold",
)


# =========================================================================
# CONFIGURACIÓN GLOBAL Y EXPORTACIÓN AUTOMATIZADA
# =========================================================================
# Título general del reporte técnico
fig.suptitle(
    "TABLERO DE CONTROL INFORMATIVO: CALIDAD DEL AIRE REGIONAL",
    fontsize=14,
    fontweight="bold",
    color="#1A252F",
    y=0.98,
)

# Requerimiento: Ajustar márgenes para prevenir solapamientos
plt.tight_layout()

# Requerimiento: Exportar automáticamente en formato vectorial PDF listo para impresión
ruta_salida_pdf = r"C:\Users\marco\Documentos\docencia\fundamentos_de_programacion\3_paciales\4_parcial\3_imagenes\reporte_grafico_ambiental.pdf"
plt.savefig(ruta_salida_pdf, format="pdf", bbox_inches="tight")

# Mostrar en el cuaderno Jupyter
plt.show()

print(f"¡Éxito! El tablero visual ha sido exportado a: {ruta_salida_pdf}")


# Celda 2 (Markdown): Justificación de la Maquetación y Comunicación Visual

*Esta sección contiene la documentación teórica que el estudiante debe incorporar para sustentar la efectividad de sus decisiones de diseño visual.*

---


# Sustentación de la Maquetación y Semiótica del Tablero Visual

En la práctica de la ciencia de datos, los gráficos deben ser herramientas autoexplicativas que faciliten la toma de decisiones rápidas bajo situaciones de crisis. El diseño de este tablero técnico se fundamenta en los siguientes pilares de comunicación visual:

**1. Elección de Tipos de Gráficos y Variables Visuales:**

* **Gráfico de Barras (Izquierdo):** Es el estándar ideal para realizar comparaciones discretas. Permite identificar de forma inmediata qué ciudad registra la barra más alta en términos de masa microparticulada ($PM_{2.5}$). Al incluir etiquetas numéricas exactas en la cúspide de cada barra, eliminamos la fatiga visual del lector de tener que proyectar horizontalmente la mirada hacia el eje $Y$, reduciendo el error de interpretación del dato puntual.
* **Gráfico de Pastel (Derecho):** Su propósito no es comparar magnitudes finas, sino reflejar la relación parte-todo de una variable cualitativa ordinal (`Clasificacion_Calidad`). Permite a la gerencia entender la proporción global de días bajo condiciones seguras frente a los días bajo condiciones de alerta ambiental.


**2. Uso de la Psicología del Color y Énfasis Visual (*Explode*):**

* **Código de Colores Semánticos:** En el gráfico circular no se asignaron colores aleatorios. Se implementó una paleta estructurada bajo la convención internacional de índices de calidad del aire: **Verde** para una condición "Buena" (segura), **Amarillo** para "Moderada" (atención/transición) y **Rojo** para "Dañina" (peligro inminente). Esto permite que cualquier funcionario de salud pública decodifique el estado de la red en menos de un segundo.
* **Aislamiento Estratégico (*Explode*):** Al separar físicamente la porción correspondiente a la categoría **"Dañina"** fuera del eje central del pastel, se genera un punto de tensión visual intencional. Esto fuerza al ojo del espectador a concentrarse de forma prioritaria en la métrica más crítica y alarmante del informe técnico.


**3. Calidad Editorial y Robustez del Archivo Vectorial:**

* El comando `plt.tight_layout()` recalcula las cajas del lienzo para impedir que el título global (`suptitle`) choque con las etiquetas de los subgráficos, garantizando la armonía del espacio en blanco.
* La exportación en formato **PDF** asegura propiedades vectoriales nativas. A diferencia de un formato de píxeles (`PNG` o `JPEG`), el archivo PDF preserva las fuentes de texto y las líneas geométricas como ecuaciones matemáticas, permitiendo hacer ampliaciones o impresiones a gran escala en pósteres ejecutivos sin sufrir degradación por pixelación.


# Actividad 5: Modelado de Correlación Multidimensional Climatológica

**Consigna para el estudiante:** Existe el debate científico de si las variables climáticas como la temperatura y la humedad influyen directamente en la concentración de contaminantes suspendidos en el aire.

1. Construye un diagrama de dispersión (`plt.scatter`) donde el eje $X$ sea la `Temperatura_C` y el eje $Y$ sea el `Nivel_PM25`.
2. Introduce una tercera dimensión al análisis modificando el color de los marcadores en función del porcentaje de `Humedad_Porcentaje` (pista: usa el argumento `c` y aplica un mapa de calor o `cmap` adecuado como `'Blues'` o `'viridis'`). Configura la barra de colores lateral (`plt.colorbar()`) para que la escala sea legible y disminuye la opacidad (`alpha=0.75`) para controlar el solapamiento.
3. **Conclusión Científica Integral (Markdown):** Evalúa con ojo crítico el patrón de puntos resultante. ¿Se observa una mayor acumulación de días con calidad del aire "Dañina" (altos niveles de PM2.5) bajo condiciones de alta temperatura y baja humedad, o viceversa? Sintetiza tus hallazgos estadísticos y visuales para justificar qué condiciones meteorológicas del año representan el mayor peligro ambiental para los ciudadanos.

# Solución completa para la **Actividad 5 (Modelado de Correlación Multidimensional Climatológica)**.

Esta actividad final cierra el ciclo analítico diseñado para tus estudiantes. Aquí se evalúa la capacidad de construir y decodificar un gráfico avanzado de dispersión en **tres dimensiones visuales** utilizando Matplotlib: el eje $X$ (Temperatura), el eje $Y$ (Nivel de PM2.5) y el **color de los puntos** (mapeado dinámicamente a la Humedad mediante una barra de colores o `colorbar`).

# Celda 1: Código de Dispersión Multidimensional y Mapeo de Calor (`cmap`)

In [ ]:
import matplotlib.pyplot as plt
import pandas as pd

# 1. Configuración de la ruta y carga de datos
ruta_csv = r"C:\Users\marco\Documentos\docencia\fundamentos_de_programacion\3_paciales\4_parcial\2_datos\contaminacion_ambiental_ciudades.csv"
df_ambiental = pd.read_csv(ruta_csv)

# 2. Pipeline de limpieza previo (Idéntico a las actividades anteriores)
df_ambiental = df_ambiental.dropna(subset=["Ciudad"])
mediana_medellin = df_ambiental[
    (df_ambiental["Ciudad"] == "Medellín") & (df_ambiental["Temperatura_C"] > -40)
]["Temperatura_C"].median()
df_ambiental.loc[
    df_ambiental["Temperatura_C"] == -40.0, "Temperatura_C"
] = mediana_medellin


# =========================================================================
# CONSTRUCCIÓN DEL GRÁFICO DE DISPERSIÓN AVANZADO
# =========================================================================
plt.figure(figsize=(10, 7))

# Seteamos el estilo global
plt.style.use("seaborn-v0_8-whitegrid")

# Requerimiento: Eje X = Temperatura, Eje Y = Nivel_PM25
# Requerimiento: Tercera dimensión -> c = Humedad_Porcentaje usando el mapa de color 'viridis'
# Requerimiento: Opacidad -> alpha = 0.75 para controlar el solapamiento de puntos
dispersion = plt.scatter(
    x=df_ambiental["Temperatura_C"],
    y=df_ambiental["Nivel_PM25"],
    c=df_ambiental["Humedad_Porcentaje"],
    cmap="viridis",
    s=75,  # Tamaño de los marcadores aumentado para mejor visualización
    alpha=0.75,
    edgecolors="#333333",
    linewidths=0.8,
)

# =========================================================================
# PERSONALIZACIÓN Y ELEMENTOS DE REFERENCIA
# =========================================================================
# Añadir títulos y etiquetas con unidades del sistema internacional
plt.title(
    "Análisis de Correlación: Contaminación por PM2.5 frente a Temperatura y Humedad",
    fontsize=13,
    fontweight="bold",
    pad=15,
)
plt.xlabel("Temperatura Ambiente (°C)", fontsize=11)
plt.ylabel("Concentración de Material Particulado PM2.5 (µg/m³)", fontsize=11)

# Requerimiento: Configurar la barra de colores lateral para que la escala sea legible
cbar = plt.colorbar(dispersion)
cbar.set_label(
    "Porcentaje de Humedad Relativa (%)", fontsize=11, fontweight="bold"
)
cbar.ax.tick_params(labelsize=10)

# Ajustar los límites de los ejes para enmarcar la nube de puntos estéticamente
plt.xlim(df_ambiental["Temperatura_C"].min() - 2, df_ambiental["Temperatura_C"].max() + 2)
plt.ylim(0, df_ambiental["Nivel_PM25"].max() + 10)

# Evitar cortes en los bordes antes de mostrar
plt.tight_layout()

# Mostrar gráfico en el cuaderno
plt.savefig(r"C:\Users\marco\Documentos\docencia\fundamentos_de_programacion\3_paciales\4_parcial\3_imagenes\grafico_dispersion_contaminacion.png", \
    dpi=300)
plt.show()


# Celda 2 (Markdown): Conclusión Científica e Interpretación de Fenómenos Atmosféricos

*Esta sección contiene el análisis conceptual de alto nivel que el estudiante debe redactar, demostrando que comprende la interacción física de las variables climáticas cruzadas en el gráfico.*

---


# Conclusión Científica Integral: Dinámicas de Interacción Climatológica


Al evaluar la distribución tridimensional de la nube de puntos, donde la posición espacial describe el binomio **Temperatura-Contaminación** y el gradiente cromático añade el factor de **Humedad**, se desprenden las siguientes observaciones científicas y ambientales:


**1. Evaluación de la Tendencia Estructural (Temperatura vs. PM2.5):**
Si observamos una acumulación de puntos con pendientes ascendentes hacia la derecha del gráfico, se confirmaría una **correlación lineal positiva** entre la temperatura y el material particulado. Físicamente, las altas temperaturas en entornos urbanos suelen acelerar las reacciones fotoquímicas en la atmósfera, transformando gases precursores en partículas finas suspendidas secundarias ($PM_{2.5}$). Además, el calor extremo puede inhibir ciertos flujos de viento locales, atrapando la polución a nivel del suelo.


**2. Decodificación de la Tercera Dimensión (El Rol de la Humedad Relativa):**
La barra de color `viridis` mapea los valores de humedad (donde los tonos oscuros/morados representan aire seco y los tonos claros/amarillos indican alta saturación de agua). Al cruzar visualmente el color con la altura del eje $Y$:

* **Condiciones de Alta Peligrosidad (Zona Crítica):** Si los puntos ubicados en la parte más alta del eje $Y$ (niveles alarmantes de PM2.5) muestran predominantemente colores amarillos/claros, significaría que la combinación de calor y alta humedad actúa como un "aglomerante" que mantiene las partículas suspendidas en el aire pesado.
* Por el contrario, si los puntos críticos son de color morado/oscuro, demostraría que los días secos y calurosos son los que disparan las crisis respiratorias, ya que la ausencia de lluvias impide el fenómeno de "lavado atmosférico" (deposición húmeda), permitiendo que el polvo y el hollín floten libremente.


**3. Recomendación de Políticas Públicas basadas en Datos:**
A partir de este análisis multidimensional, se concluye que el comité de alertas tempranas de la red de monitoreo no debe vigilar únicamente las emisiones de las chimeneas o tubos de escape, sino los **pronósticos meteorológicos**. Las ventanas climáticas específicas identificadas en el cuadrante de alta densidad de puntos (ej. días que superen ciertos grados Celsius combinados con rangos específicos de humedad) constituyen el **disparador científico óptimo** para decretar estados de prevención, alertas o emergencias ambientales de manera proactiva, protegiendo la salud pública antes de que los sensores registren picos irreversibles de contaminación.


# Criterios de Evaluación:

* **Criterio de Saneamiento Espacial (25%):** Habilidad del estudiante para entender que la falta de la variable geográfica (`Ciudad`) anula la validez del registro en un estudio regional y aplicar correctamente filtros de eliminación de nulos indexados.
* **Agregaciones Climatológicas (25%):** Uso impecable de la sintaxis de Pandas para obtener múltiples descriptores estadísticos y destreza conceptual interpretando la desviación estándar del PM2.5.
* **Calidad Gráfica y Editorial (25%):** Correcto uso de subgráficos independientes en Matplotlib, rotulado completo de unidades físicas (como °C o g/m³) y exportación automatizada y limpia a PDF.
* **Pensamiento de Ciencia de Datos (25%):** Calidad analítica de la respuesta final. El alumno debe ser capaz de decodificar un scatter plot tridimensional (Eje X, Eje Y y color de puntos por humedad) para emitir un juicio argumentado sobre dinámicas de contaminación ambiental.